"""Create a standalone standard-GLB playback page for the isolated motion proof."""
import json
from catalog import ROOT,OUT
HTML='''<!doctype html><meta charset="utf-8"><title>Tree41 measured animation proof</title><style>body{margin:0;background:#30352e;color:white;font:16px system-ui}header{position:absolute;z-index:2;max-width:700px;background:#202520dd;padding:16px}canvas{display:block}button,input{margin:8px}a{color:#bdf}</style>
<header><b>Tree41 measured 3D animation proof — HOLD for phase appearance</b><p>Existing crown mesh, measured native leaf motion, stationary wood and fixed source-ray depth. Phase0 geometry is unchanged. Native RGB/alpha changes remain incomplete; this is not final animation parity. Preview rate:30 native ticks/s.</p><button id="play">Pause</button><label>Phase<input id="phase" type="range" min="0" max="13" step="1" value="0"></label><span id="status">Loading…</span><p><a href="animated-tree41.glb">Standalone animated GLB</a> · <a href="representative-phases.png">Source and oblique actual views</a> · <a href="temporal-coverage.json">Coverage hold</a></p></header>
<script type="importmap">{"imports":{"three":"THREE","three/addons/":"ADDONS"}}</script><script type="module">
import * as THREE from 'three';import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';import{OrbitControls}from'three/addons/controls/OrbitControls.js';
const renderer=new THREE.WebGLRenderer({antialias:true});renderer.setSize(innerWidth,innerHeight);renderer.setPixelRatio(devicePixelRatio);document.body.append(renderer.domElement);const scene=new THREE.Scene();scene.background=new THREE.Color(0x30352e);const camera=new THREE.PerspectiveCamera(40,innerWidth/innerHeight,.1,10000);const controls=new OrbitControls(camera,renderer.domElement);scene.add(new THREE.HemisphereLight(0xffffff,0x555544,2));const light=new THREE.DirectionalLight(0xffffff,2);light.position.set(-300,500,300);scene.add(light);
try{const gltf=await new GLTFLoader().loadAsync('animated-tree41.glb');scene.add(gltf.scene);const bounds=new THREE.Box3().setFromObject(gltf.scene),center=bounds.getCenter(new THREE.Vector3()),size=bounds.getSize(new THREE.Vector3());camera.position.copy(center).add(new THREE.Vector3(size.x*.8,size.y*.7,size.x*1.8));controls.target.copy(center);controls.update();const mixer=new THREE.AnimationMixer(gltf.scene);const clip=gltf.animations[0];if(!clip)throw Error('Missing standard animation');mixer.clipAction(clip).play();let playing=true;const clock=new THREE.Clock();const play=document.querySelector('#play'),phase=document.querySelector('#phase');play.onclick=()=>{playing=!playing;play.textContent=playing?'Pause':'Play'};phase.oninput=()=>{playing=false;play.textContent='Play';mixer.setTime(+phase.value*.1+.0001)};window.animationProof={loaded:true,animations:gltf.animations.length,duration:clip.duration};document.querySelector('#status').textContent='Loaded standard morph animation';function animate(){requestAnimationFrame(animate);const dt=clock.getDelta();if(playing){mixer.update(dt);phase.value=Math.floor((mixer.time%clip.duration)/.1)}controls.update();renderer.render(scene,camera)}animate();}catch(error){document.querySelector('#status').textContent=String(error);window.animationProof={loaded:false,error:String(error)}}
addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)});
</script>'''
def main():
 root='/@fs/'+str(ROOT/'level-editor/app/node_modules/three')
 text=HTML.replace('"THREE"',json.dumps(root+'/build/three.module.js')).replace('"ADDONS"',json.dumps(root+'/examples/jsm/'))
 path=OUT/'tree41-animation-proof/index.html';path.write_text(text);print(path)
if __name__=='__main__':main()
