"""Build an isolated standard-loader viewer for the rotating mission sign."""
import json
from catalog import ROOT,OUT

def main():
 dst=OUT/'state-sign-candidate/animation-export-v2';three='/@fs/'+str(ROOT/'level-editor/app/node_modules/three');imports=json.dumps({'imports':{'three':three+'/build/three.module.js','three/addons/':three+'/examples/jsm/'}})
 page='''<!doctype html><meta charset="utf-8"><title>Croisement02 sign animation proof</title><style>body{margin:0;background:#454545;color:white;font:15px system-ui}header{position:absolute;z-index:2;background:#202020dc;padding:14px;max-width:600px}canvas{display:block}button,input{margin:6px}a{color:#acf}</style><header><b>Rotating sign: isolated standard GLB proof</b><p>32 native poses, 2 ticks each at 25 Hz. Per-pose timber shading and painted ground shadow. Full physical map integration remains separate.</p><button id="play">Pause</button><input id="phase" type="range" min="0" max="31" step="1"><span id="status">Loading…</span></header><script type="importmap">IMPORTS</script><script type="module">
import * as THREE from 'three';import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
const renderer=new THREE.WebGLRenderer({antialias:true});renderer.setSize(innerWidth,innerHeight);renderer.setPixelRatio(devicePixelRatio);renderer.setClearColor(0x454545);document.body.append(renderer.domElement);const scene=new THREE.Scene(),camera=new THREE.OrthographicCamera(-40*innerWidth/innerHeight,40*innerWidth/innerHeight,40,-40,.1,1000);camera.position.set(0,20+Math.sin(35*Math.PI/180)*400,Math.cos(35*Math.PI/180)*400);camera.lookAt(0,20,0);const controls=new OrbitControls(camera,renderer.domElement);controls.target.set(0,20,0);controls.update();let playing=true;const button=document.querySelector('#play'),slider=document.querySelector('#phase');
try{const gltf=await new GLTFLoader().loadAsync('animated-sign.glb');scene.add(gltf.scene);if(gltf.animations.length!==1)throw Error('Expected one animation');const mixer=new THREE.AnimationMixer(gltf.scene),clip=gltf.animations[0];mixer.clipAction(clip).play();const nodes=[];gltf.scene.traverse(o=>{if(Number.isInteger(o.userData.native_body_frame)||Number.isInteger(o.userData.native_frame))nodes.push(o)});if(nodes.length!==96)throw Error('Missing phase nodes '+nodes.length);window.animationProof={loaded:true,duration:clip.duration,pause(){playing=false;button.textContent='Play'},setTime(t){mixer.setTime(t);renderer.render(scene,camera)},states(){return nodes.map(o=>({name:o.name,body:o.userData.native_body_frame??null,shadow:o.userData.native_frame??null,scale:o.scale.toArray()}))}};button.onclick=()=>{playing=!playing;button.textContent=playing?'Pause':'Play'};slider.oninput=()=>{animationProof.pause();animationProof.setTime(+slider.value*.08+.001)};document.querySelector('#status').textContent='Standard node animation loaded';const clock=new THREE.Clock();function draw(){requestAnimationFrame(draw);const dt=clock.getDelta();if(playing){mixer.update(dt);slider.value=Math.floor((mixer.time%clip.duration)/.08)}controls.update();renderer.render(scene,camera)}draw()}catch(e){window.animationProof={loaded:false,error:String(e)};document.querySelector('#status').textContent=String(e)}
</script>'''.replace('IMPORTS',imports);(dst/'index.html').write_text(page);print(dst/'index.html')

if __name__=='__main__':main()
