"""Prepare a standalone partial-motion viewer without changing editor playback."""
from catalog import OUT

def main():
    root=OUT/'log-late-settling-proof-v1';app=OUT.parents[1]/'app';html='''<!doctype html><meta charset="utf-8"><title>Two-log late settling proof</title><style>body{margin:0;background:#30352e;color:white;font:16px system-ui}header{padding:16px}canvas{display:block}button,input{margin:8px}</style><header><b>Private partial motion proof: two upper logs, ticks63–87</b><p>Measured late translations only. Earlier collapse, other bodies, rolling texture and production integration remain incomplete.</p><button id="play">Pause</button><input id="tick" type="range" min="63" max="87" value="63" step="1"><span id="status">Loading</span></header><script type="importmap">{"imports":{"three":"/@fs/APP/node_modules/three/build/three.module.js","three/addons/":"/@fs/APP/node_modules/three/examples/jsm/"}}</script><script type="module">
import * as THREE from 'three';import{GLTFLoader}from'three/addons/loaders/GLTFLoader.js';import{OrbitControls}from'three/addons/controls/OrbitControls.js';
const renderer=new THREE.WebGLRenderer({antialias:true});renderer.setSize(innerWidth,650);document.body.append(renderer.domElement);const scene=new THREE.Scene();scene.background=new THREE.Color(0x30352e);const camera=new THREE.PerspectiveCamera(40,innerWidth/650,.1,10000),controls=new OrbitControls(camera,renderer.domElement);scene.add(new THREE.HemisphereLight(0xffffff,0x555544,2));const sun=new THREE.DirectionalLight(0xffffff,2);sun.position.set(-300,500,300);scene.add(sun);
try{const gltf=await new GLTFLoader().loadAsync('motion.glb');scene.add(gltf.scene);const bounds=new THREE.Box3().setFromObject(gltf.scene),center=bounds.getCenter(new THREE.Vector3()),size=bounds.getSize(new THREE.Vector3());camera.position.copy(center).add(new THREE.Vector3(-size.x*.8,size.x*.8,size.x*1.7));controls.target.copy(center);controls.update();const mixer=new THREE.AnimationMixer(gltf.scene);if(gltf.animations.length!==2)throw Error('Expected two separate body clips');const actions=[];for(const clip of gltf.animations){const action=mixer.clipAction(clip);action.setLoop(THREE.LoopOnce,1);action.clampWhenFinished=true;action.play();actions.push(action)}let playing=true,tick=63;const start=(63+1)/25,end=(87+1)/25,clock=new THREE.Clock();function setTime(t){for(const action of actions){action.paused=false;action.enabled=true}mixer.setTime(t);gltf.scene.updateMatrixWorld(true);tick=t*25-1;document.querySelector('#tick').value=tick;renderer.render(scene,camera)}setTime(start);document.querySelector('#play').onclick=()=>playing=!playing;document.querySelector('#tick').oninput=e=>{playing=false;setTime((+e.target.value+1)/25+.00001)};window.animationProof={loaded:true,animations:gltf.animations.length,pause:()=>playing=false,setTime,positions:()=>gltf.scene.children.map(n=>({name:n.name,position:n.position.toArray()})),bounds:{min:bounds.min.toArray(),max:bounds.max.toArray()}};document.querySelector('#status').textContent='Standard GLB clips loaded';function animate(){requestAnimationFrame(animate);const dt=clock.getDelta();if(playing){let t=(tick+1)/25+dt;if(t>end)t=start;setTime(t)}controls.update();renderer.render(scene,camera)}animate()}catch(e){window.animationProof={loaded:false,error:String(e)};document.querySelector('#status').textContent=String(e)}
</script>'''.replace('APP',str(app));(root/'index.html').write_text(html)
if __name__=='__main__':main()
