"""Freeze the scoped stone-cap correction with full-asset and local contact evidence."""
import sys,json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[3];sys.path[:0]=[str(Path(__file__).parent),str(ROOT/'level-editor/refinement/blender')]
from catalog import OUT
from evidence_io import sha,write_json
from build_review_gallery import build

def main():
 d=OUT/'restart7-fence-residual/wall101-cap-v2';full=d/'full-asset-review-v1';dest=OUT/'restart7-fence-residual/frozen-wall101-card-v1';dest.mkdir(exist_ok=False);model=d/'model.blend';digest=sha(model);assert digest=='05151df87b5a40c98de2ed6b39a87d395b9bd7676cadaf15b99375bf46b7e71b';guard=json.loads((full/'receipt.json').read_text());assert guard['model_sha256']==digest and not guard['lost_pixels']and guard['all_six_other_receivers_exact']
 review=dest/'root-and-self-review.json';write_json(review,dict(model_sha256=digest,root_review='PASS scoped five-center cap contour direction after actual/contact8, solid/contact8, source comparison and gain-overlay review; one edge sample[1545,844] disclosed as stone/grass antialias border.',self_review='Full-asset actual8 and solid8 subsequently viewed: all seven receivers visible without clipping; native camera first. Six retained receiver fingerprints exact; full11861 native-mask centers have11gains and zero losses.',root_review_scope='Geometry only; no new texture approval or source-perfect claim.',full_asset_guard_sha256=sha(full/'receipt.json'),geometry_user_approved=False,texture_api_called=False))
 item=dict(id='croisement02-east-stone-wall-and-gate-cap101',name='East stone wall — small cap contour correction',status='ready-for-user',technical_eligible=True,model=str(model),solid=str(full/'solid-eight.png'),textured=str(full/'actual-eight.png'),context=str(d/'source-comparison.png'),source_comparison=str(d/'source-gain-overlay.png'),source_comparison_label='Native cap gains: cyan inside mask101; red one disclosed outside edge sample',validation=str(full/'receipt.json'),ownership=str(d/'source-audit.json'),review=str(review),notes='Only15 vertices on stone receiver010 move, at most2.638world units. Five target cap centers recovered; whole native101 domain gains11 and loses0. One adjacent outside-mask sample[1545,844] remains a disclosed border overreach. Six other receivers stay exact. Gray on newly changed unseen cap surfaces remains pending texture fill; no texture approval or source-perfect claim. Original unrelated zero-area face on part005 remains unchanged.',approval_scope='Exact changed stone-cap geometry with all retained wall/gate receivers; no texture generation, source ownership transfer or publication.',animation_reviews=[dict(id='cap-contact',name='Cap contact detail — original camera first',description='Same saved model, cropped to changed cap and neighboring wall/gate.',solid=str(d/'solid-eight.png'),textured=str(d/'actual-eight.png'),context=str(d/'source-comparison.png'))])
 manifest=dest/'review-candidates.json';write_json(manifest,dict(map='Croisement02 cap contour',review_kind='geometry',scope='Next grouped pool only; original-camera-first full asset and close supplements. Other approved cards and existing ledgers remain unchanged.',items=[item]));build(manifest,dest/'gallery');write_json(dest/'freeze-receipt.json',dict(status='Frozen next-pool geometry card',model_sha256=digest,base_sha256=guard['base_sha256'],files={str(p):sha(p)for p in [manifest,review,full/'receipt.json',dest/'gallery/evidence.json']},user_approved=False,texture_approved=False));print(dest/'gallery/index.html')
if __name__=='__main__':main()
