"""Freeze the two independently reviewed continuous-root geometry decisions."""
import json,hashlib
from pathlib import Path
REPO=Path(__file__).resolve().parents[3];ROOT=REPO/'level-editor/work/croisement02-refinement/restart6-source-coverage'
def sha(path):return hashlib.sha256(path.read_bytes()).hexdigest()
def write(path,value):path.write_text(json.dumps(value,indent=2)+'\n')
def main():
 out=ROOT/'continuous-roots-ready-v1';out.mkdir(exist_ok=False);items=[];cards=[]
 for tree,v,digest in [(39,2,'dc08ec8fcdc0b11cc67cb4407649ac8a8ab9be46a7ac79ae492e7cf6027b528d'),(18,3,'c37a7d21b278da592bc3ec3d6c8d2f490d66b6831a8323700ff68bfa7d5a2257')]:
  work=ROOT/f'tree{tree}-continuous-finished-v{v}';model=work/'model.blend';assert sha(model)==digest;guard=json.load(open(work/'saved-guard.json'));upper=json.load(open(work/'upper-assembly-guard.json'));assert guard['model_sha256']==upper['model_sha256']==digest;assert not guard['failures']and not guard['lost_native_coverage'];assert upper['upper_world_position_uv_material_graph_records_exact'];assert upper['assembled_exterior']=={'nonmanifold_edges':0,'degenerate_faces':0}
  image_names=[('Full asset: original game camera first','textured-sheet.png'),('Full solid shape: original game camera first','solid-sheet.png'),('Lower trunk: approved parent above, continuous candidate below','lower-solid-review/comparison.png'),('Native source / overlay / isolated wood','source-comparison.png'),('Ground contact and lower bark appearance','contact-sheet.png')]
  evidence_files=['model.blend','saved-guard.json','upper-assembly-guard.json','restoration.json','lower-solid-review/evidence.json']+[p for _,p in image_names];evidence={str(work/p):sha(work/p)for p in evidence_files};notes=['Geometry decision only: continuous lower trunk and grounded root construction replace overlapping collars.','Observed source edges restored exactly; upper wood, crown and attachment support remain unchanged.','New hidden root depth is inferred from the asset’s own native silhouette.','Gray reverse surfaces and inherited stretched/olive bark remain a separate appearance task; no completed-texture claim.']
  if tree==39:notes.append('Source parts095/096/097 retain canonical names and per-face ownership; their uncapped exterior boundaries form one closed assembled surface.')
  root_receipt=out/f'tree{tree}-root-review.json';write(root_receipt,{'model_sha256':digest,'reviewer':'root','status':'PASS geometry scope','reviewed_images':{str(work/p):sha(work/p)for _,p in image_names},'scope':'Root personally reviewed final actual8, solid8, native comparison, contact4 and lower before/after4. Fin and collar artifacts resolved; upper/crown preserved. New gray reverse and inherited bark remain fill work.','user_approval':'pending'})
  evidence[str(root_receipt)]=sha(root_receipt);disclosure=out/f'tree{tree}-disclosure.json';write(disclosure,{'model_sha256':digest,'notes':notes});evidence[str(disclosure)]=sha(disclosure);revision=hashlib.sha256(json.dumps(evidence,sort_keys=True).encode()).hexdigest();asset=f'croisement02-tree-{tree}'
  items.append({'asset_id':asset,'name':f'Tree {tree}: continuous trunk and source contour','model_sha256':digest,'model':str(model),'review_revision':revision,'decision':'pending','scope':'Continuous lower-root geometry only; native source and upper support preserved. Unknown reverse appearance pending.','evidence':evidence,'displayed_images':[{'label':label,'file':str(work/p),'sha256':sha(work/p)}for label,p in image_names],'notes':notes});cards.append({'card_id':f'{asset}-continuous-root-geometry','title':f'Tree {tree}: continuous lower trunk and roots','asset_ids':[asset]})
 write(out/'bound-members.json',{'items':items,'cards':cards,'scope':'Two separate exact geometry decisions. No inherited user approval or texture completeness.'});print(out/'bound-members.json')
if __name__=='__main__':main()
