import assert from 'node:assert/strict';
import {readFile,writeFile} from 'node:fs/promises';
import {resolve,join} from 'node:path';
import {createHash} from 'node:crypto';
import {validateStateDelivery} from '../../shared/src/state-delivery.ts';
import {verifyNativePresentationSource} from '../../app/src/native-state-presentation.ts';
import {decode} from '../../app/node_modules/fast-png/lib/index.js';
const folder=resolve('level-editor/work/croisement02-refinement/restart27-orphan-delivery-v1');
const sha=b=>createHash('sha256').update(b).digest('hex');
const config=JSON.parse(await readFile(join(folder,'reader-config.json'),'utf8'));
const checked=async p=>{const bytes=await readFile(p.path);assert.equal(sha(bytes),p.sha256,p.path);return bytes;};
const contract=JSON.parse(await checked(config.contract)),source=JSON.parse(await checked(config.source_contract));
validateStateDelivery(contract);assert.deepEqual(contract.native,source.native);assert.equal(contract.families.length,1);
const family=contract.families[0];assert.deepEqual(family.patch_ids,[config.identity]);assert.deepEqual(family.physical.initial,{kind:'absent'});assert.equal(family.physical.applied[0].model_scene,'scatter-site-13');assert.deepEqual(family.physical.applied[0].position,[0,0,0]);
const mission=JSON.parse(await checked(config.mission_source.data)),level=JSON.parse(await checked(config.mission_source.level));
await verifyNativePresentationSource(contract.native,{name:config.mission_source.name,data:mission,level,camera:config.mission_source.camera});
await checked(config.model);await checked(config.catalog);
for(const r of config.native_reader.mapping)await checked({path:r.file,sha256:r.sha256});
const patch=contract.native.patch_states.find(p=>p.id===config.identity),frame=patch.initial[0];
const resource=config.native_reader.mapping.find(r=>r.logical_path===frame.path);const png=decode(await readFile(resource.file));assert.equal(png.channels,4);assert.equal(png.width,4);assert.equal(png.height,1);assert(!png.data.some((v,i)=>i%4===3&&v));
const wrong=structuredClone(contract);wrong.families[0].body_terminal_tick--;assert.throws(()=>validateStateDelivery(wrong),/terminal/);
const path=structuredClone(contract);path.families[0].physical.applied[0].model='../scatter.glb';assert.throws(()=>validateStateDelivery(path),/physical source/);
const report={status:'PASS_PRIVATE_PRODUCTION_CONTRACT_CPU',contract:config.contract,native_contract_unchanged:true,source_authority_verified:true,source_absent_initial_pixels:0,terminal_tick:family.body_terminal_tick,native_resources_checked:config.native_reader.mapping.length,negative_wrong_terminal_rejected:true,negative_unsafe_model_path_rejected:true,browser_verified:false,other31_initials_not_faked:true};
await writeFile(join(folder,'verification.json'),JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify(report));
