"""Freeze additive root geometry and its exact retained tree base for batch review."""
import json,sys
from pathlib import Path
ROOT=Path(__file__).resolve().parents[3]
sys.path[:0]=[str(Path(__file__).parent),str(ROOT/'level-editor/refinement/blender')]
from catalog import OUT
from evidence_io import sha,write_json
from build_review_gallery import build

def main():
 base=OUT/'restart3-tree06-root/research-roots-v5';package=base/'final-candidate-package.json';data=json.loads(package.read_text());addition=Path(data['addition']['path']).resolve();retained=ROOT/data['original_approved_base']['path'];dest=OUT/'restart3-tree06-root/frozen-geometry-card-v1';assert not(dest/'freeze-receipt.json').exists();dest.mkdir(exist_ok=True)
 assert sha(addition)==data['addition']['sha256']=='54943a848b57f7db3dfbd4ca15fa9ab9be1a69ccda8a44f49e823dac4086ce0f'
 assert sha(retained)==data['original_approved_base']['sha256']=='3258b6e6dea0b4490d9681c2d978a1f04d2fb32d9bbab646fbe11489531bfe3f'
 for r in data['evidence']:assert sha(Path(r['path']))==r['sha256']
 review=dest/'root-review.json';write_json(review,dict(status='PASS scoped additive root geometry; user approval pending',reviewer='root coordinator',evidence_method='Personally viewed final appearance-v3 source/contact8 and neutral new-volume/contact8, read final package and support proof',addition_sha256=sha(addition),retained_base_sha256=sha(retained),assembly_contract=data['assembly_contract'],scope='Rounded continuous grounded root addition; exact retained original tree components. Gray rims explicit unknown. Source residuals disclosed, no source-perfect claim.',residuals=data['residuals'],render_native_samples_exact=247,render_native_samples_covered=256,texture_approved=False,batch_scope='Subsequent pool only; closing-v7 remains unchanged at eleven cards.'))
 item=dict(id='croisement02-tree-06-root-addition',name='Tree 06 — grounded root continuation',status='ready-for-user',technical_eligible=True,model=str(addition),model_sha256=sha(addition),solid=str(base/'neutral-solid/contact-eight.png'),textured=str(base/'appearance-v3/contact-eight.png'),context=str(base/'appearance-v3/source-comparison.png'),source_comparison=str(base/'appearance-v3/source-residual-overlay.png'),source_comparison_label='Native source residuals: red missing wood samples; blue bank overlap',validation=str(base/'final-contact-audit.json'),ownership=str(package),review=str(review),approval_scope='Only this exact additive root geometry assembled with the exact retained tree base; not new texture fill, source-perfect parity, scene selection or publication.',notes='Smooth connected roots meet the bank. Retains the four approved tree components exactly. Native source fit recovers 256/313 wood samples: 57 remain missing; 28 scoped bank samples and 37 full-crop samples lie outside the wood domain. 247/256 covered center samples match the review render exactly; nine edge samples mix during raster sampling. Gray rims and backs are unknown material awaiting texture fill after geometry approval. Existing upper trunk reverse texture defects remain unchanged.',retained_base=dict(path=str(retained),sha256=sha(retained)),assembly_contract=data['assembly_contract'],animation_reviews=[dict(id='new-volume',name='New volume alone',description='Same exact rounded additive volume, neutral material only; no retained tree or bank occlusion.',solid=str(base/'neutral-solid/new-volume-eight.png'),textured=str(base/'appearance-v3/contact-eight.png'),context=str(base/'appearance-v3/source-comparison.png'))])
 manifest=dest/'review-candidates.json';write_json(manifest,dict(map='Croisement02 root continuation',review_kind='geometry',scope='Subsequent batch pool. Original game camera is top-left. Decision binds the root addition and exact retained base hashes together; gray unknown appearance remains incomplete.',items=[item]));build(manifest,dest/'gallery')
 receipt=dict(status='Frozen geometry card for subsequent batch pool',addition_sha256=sha(addition),retained_base_sha256=sha(retained),assembly_contract=data['assembly_contract'],files={str(p):sha(p)for p in [manifest,review,package,dest/'gallery/evidence.json',dest/'gallery/index.html']},user_approved=False,texture_approved=False,closing_v7_modified=False)
 write_json(dest/'freeze-receipt.json',receipt);print(dest/'gallery/index.html')
if __name__=='__main__':main()
