"""Freeze the bounded bank source-contact appearance review."""
import sys,json
from pathlib import Path
HERE=Path(__file__).resolve().parent;sys.path[:0]=[str(HERE),str(HERE.parents[1]/'refinement/blender')]
from catalog import OUT
from evidence_io import sha,write_json
from build_review_gallery import build
def main():
 d=OUT/'restart4-bank103-source-overlay-v2';v=json.loads((d/'validation.json').read_text());g=json.loads((d/'saved-source-guards.json').read_text());h=sha(d/'model.blend');assert h==v['model_sha256']==g['model_sha256']=='c0b8458ed39b0412fae16a03384c5585c3271cc5eb48072f0354380ab8f0072e';assert g['exact_native_rgba_first_hit_centers']==103 and g['excluded_root_owned_centers_with_no_overlay']==28
 write_json(d/'root-review.json',dict(status='ready-for-user',reviewer='root',model_sha256=h,validation_sha256=sha(d/'validation.json'),saved_source_guards_sha256=sha(d/'saved-source-guards.json'),viewed={'paired-review.png':sha(d/'paired-review.png')},scope='Exact103 source-contact appearance overlay on unchanged bank; not new bank or root volume',findings=['Root viewed paired native/oblique before-after and validation; scoped appearance PASS.','Small native grass/contact fragments restored; sharp source pixels versus soft inferred surroundings disclosed.','Measured structural root-bank contact resolves suspension concern without changing geometry.','Reopened exact103 source RGBA and28 root-owned exclusions pass.'],user_approval=None))
 selfreview=json.loads((d/'self-review.json').read_text());selfreview['status']='Scoped visual and reopened source guards PASS';selfreview['saved_source_guards_sha256']=sha(d/'saved-source-guards.json');write_json(d/'self-review.json',selfreview)
 item=dict(id='croisement02-bank103-source-contact',name='Northern bank — 103 native contact samples',status='ready-for-user',technical_eligible=True,user_approval=None,review_scope='saved source-contact appearance only',model=str(d/'model.blend'),solid=str(d/'paired-review.png'),solid_label='Original camera top-left: before / after; oblique below',textured=str(d/'paired-review.png'),textured_label='Saved bank appearance with current approved tree06',source_comparison=str(OUT/'restart4-bank131-current-audit-v2/source-marked.png'),source_comparison_label='Native art: pink103 bank samples / cyan28 root-covered exclusions',validation=str(d/'saved-source-guards.json'),review=str(d/'root-review.json'),notes=['Restore exactly103 native grass/contact colors using a surface overlay clipped to those source cells. Original bank geometry, UVs and material images remain exact;28 root-covered samples remain excluded.','The overlay follows the unchanged bank surface with0.002 units offset along the native camera ray to avoid coplanar flicker. It does not add a bank mass or root extension.','Native pixels remain sharper than surrounding inferred bank texture. Brown/dark contact colors do not prove physical wood or broader ownership.','Approved tree06 and current ground remain unchanged. Root structural contact is measured independently; some projecting tips remain elevated as previously documented.','No synthesis. Exact packed source RGBA checked after reopen, with103 overlay first hits. This appearance needs its own user decision; no whole-bank or root-geometry reapproval is requested.'])
 write_json(d/'review-candidates.json',dict(map='Croisement02 bank source contact',items=[item],without_packets=[],status_counts={'pending appearance':1}));build(d/'review-candidates.json',d/'gallery');write_json(d/'ready-for-next-batch.json',dict(status='ready-for-user',scope=item['review_scope'],model_sha256=h,candidates=str(d/'review-candidates.json'),gallery=str(d/'gallery/index.html'),user_approval=None))
if __name__=='__main__':main()
