/** Pin compiler gameplay frames from hydrated old and proposed map placements. */
import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';import crypto from 'node:crypto';
import {parseStoredMap} from '../../shared/src/stored-level.ts';
import {partMatrix} from '../../shared/src/level3d.ts';
const base=path.resolve('level-editor/work/croisement02-refinement');const stage=path.join(base,'restart2-textures/post-batch15-static-candidate-v1');const out=path.join(base,'restart4-gameplay-migration-v4');if(!fs.existsSync(out))fs.mkdirSync(out);assert(!fs.existsSync(path.join(out,'frame-inventory.json')));
const read=(p:string)=>JSON.parse(fs.readFileSync(p,'utf8'));const sha=(p:string)=>crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex');const pins:Record<string,string>={};
function descriptors(root:string){const index=path.join(root,'index.json');pins[index]=sha(index);return new Map(read(index).assets.filter((e:any)=>e.source_map?.toLowerCase()==='croisement02').map((e:any)=>{const f=path.resolve(root,e.descriptor);pins[f]=sha(f);return[e.id,{file:f,value:read(f)}];}));}
const old=descriptors(path.resolve('level-editor/library/3d-assets'));const newer=descriptors(path.join(stage,'map-assets/3d-assets'));const oldMap=path.resolve('level-editor/library/scenes/croisement02.rhlos-map.json'),newMap=path.join(stage,'croisement02.rhlos-map.json');pins[oldMap]=sha(oldMap);pins[newMap]=sha(newMap);
const oldDoc=parseStoredMap(read(oldMap),new Map([...old].map(([id,x]:any)=>[id,x.value]))),newDoc=parseStoredMap(read(newMap),new Map([...newer].map(([id,x]:any)=>[id,x.value])));assert.deepEqual(oldDoc.camera,newDoc.camera);
const owners=new Map<string,string>();for(const[id,x]of newer as any)for(const p of x.value.parts){assert(!owners.has(p.node),'Duplicate proposed source part');owners.set(p.node,id);}
const angle=newDoc.camera.elevation_deg*Math.PI/180;const point=(m:number[],p:number[])=>{const q=[p[0],-p[1]/Math.sin(angle),p[2]/Math.cos(angle)];return[0,1,2].map(r=>m[r]*q[0]+m[r+4]*q[1]+m[r+8]*q[2]+m[r+12]);};
function frame(doc:any,id:string,node:string){const objects=doc.objects.filter((o:any)=>o.node===`asset:${id}:${node}`);assert(objects.length<=1,'Multiple placements require explicit migration selection');return objects[0]?partMatrix(doc.camera,doc,objects[0]):null;}
const aliases=new Map<string,string>();for(const[id,e]of old as any)for(const p of e.value.parts){if(owners.has(p.node))continue;if(p.source_obstacle!==undefined){const matches=[...newer].flatMap(([nid,x]:any)=>x.value.parts.filter((q:any)=>q.source_obstacle===p.source_obstacle).map((q:any)=>q.node));assert(matches.length<=1,'Ambiguous source-obstacle alias');if(matches.length===1)aliases.set(p.node,matches[0]);}}
const candidates=[...old].filter(([id,x]:any)=>!newer.has(id)&&x.value.parts.length&&x.value.parts.every((p:any)=>owners.has(aliases.get(p.node)??p.node))).map(([id,x]:any)=>({id,sha256:sha(x.file)}));const records:any[]=[];const errors:any[]=[];const totals:Record<string,number>={};
for(const r of candidates){const entry:any=old.get(r.id);assert(entry);const d=entry.value;assert.equal(sha(entry.file),r.sha256);const offsets:any={},mapping:any={},checks:any[]=[];
 for(const p of d.parts){const newNode=aliases.get(p.node)??p.node;const target=owners.get(newNode)!;assert(target);const nd:any=newer.get(target);const np=nd.value.parts.find((x:any)=>x.node===newNode);let a=frame(oldDoc,d.id,p.node),b=frame(newDoc,target,newNode);
  if(!a){assert(!d.gameplay,'Missing placed source gameplay frame '+d.id);continue;}assert(b,'Missing proposed gameplay frame');assert(a.every((v,i)=>i>=12||Math.abs(v-b![i])<1e-12),'Nontranslation gameplay frame');const dx=a[12]-b[12],dy=-(a[13]-b[13])*Math.sin(angle),dz=(a[14]-b[14])*Math.cos(angle);offsets[p.node]=[dx,dy,dz];mapping[p.node]=target;let drift=0;
  if(p.obstacle_local_game){const x=p.obstacle_local_game,y=np.obstacle_local_game;assert(y&&x.points.length===y.points.length);for(let i=0;i<x.points.length;i++)for(const z of['z_bottom','z_top']){const u=point(a,[x.points[i].x,x.points[i].y,x.points[i][z]]),v=point(b,[y.points[i].x,y.points[i].y,y.points[i][z]]);drift=Math.max(drift,...u.map((x,i)=>Math.abs(x-v[i])));}if(drift>1e-8)errors.push({node:p.node,kind:'world_obstacle_drift',max:drift});for(const k of new Set([...Object.keys(x),...Object.keys(y)]))if(k!=='points'&&JSON.stringify(x[k])!==JSON.stringify(y[k]))errors.push({node:p.node,kind:'obstacle_property_changed',field:k});}
  const matrix=(m:number[])=>[0,1,2,3].map(r=>[0,1,2,3].map(c=>m[c*4+r]));checks.push({node:p.node,destination:target,destination_node:newNode,old_world:matrix(a),new_world:matrix(b),local_game_offset:[dx,dy,dz],world_obstacle_drift:drift});
 }
 if(d.gameplay)for(const[k,v]of Object.entries(d.gameplay))if(Array.isArray(v))totals[k]=(totals[k]??0)+v.length;
 records.push({source_id:d.id,source_descriptor:entry.file,gameplay:d.gameplay??null,offsets,node_destinations:mapping,node_aliases:Object.fromEntries(d.parts.map((p:any)=>[p.node,aliases.get(p.node)??p.node])),frame_checks:checks});
}
const report={status:errors.length?'HOLD runtime-frame mismatch':'PASS runtime compiler frame inventory',camera:newDoc.camera,frame_authority:'parseStoredMap + partMatrix from actual old/new stored placements; internal visual GLB node matrices intentionally do not redefine compiler gameplay coordinates',source_descriptors:records.length,gameplay_sources:records.filter(r=>r.gameplay).length,records,feature_counts:totals,errors,pins,destination_descriptors:Object.fromEntries([...newer].map(([id,x]:any)=>[id,x.file])),retirement_candidates:records.map(r=>r.source_id)};fs.writeFileSync(path.join(out,'frame-inventory.json'),JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify({sources:records.length,gameplay:report.gameplay_sources,errors}));assert.equal(errors.length,0);
