"""Freeze the bounded49 contact-color appearance for grouped user review."""
import sys,json
from pathlib import Path
HERE=Path(__file__).resolve().parent;sys.path[:0]=[str(HERE),str(HERE.parents[1]/'refinement/blender')]
from catalog import OUT
from evidence_io import sha,write_json
from build_review_gallery import build
def main():
 d=OUT/'restart4-fringe49-source-contact-v1';h=sha(d/'model.blend');assert h=='67b6f3c249ab96ccb37e73508ee043032c1c567535fb2fd134b02ae7ebafb8da';v=json.loads((d/'validation.json').read_text());assert v['changed_pixels']==49
 phase=OUT/'restart2-state/phase51-state-precedence-v1.json'
 write_json(d/'root-review.json',dict(status='ready-for-user',reviewer='root',model_sha256=h,validation_sha256=sha(d/'validation.json'),exact_delta_sha256=sha(d/'exact-delta-check.json'),context_sha256=sha(d/'context-validation.json'),phase_precedence_sha256=sha(phase),viewed={f'mask{i}/{n}.png':sha(d/f'mask{i}/{n}.png')for i in [19,25,95]for n in ['source','paired']},scope='49 near-ground source-contact colors only; no physical wood/ground ownership transfer',findings=['Root personally viewed all three source sheets and native/opposite before-after; scoped appearance PASS.','Both elevated samples excluded. Tree25 elevated sample has0.952 percent existing pixel-corner geometry coverage; Tree19 remains one explicit uncovered dark tip edge, not a floor repair.','Gray reverse tree25 context is unchanged and outside this appearance scope.'],user_approval=None))
 item=dict(id='croisement02-fringe49-contact-colors',name='Ground contacts — 49 native source colors',status='ready-for-user',technical_eligible=True,user_approval=None,review_scope='saved49-pixel contact-color appearance only',model=str(d/'model.blend'),solid=str(d/'mask19/paired.png'),solid_label='Tree19: native before/after top, opposite below',textured=str(d/'mask95/paired.png'),textured_label='Fence95: native before/after top, opposite below',source_comparison=str(d/'mask19/source.png'),source_comparison_label='Tree19 native source / selected9 / saved ground',source_comparison_secondary=str(d/'mask25/source.png'),source_comparison_secondary_label='Tree25: single low-toe contact; elevated sample excluded',source_trace=str(d/'mask95/source.png'),source_trace_label='Fence95 native source / selected39 / saved ground',projection_errors=str(d/'mask25/paired.png'),projection_errors_label='Tree25 native/opposite; preexisting gray reverse unchanged',validation=str(d/'validation.json'),review=str(d/'root-review.json'),notes=['Appearance only: exact49 source colors on the existing ground —9 Tree19 contact pixels,1 Tree25 low-toe pixel and39 olive fence95 fringe pixels. This is conservative source-context preservation, not proof of physical wood/ground ownership.','All2,064,335 outside RGBA pixels, approved206+14 patches, alpha, geometry and UVs remain exact. All49 samples are ground first hits with the reviewed current foreground.','Two elevated samples remain excluded: Tree25[117,918] has a tiny existing corner intersection; Tree19[1594,147] remains an explicit uncovered dark tip edge, not floor.','Dynamic initial/transition overlays and final-last-transition stamps retain precedence above the static base. No state asset changes or API synthesis.','Original-camera views are top-left; opposite views show the same narrow color changes. Gray Tree25 reverse geometry is unchanged context, outside this ground appearance decision.'])
 write_json(d/'review-candidates.json',dict(map='Croisement02 source contact colors',items=[item],without_packets=[],status_counts={'pending appearance':1}));build(d/'review-candidates.json',d/'gallery');write_json(d/'ready-for-next-batch.json',dict(status='ready-for-user',target_batch='V17',scope=item['review_scope'],model_sha256=h,candidates=str(d/'review-candidates.json'),gallery=str(d/'gallery/index.html'),user_approval=None))
if __name__=='__main__':main()
