import * as THREE from 'three';
import {createGltfLoader} from '/@fs/home/phire/data/dev/2026/robin-hood-the-legend-of-sherwood/level-editor/app/src/gltf-loader.ts';
const manifest=await(await fetch('./manifest.json')).json();
const scene=new THREE.Scene();scene.background=new THREE.Color('#303030');scene.add(new THREE.AmbientLight(0xffffff,1.7));
const sun=new THREE.DirectionalLight(0xffffff,2);sun.position.set(-.45,.70,.55);scene.add(sun);
const renderer=new THREE.WebGLRenderer({antialias:true,preserveDrawingBuffer:true});renderer.setSize(1200,900);renderer.setPixelRatio(1);document.body.append(renderer.domElement);
const camera=new THREE.OrthographicCamera(-1,1,1,-1,.01,20000),loader=createGltfLoader(),checks=[],models=new Map();
const sha=async(bytes)=>Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',bytes)),v=>v.toString(16).padStart(2,'0')).join('');
async function load(pin){if(models.has(pin.sha256))return models.get(pin.sha256).clone(true);const response=await fetch(pin.url);if(!response.ok)throw Error('Resource unavailable '+pin.url);const bytes=await response.arrayBuffer();if(await sha(bytes)!==pin.sha256)throw Error('Resource hash changed');const gltf=await loader.parseAsync(bytes,'');let meshes=0;gltf.scene.traverse(o=>{if(o.isMesh){meshes++;for(const m of Array.isArray(o.material)?o.material:[o.material])if(m.map&&!m.map.image?.width)throw Error('Missing material image')}});checks.push({sha256:pin.sha256,meshes});models.set(pin.sha256,gltf.scene);return gltf.scene.clone(true)}
for(const r of manifest.receivers){const root=await load(r.model);root.position.add(new THREE.Vector3(...r.position));root.rotation.x+=r.rotation[0];scene.add(root)}
const entries=[];
for(const record of manifest.records){const endpoints={};for(const endpoint of ['initial','applied']){const group=new THREE.Group(),bindings=record.family.physical[endpoint];for(const binding of Array.isArray(bindings)?bindings:[]){const root=await load(record.models[binding.model]);root.position.add(new THREE.Vector3(...binding.position));group.add(root)}group.visible=false;scene.add(group);endpoints[endpoint]=group}entries.push({record,endpoints})}
function show(index,endpoint,view=0){for(const entry of entries)for(const root of Object.values(entry.endpoints))root.visible=false;const entry=entries[index],root=entry.endpoints[endpoint];root.visible=true;root.updateWorldMatrix(true,true);const framing=root.children.length?root:entry.endpoints.applied;framing.updateWorldMatrix(true,true);const bounds=new THREE.Box3().setFromObject(framing),center=bounds.getCenter(new THREE.Vector3()),size=bounds.getSize(new THREE.Vector3()),t=35*Math.PI/180;const half=Math.max(size.x/(4/3),size.y*Math.cos(t)+size.z*Math.sin(t),70)*.7;camera.left=-half*4/3;camera.right=half*4/3;camera.top=half;camera.bottom=-half;const direction=new THREE.Vector3(0,Math.sin(t),Math.cos(t)*(view===0?1:-1));camera.position.copy(center).addScaledVector(direction,3000);camera.lookAt(center);camera.updateProjectionMatrix();renderer.render(scene,camera);document.querySelector('#title').textContent=entry.record.id+' / '+endpoint+' / '+(view===0?'original camera direction':'opposite contact view')+' — foliage and actors excluded';return {id:entry.record.id,endpoint,view,empty:!root.children.length,bounds:[bounds.min.toArray(),bounds.max.toArray()],camera:camera.position.toArray(),target:center.toArray(),direction:direction.toArray()}}
window.stateContactProof={ready:true,checks,manifest,show,capture:()=>renderer.domElement.toDataURL('image/png')};show(0,'initial',0);
