"""Freeze two independently reviewed lower root hypotheses for grouped review."""
import json,hashlib
from pathlib import Path
from PIL import Image
OUT=Path(__file__).resolve().parents[2]/'work/croisement02-refinement';ROOT=OUT/'restart6-source-coverage';DEST=ROOT/'toe-ready-v15-v2';DEST.mkdir(exist_ok=False)
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def write(p,d):p.write_text(json.dumps(d,indent=2)+'\n')
items=[];cards=[]
for number,expected in[(19,'8908000d0712c8383074bc464b17cb6c39346d4bb39bb80791063141c11187dd'),(25,'2c7f634653453cbe2514b59db2390d4f07b0b232d252e376d3b03cb739f4a88c')]:
 model=ROOT/f'tree{number}-toe-finished-v12/model.blend';assert sha(model)==expected;review=ROOT/f'tree{number}-toe-review-v12';guard=model.parent/'saved-guard-v2.json';g=json.load(open(guard));e=json.load(open(review/'evidence.json'));assert not e['lost']and not g['lower_native_failures'];assert g['crown_exact']and g['upper_triangles_exact']and g['retained_packed_images_exact'];assert g['assembled_topology']=={'nonmanifold':0,'degenerate':0};folder=DEST/f'tree{number}';folder.mkdir();prior=ROOT/f'tree{number}-toe-review-v4/before';images=[]
 for name,title in [('textured8.png','Full asset, original camera first'),('solid8.png','Full solid geometry'),('source-comparison.png','Original source / overlay / physical wood')]:images.append((title,review/'after'/name))
 for name,title in [('solid-contact4.png','Original above / continuous grounded geometry below'),('contact4.png','Original above / retained native and pending reverse appearance below')]:
  a=Image.open(prior/name).convert('RGBA');b=Image.open(review/'after'/name).convert('RGBA');assert a.size==b.size;canvas=Image.new('RGBA',(a.width,a.height+b.height));canvas.paste(a,(0,0));canvas.paste(b,(0,a.height));path=folder/f'comparison-{name}';canvas.save(path);images.append((title,path))
 notes=['Geometry-only decision: removes overlapping lower slits/caps, preserving the existing upper wood and crown.',f'All {e["old_hits"]} previous native center hits retained; {g["lower_native_exact"]} lower native RGBA samples exact. Original used packed source images remain exact.','New gray reverse/foot surfaces and inherited olive/green/stretched bark remain unfinished appearance; no texture completion is implied.','Hidden lower depth is inferred from this tree’s own source; ground contact is Z0.15. No other assets, masks, or gameplay were changed.']
 if number==19:notes+=['Of the original 47 exposed target centers, 27 now gain physical wood coverage. Remaining dark/contact fringe is not forced into solid wood.','The short projecting left spur remains elevated; the main forward root is grounded.']
 else:notes+=['Of the original 46 exposed target centers, 32 now gain physical wood coverage. This does not establish all ambiguous ivy/contact pixels as wood.','One accepted upper AA center, [119,908], incidentally gains coverage from the lower reconstruction; the other four AA centers remain unchanged misses.','The deeper curved rear buttress is inferred. Observed ivy/green source colors remain protected; they are not permission to synthesize bark over those pixels.']
 write(folder/'disclosure.json',dict(model_sha256=expected,notes=notes));root=dict(model_sha256=expected,status='PASS scoped geometry, pending grouped user decision',reviewer='root coordinator',viewed=['full actual8','full solid8','ground contact4','ground solid-contact4','native source comparison','same-camera original solid contact4'],findings='Overlapping slits/caps removed; continuous grounded feet; source silhouettes and unchanged crowns retained.',limitations=notes[2:]);write(folder/'root-review.json',root)
 files=[model,guard,model.parent/'finish.json',review/'evidence.json',review/('self-review-v2.json'if number==25 else 'self-review.json'),folder/'root-review.json',folder/'disclosure.json',ROOT/'source-role132-v1/reviewed-role-proposal.json',ROOT/'source-role132-v1/target-classification-v12.json']+[p for _,p in images];evidence={str(p.resolve()):sha(p)for p in files};revision=hashlib.sha256(json.dumps(evidence,sort_keys=True).encode()).hexdigest();asset=f'croisement02-tree-{number}';items.append(dict(asset_id=asset,name=f'Tree {number}: continuous grounded lower roots',model=str(model.resolve()),model_sha256=expected,review_revision=revision,decision='pending',scope='Lower root geometry only; unfinished appearance disclosed.',evidence=evidence,displayed_images=[dict(label=label,file=str(p.resolve()),sha256=sha(p))for label,p in images],notes=notes));cards.append(dict(card_id=f'{asset}-continuous-root-toe-geometry',title=f'Tree {number}: continuous grounded roots',asset_ids=[asset]))
 write(folder/'texture-input-scope.json',dict(model_sha256=expected,geometry_approval='pending grouped user decision; no API yet',source_guard={str(guard.resolve()):sha(guard)},scope='New lower receiver unknown appearance only, preserving approved parent appearance and exact native overlays.',protect=['All unchanged crown/upper geometry, materials, UVs and packed images.','Continuous toe native projection: observed image alpha and all saved native first-hit samples.','Observed green/olive/ivy RGB is protected regardless of material color.','Existing generated parent appearance outside genuinely new receiver surfaces.'],editable_authority='Derive unknown texels from explicit constant-gray fallback branches of private continuous toe materials minus native alpha; never classify ownership from gray RGB alone. Bind actual face/UV support before API.',supplementary_references=['Own native tree source','Leicester southeast cottage tree','Leicester moat bank tree'],forbidden=['Geometry changes','Source ownership transfer','Other tree references','API before grouped geometry approval']))
write(DEST/'bound-members.json',dict(items=items,cards=cards));print(DEST/'bound-members.json')
