"""Freeze one geometry-only review for all source-bound hiding mound placements."""
from pathlib import Path
import sys,json
P=Path(__file__).resolve().parent;sys.path[:0]=[str(P),str(P.parents[1]/'refinement/blender')]
from catalog import OUT
from evidence_io import sha,write_json
from build_review_gallery import build

def main():
 worker=OUT/'restart15-hiding-mounds/all-placements-v1';model=worker/'model.blend';digest=sha(model);validation=json.loads((worker/'validation.json').read_text());guard=json.loads((worker/'saved-native-guard.json').read_text());author=json.loads((worker/'author-review-v1.json').read_text());assert guard['status']=='PASS'and author['status']=='AUTHOR_GEOMETRY_PASS';assert digest==validation['model_sha256']==guard['model_sha256']==author['model_sha256'];assert len(validation['records'])==20 and sum(len(r['aliases'])for r in validation['records'])==32
 for part in ['shape-review-v1','contacts-v1','neighborhoods-v1','source-contexts-v1']:
  assert json.loads((worker/part/'report.json').read_text())['model_sha256']==digest
 out=OUT/'restart15-hiding-mounds/grouped-geometry-review-v1';out.mkdir(exist_ok=False);endpoints=[]
 for row in validation['records']:
  tag=row['tag'];endpoints.append(dict(id=tag,asset_id='croisement02-hiding-mound-'+tag,name=tag+' — '+str(len(row['aliases']))+' mission instance(s)',model=str(model),model_sha256=digest,textured=str(worker/'shape-review-v1'/f'{tag}-actual-sheet.png'),solid=str(worker/'shape-review-v1'/f'{tag}-coverage-gray-sheet.png'),context=str(worker/'contacts-v1'/f'{tag}-contact-three.png'),source_comparison=str(worker/'source-contexts-v1'/f'{tag}-source-comparison.png'),validation=str(worker/'saved-native-guard.json'),review=str(worker/'author-review-v1.json')))
 item=dict(id='croisement02-hiding-mounds-all-initial-geometry',name='Initial hiding-place leaf piles — all 32 instances',status='independent-review-pending',technical_eligible=False,user_approval=None,review_scope='initial endpoint geometry only',model=str(model),model_sha256=digest,textured=str(worker/'shape-review-v1/site-16-actual-sheet.png'),solid=str(worker/'shape-review-v1/site-16-coverage-gray-sheet.png'),context=str(worker/'contacts-v1/site-16-contact-three.png'),source_comparison=str(worker/'source-contexts-v1/site-16-source-comparison.png'),review=str(worker/'author-review-v1.json'),validation=str(worker/'saved-native-guard.json'),endpoint_reviews=endpoints,notes=['One shared construction, fitted to20 distinct positions and bound to32 exact mission instances. Each pile contains67 closed irregular clumps. Full alias and support witnesses are in the validation receipt.','First view is always the original camera. All20 placements have native and reverse textured/gray views; six elevated or uneven support sites have complete eight-view orbits.','All20,220 known native pixel centers match exactly. Ground/bank/wall contact views reveal supports; separately pinned neighborhood views retain surrounding scenery. These are complementary views, not a claim of identical native and physical occlusion.','Geometry approval only. Gray inferred caps and stretched source textures on hidden faces are visible and await later appearance work. Ordinary pile height is6.47 versus width50; the slope variant reaches8.96.','Applied scatter, transition motion, characters, gameplay, new texture generation and publication are excluded. No user approval is inferred from the earlier limited-trio direction review.'])
 candidates=out/'review-candidates.json';write_json(candidates,dict(map='Croisement02 initial hiding mound geometry',items=[item],without_packets=[]));build(candidates,out/'gallery');write_json(out/'review-packet.json',dict(status='Independent root review pending',id=item['id'],model_sha256=digest,review_candidates=str(candidates),gallery=str(out/'gallery/index.html'),evidence_sha256=sha(out/'gallery/evidence.json'),author_review=str(worker/'author-review-v1.json'),aliases=[dict(site=r['tag'],instances=r['aliases'])for r in validation['records']],scope=item['review_scope'],api_calls=0,shared_catalog_modified=False));print(out/'review-packet.json')
if __name__=='__main__':main()
