"""Freeze native endpoint art and explicit leaf/rim/depth hypotheses."""
from pathlib import Path
import json,hashlib
import numpy as np
from PIL import Image,ImageDraw
O=Path.cwd()/'level-editor/work/croisement02-refinement';D=O/'restart9-hole-endpoints/source-plan-v1';D.mkdir(parents=True,exist_ok=True);h=lambda p:hashlib.sha256(p.read_bytes()).hexdigest();C=O/'restart7-source-patch-delivery/contracts-v1';A=O/'restart7-source-patch-delivery/physical-scope-v1/report.json';record=next(r for r in json.load(open(A))['records']if r['profile']=='Croisement01 - hole');rep=record['members'][0];contract=C/rep['contract'];assert h(contract)==rep['contract_sha256'];native=json.load(open(contract))['native'];patch=next(p for p in native['patch_states']if p['id']==rep['id']);F=O/'source-states/mission-patches'/rep['id'];base=Image.open(O/'source-states/covered.png').convert('RGBA');anchor=rep['display_position'];phases=[];canvas=Image.new('RGB',(1152,440),(35,35,35));draw=ImageDraw.Draw(canvas)
for i,(tag,frame)in enumerate([('initial',patch['initial'][0]),('applied',patch['transition'][-1])]):
 path=F/('initial-000.png'if tag=='initial'else'transition-029.png');assert h(path)==frame['sha256'];a=Image.open(path).convert('RGBA');render=base.copy();where=[anchor[k]+frame['offset'][k]for k in (0,1)];render.alpha_composite(a,tuple(where));crop=(anchor[0],anchor[1]+10,anchor[0]+100,anchor[1]+110);cropim=render.crop(crop).resize((384,384),Image.Resampling.NEAREST);canvas.paste(cropim,(i*384,32));draw.text((i*384+5,8),tag+' native endpoint on original base',fill='white');phases.append(dict(phase=tag,source=str(path),sha256=h(path),offset=frame['offset'],size=list(a.size),positive_alpha=int((np.array(a)[:,:,3]>0).sum()),world_anchor_native_display=anchor))
source=Image.open(F/'transition-029.png').convert('RGBA');mark=Image.new('RGBA',source.size,(35,35,35,255));mark.alpha_composite(source);polygon=[(26,18),(35,13),(44,16),(53,20),(50,31),(42,35),(30,30),(23,25)];dr=ImageDraw.Draw(mark);dr.line(polygon+[polygon[0]],fill=(255,50,160,255),width=1);canvas.paste(mark.resize((384,293),Image.Resampling.NEAREST),(768,32));draw.text((773,8),'Applied: proposed recessed interior',fill='white');draw.text((773,338),'Pink contour is inferred role boundary.',fill='white');draw.text((773,356),'Leaf scatter stays separate physical detail.',fill='white');canvas.save(D/'phase-source-plan.png')
plan=dict(status='Source and placement plan; physical construction pending',profile=record['profile'],mission_instances=30,unique_positions=17,authority=dict(path=str(A),sha256=h(A)),representative_contract=dict(path=str(contract),sha256=h(contract)),phases=phases,members=record['members'],receiver_audit=str(O/'restart9-hole-endpoints/receiver-audit-v1/report.json'),native_behavior='Initial camouflage remains until transition; applied appearance is final transition stamped into background. Reset restores original substrate and initial display. No invented continuous physical collapse.',source_role={'initial':'Low leaf camouflage over opening; connected leaf clusters and thin grounded scatter.','applied':'Leaf rim and scattered leaves remain around dark recess. Colored source alpha is appearance coverage, not proof of solid depth.','proposed_inner_polygon_terminal_pixel_xy':polygon},geometry_hypothesis={'cover_height_world_units':[0.2,3.0],'recess_depth_world_units':16,'hidden_depth':'inferred; original projection constrains visible source coordinates only','native_camera_degrees':35,'reuse':'One endpoint pair, translated along native rays to exact physical receiver support at each display anchor','source_rgba':'Own original frame UV projected exactly, known front unchanged; unknown side/back material neutral until approved geometry fill.'},receiver_constraints=['All30 native elevations0, but two unique positions688,177 and797,271 hit approved bank atZ43.949.','Applied recess requires a state-local ground/bank aperture to expose below-surface bowl; no global ground edit or permanent source-role transfer.','Additional NWrock coverage audit pending.','No gameplay sectors, masks, motion, timing, or actions changed.'],files={'phase-source-plan.png':h(D/'phase-source-plan.png')});(D/'plan.json').write_text(json.dumps(plan,indent=2)+'\n');print(h(D/'plan.json'))
