"""Bind approved geometry and exact Batch14 bark inputs for texture generation."""
from pathlib import Path
import sys,json,hashlib,shutil
R=Path.cwd();sys.path[:0]=[str(R/'level-editor/refinement')]
from prepare_texture_packet import prepare
O=R/'level-editor/work/croisement02-refinement';B=O/'restart6-five-bark-fill-v1';read=lambda p:json.loads(p.read_text());h=lambda p:hashlib.sha256(p.read_bytes()).hexdigest();approval=O/'restart3-review-batches/batch-v14/user-approval.json';assert h(approval)=='8417fd11d5bd7ee78f209f474111bb3619faa43e1b8e30f31a359cf7b6ea4981'
for n in [int(x)for x in sys.argv[1:]]:
 asset=f'croisement02-tree-{n:02d}';S=B/f'tree-{n:02d}-input-v{2 if n==18 else 1}';card=read(S/'ready-candidate-v1.json');decision=next(m for c in read(approval)['cards']for m in c['members']if m['asset_id']==asset);assert decision['scope']=='texture-input' and decision['review_revision']==card['review_revision'];assert decision['model_sha256']==card['candidate_model_sha256']
 for path,entry in card['files'].items():assert h(Path(path))==entry['sha256']
 D=B/f'tree-{n:02d}-fill-v1';assert not D.exists();P=D/'packet';P.mkdir(parents=True);(P/'views').mkdir();W=D/'worker';W.mkdir();(W/'model.blend').symlink_to(card['candidate_model']);proof=read(S/'input-review.json');meta=read(S/'views.json')
 for v in meta['views']:
  i=v['index'];shutil.copyfile(S/f'views/view-{i}-textured.png',P/f'views/view-{i}-textured.png');shutil.copyfile(S/f'views/view-{i}-known.png',P/f'views/view-{i}-known.png');shutil.copyfile(S/f'actual/view-{i}-solid.png',P/f'views/view-{i}-solid.png');v['ownership_sha256']=h(P/f'views/view-{i}-known.png')
 (P/'views.json').write_text(json.dumps(meta,indent=2)+'\n');shutil.copyfile(S/'input.png',P/'textured.png');shutil.copyfile(S/'solid.png',P/'solid.png');geometry_authority=proof['geometry_approval'];gp=Path(geometry_authority['geometry_approval_file']);assert h(gp)==geometry_authority['geometry_approval_sha256'];geometry=next(m for c in read(gp)['cards']for m in c['members']if m['asset_id']==asset);assert geometry['scope']=='geometry'and geometry['model_sha256']==card['candidate_model_sha256'];evidence={str(p):dict(path=str(p),sha256=h(p))for p in [approval,gp,S/'ready-candidate-v1.json',S/'root-review.json',S/'input-review.json',B/'source-authority.json',*[p for p in P.rglob('*')if p.is_file()]]};identity=dict(asset_id=asset,model_sha256=card['candidate_model_sha256'],evidence={k:v['sha256']for k,v in evidence.items()});rev=hashlib.sha256(json.dumps(identity,sort_keys=True,separators=(',',':')).encode()).hexdigest();item=dict(id=asset,workspace=str(W),status='ready-for-user',stored_material_validation='PASS',solid=str(P/'solid.png'),textured=str(P/'textured.png'),revision=dict(sha256=rev,model_sha256=card['candidate_model_sha256'],evidence=evidence),approval_provenance=dict(original_geometry=geometry,approved_new_input=decision,input_receipt=str(approval),scope='Exact approved geometry and separately Batch14 approved scoped bark input. Original shader/source protection required after bake.'))
 (D/'review-manifest.json').write_text(json.dumps(dict(version=1,items=[item]),indent=2)+'\n');(D/'decisions.json').write_text(json.dumps(dict(version=1,decisions=[dict(asset_id=asset,scope='geometry',decision='approved',revision_sha256=rev,exact_user_text=read(gp)['exact_user_text'],original_geometry_decision=geometry,approved_input_decision=decision,translation='Unchanged approved model plus explicitly approved new input; no new appearance approval')]),indent=2)+'\n');result=prepare(D/'review-manifest.json',asset,D/'experiment',D/'decisions.json');refs=read(S/'auxiliary-references.json');assert h(D/'experiment/input.png')==refs['input_sha256'];assert h(D/'experiment/solid.png')==refs['lighting_sha256'];(D/'experiment/auxiliary-references.json').write_text(json.dumps(refs,indent=2)+'\n');print(result,flush=True)
