"""Conservative local clearance proposals from complete sampled source footprints."""
from pathlib import Path
import json,hashlib
import numpy as np
from scipy.optimize import minimize,Bounds,LinearConstraint
from PIL import Image,ImageDraw
ROOT=Path(__file__).resolve().parents[3];B=ROOT/'level-editor/work/croisement02-refinement/restart14-butterflies';O=B/'footprint-path-proposal-v2';O.mkdir(exist_ok=True);fp=B/'all7-footprint-audit-v2/report.json';audit=json.loads(fp.read_text());prior=json.loads((B/'flight-path-constraints-v1/proposal.json').read_text());D=np.roll(np.eye(99),-1,axis=1)-np.eye(99);DD=D@D;rows=[];sheet=Image.new('RGB',(1120,840),'#252525');dr=ImageDraw.Draw(sheet)
for j,seq in enumerate(range(8,15)):
 f=[r for r in audit['phase_records']if r['sequence']==seq];old=prior['rows'][j];lower=np.array([max(10,r['maximum_noncanopy_receiver_height']+r['z_extent']+8)for r in f]);dist=np.minimum(abs(np.arange(99)[:,None]-np.arange(99)),99-abs(np.arange(99)[:,None]-np.arange(99)));start=np.max(lower[None,:]-3*dist,axis=1)
 result=minimize(lambda h:float(h.mean()+.3*np.sum((DD@h)**2)),start,jac=lambda h:np.ones(99)/99+.6*DD.T@(DD@h),method='SLSQP',bounds=Bounds(lower,np.full(99,400)),constraints=[LinearConstraint(D,-3,3)],options={'maxiter':400,'ftol':1e-8});assert result.success;h=result.x;conflicts=[];above=[]
 for r,z in zip(f,h):
  for owner,(lo,hi)in r['tree_height_intervals'].items():
   if z-r['z_extent']<=hi and z+r['z_extent']>=lo:conflicts.append({'phase':r['phase'],'owner':owner,'tree_z_interval':[lo,hi],'butterfly_envelope':[z-r['z_extent'],z+r['z_extent']],'status':'CONSERVATIVE_POTENTIAL_COLLISION_NEEDS_EXACT_GEOMETRY'})
   elif lo>z+r['z_extent']:above.append({'phase':r['phase'],'owner':owner,'status':'ABOVE_PATH_NATIVE_ORDER_ADAPTER_OBLIGATION_NOT_ALTITUDE_FAILURE'})
 body=np.array(old['body_anchors']);sin=np.sin(np.deg2rad(35));cos=np.cos(np.deg2rad(35));world=np.c_[body[:,0],-(body[:,1]+cos*h)/sin,h];clear=min(z-r['z_extent']-r['maximum_noncanopy_receiver_height']for r,z in zip(f,h));rows.append({'sequence':seq,'height_minmax':[float(h.min()),float(h.max())],'maximum_step':float(np.max(abs(D@h))),'minimum_sampled_noncanopy_clearance':float(clear),'world_zup_knots':world.tolist(),'source_screen_anchors':old['body_anchors'],'projection_error':float(np.max(abs(np.c_[world[:,0],-sin*world[:,1]-cos*world[:,2]]-body))),'potential_tree_collision_intervals':conflicts,'above_path_order_obligations':above,'whole_anatomy_status':'01conserved-rig sampledfootprint'if seq==8 else'observed body/wingalpha footprint+8Z conservativeextent; six unbuilt anatomies remain unvalidated'})
 y=j*120;dr.text((8,y+3),f'Butterfly{j+1}: full footprint localZ {h.min():.1f}-{h.max():.1f}; tree intervals {len(conflicts)}',fill='white');dr.line([(70+i*10,y+110-z*.6)for i,z in enumerate(h)],fill='#68e6cb',width=2)
 for r in conflicts:xx=70+r['phase']*10;dr.ellipse((xx-2,y+104,xx+2,y+108),fill='#ff685f')
sheet.save(O/'full-footprint-local-height.png');report={'status':'CPU_PATH_PROPOSALS_NOT_RENDERED_OR_INSTALLED','footprint_sha256':hashlib.sha256(fp.read_bytes()).hexdigest(),'rows':rows,'source_semantics_correction':'Verified AddElement routes empty-polyline elevated FX into non-animation display-order list; not polyline sorting/fallback.05 is backgroundFX. blit_type0 standard transparent blit. Native ordered composition is owned by missing_fences; physical oblique depth separate.','method':'Cyclic full-sampled-footprint noncanopy upperenvelope plus actual01worldZextent / conservative8Zothers +8clearance, max3Zstep per2ticks; all geometric assumptions inferred, no camera-driven canopy lift.','source05_order':'Capture restores current map background; concurrent mission stamps require preserved capture/restore sequence, not replacement with staticfloor.','representative_context_next':[{'sequence':8,'cluster':'logging','phases':[0,30,49],'why':'Conserved physical anatomy available; full-footprint localclearance test, nativeadapter distinct.'},{'sequence':10,'cluster':'south field','phases':[0,49,74],'why':'Haystack proximity; own source phase anchors, unbuilt anatomy not propagated.'},{'sequence':13,'cluster':'western rocks','phases':[0,49,74],'why':'Rock/shrub clearance with local height, not canopy-above blanket.'},{'sequence':12,'cluster':'south background special','phases':[5,40,51],'why':'05 sourcecapture/restore and hole/hidingPC overlaps, nativecomposition vs ordinary oblique depth.'}],'limits':['Physical backside surfaces considered even if culled from native render; alpha uses bilinearlevel0, no mip proof.','Grid sampledfootprint clearance does not prove continuous swept mesh collision freedom.','Tree interval intersections conservatively combine surfaces acrossfootprint; exact triangle proof required before selecting conflicting07route.','Source silhouettes/current ordered rendering do not authorize changes to sourcecanopy or flight elevation.']};(O/'proposal.json').write_text(json.dumps(report,indent=2)+'\n');print([(r['sequence'],r['height_minmax'],len(r['potential_tree_collision_intervals']),r['minimum_sampled_noncanopy_clearance'])for r in rows]);assert sum(p.stat().st_size for p in O.iterdir())<2*1024**2
