"""Translate exact approved lower-bark inputs into the guarded texture workflow."""
from pathlib import Path
import hashlib,json,shutil,sys
R=Path.cwd();sys.path[:0]=[str(R/'level-editor/refinement')]
from prepare_texture_packet import prepare
O=R/'level-editor/work/croisement02-refinement';S=O/'restart6-tree07-bark-close-v1';D=O/'restart6-tree07-bark-fill-v1';P=D/'packet';W=O/'root-stem-round-2/assets/croisement02-tree-07';read=lambda p:json.loads(p.read_text());h=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
assert not D.exists();approval=O/'restart3-review-batches/pending-v12-v13-hub-v1/user-approval.json';assert h(approval)=='7824a374725f41de669cb93d8a1bd78659523a893b29fa541a195e5125de63f2';batch=O/'restart3-review-batches/batch-v12/user-approval.json';decision=next(m for c in read(batch)['cards'] for m in c['members'] if m['asset_id']=='croisement02-tree-07');card=read(S/'ready-candidate-v1.json');assert decision['scope']=='texture-input' and decision['model_sha256']==card['candidate_model_sha256'];assert decision['review_revision']==card['review_revision'];assert h(W/'model.blend')==card['candidate_model_sha256']
for p,r in card['files'].items():assert h(Path(p))==r['sha256']
P.mkdir(parents=True);(P/'views').mkdir();meta=read(S/'views.json');meta['source_blend']=str(W/'model.blend')
for v in meta['views']:
 i=v['index'];shutil.copyfile(S/f'views/view-{i}-input.png',P/f'views/view-{i}-textured.png');shutil.copyfile(S/f'views/view-{i}-known.png',P/f'views/view-{i}-known.png');shutil.copyfile(S/f'actual/view-{i}-solid.png',P/f'views/view-{i}-solid.png');v['ownership_sha256']=h(P/f'views/view-{i}-known.png')
(P/'views.json').write_text(json.dumps(meta,indent=2)+'\n');shutil.copyfile(S/'input.png',P/'textured.png');shutil.copyfile(S/'solid.png',P/'solid.png');proof=read(S/'input-review.json');evidence={str(p):dict(path=str(p),sha256=h(p)) for p in [approval,batch,S/'ready-candidate-v1.json',S/'root-review.json',S/'input-review.json',*[p for p in P.rglob('*')if p.is_file()]]};identity=dict(asset_id='croisement02-tree-07',model_sha256=card['candidate_model_sha256'],evidence={k:v['sha256']for k,v in evidence.items()});rev=hashlib.sha256(json.dumps(identity,sort_keys=True,separators=(',',':')).encode()).hexdigest();item=dict(id=identity['asset_id'],workspace=str(W),status='ready-for-user',stored_material_validation='PASS',solid=str(P/'solid.png'),textured=str(P/'textured.png'),revision=dict(sha256=rev,model_sha256=identity['model_sha256'],evidence=evidence),approval_provenance=dict(original_geometry=proof['geometry_decision'],new_input=decision,input_approval_receipt=str(approval),scope='Exact original geometry8bcb plus explicitly approved new lower058/062 input; no generated texture approval implied.'))
(D/'review-manifest.json').write_text(json.dumps(dict(version=1,items=[item]),indent=2)+'\n');(D/'decisions.json').write_text(json.dumps(dict(version=1,decisions=[dict(asset_id=item['id'],scope='geometry',decision='approved',exact_user_text=proof['geometry_decision']['exact_user_text'],revision_sha256=rev,original_geometry_decision=proof['geometry_decision'],new_input_decision=decision,translation='Exact already-approved geometry; new input separately explicitly approved All11approved')]),indent=2)+'\n');print(prepare(D/'review-manifest.json',item['id'],D/'experiment',D/'decisions.json'));refs=read(S/'auxiliary-references.json');assert refs['input_sha256']==h(D/'experiment/input.png') and refs['lighting_sha256']==h(D/'experiment/solid.png');(D/'experiment/auxiliary-references.json').write_text(json.dumps(refs,indent=2)+'\n')
