"""Freeze independently reviewed hay geometry and its exact source restoration."""
from pathlib import Path
import json,sys
sys.path.insert(0,str(Path(__file__).resolve().parents[3]/'level-editor/refinement/blender'))
from catalog import OUT
from evidence_io import sha,write_json
base=OUT/'restart3-hay';w=base/'native-rgb-v1/assets/croisement02-south-field-haystack';h=sha(w/'model.blend');assert h=='0ae1a8f011764923c2859fffb61c8371ffa4c820d5a2d655ccdaeb21b6069d54'
a=base/'texel-audit-final-v1';j=base/'ground-v8';audit=json.loads((w/'inspection/saved-model-audit.json').read_text());native=json.loads((a/'texel-audit.json').read_text());verification=json.loads((a/'final-verification.json').read_text());guard=json.loads((w/'inspection/native-rgb-restoration.json').read_text())
assert audit['status']=='PASS' and audit['model_sha256']==h and native['model_sha256']==h and verification['model_sha256']==h
assert verification['neutral_native_samples']==0 and verification['other_first_hit_RGB_exact'] and len(verification['changed_native_samples'])==18
assert guard['geometry_uv_unchanged'] and guard['other_texels_unchanged'] and guard['outside_appearance_unchanged']
notes=['One grounded, closed mound in the two existing canonical halves. Rounded depth and individual straw thickness are inferred from the original artwork; the native mask and source image are unchanged.','The ragged outer skirt follows native mask 124. Reverse cut-edge detail and hidden depth are inferred; gray rear surfaces still need texture fill after user geometry approval.','Ground contact was independently reviewed on exact parent 9e56309d against approved ground 16c638be, with verified context transforms. Final geometry and UVs are unchanged; minimum height is 0.000291.','18 neutral source texels were restored to exact original RGB. All other texture pixels stayed unchanged. Native coverage retains 55 fringe center-ray gaps, 36 rendered edge misses and 10 rendered extra pixels; detailed sampling evidence is linked.']
root=dict(model_sha256=h,status='PASS scoped geometry ready for user',reviewer='root independent',exact_review_text='Root viewed final0ae1a8f0 actual8 and restoration guard: PASS exact source-restored derivative on previously reviewed geometry/contact. Root previously viewed ground-v8 source comparison and contact4: geometry/contact PASS, source shape/nativeskirt improved, no broad excess ground cover.',contact_model_sha256='9e56309dd81644568796e271f3e90419bf60d3ae6216c77b58d9d48b6487d99f',geometry_preservation=str(w/'inspection/native-rgb-restoration.json'),notes=notes)
outputs=[w/'inspection/root-review.json',w/'inspection/visual-review.json',base/'ready-candidate-v1.json']
for p in outputs:
 if p.exists():raise FileExistsError(p)
files=[w/x for x in ['model.blend','workspace.json','source-masks.json','baseline.blend','validation.json','modified/views.json','modified/solid.png','modified/textured.png','inspection/refinement.json','inspection/native-rgb-restoration.json','inspection/saved-model-audit.json','inspection/source-coverage/report.json','inspection/actual-materials/sheet.png','inspection/actual-materials/evidence.json','native-source/packet.json','native-source/complete-source.png','reference/source.png']]+[a/'texel-audit.json',a/'final-verification.json',a/'source-comparison.png',j/'evidence.json',j/'source-comparison.png',j/'contact-sheet.png',base/'native-depth-context.png',base/'candidate-v8/assets/croisement02-south-field-haystack/model.blend',base/'candidate-v8/assets/croisement02-south-field-haystack/inspection/refinement.json',base/'clip-clean-v3/topology.json',base/'clip-clean-v3/model.blend',base/'clip-clean-v2/topology.json',base/'clip-topology-research-v2/assets/croisement02-south-field-haystack/topology.json']
for p in files:
 if not p.is_file():raise FileNotFoundError(p)
write_json(outputs[0],root);write_json(outputs[1],dict(model_sha256=h,sheet_sha256=sha(w/'inspection/actual-materials/sheet.png'),ready_for_geometry_review=True,notes=notes));files+=outputs[:2]
receipt=dict(asset_id=w.name,worker=str(w),model_sha256=h,part_ids=['building-140','building-141'],native_mask_indices=[124],status='root reviewed; pending user geometry approval',texture_status='New geometry unknown rear fill pending user approval; no API call',source_trace=str(a/'source-comparison.png'),source_comparison=str(j/'source-comparison.png'),contact_sheet=str(j/'contact-sheet.png'),solid_sheet=str(w/'modified/solid.png'),notes=notes,native_statistics={k:native[k] for k in ['target_pixels','geometry_hits','exact_source_matches','source_3x3_matches']},files={str(p):sha(p) for p in files});write_json(outputs[2],receipt);print(outputs[2])
