import {readFile,writeFile,mkdir} from 'node:fs/promises';
import {resolve,join} from 'node:path';
import {createHash} from 'node:crypto';
import {parseStoredMap} from '../../shared/src/stored-level.ts';
import {verifyStaticStateReplacements} from '../../shared/src/state-delivery.ts';
const sha=b=>createHash('sha256').update(b).digest('hex'),base=resolve('level-editor/work/croisement02-refinement'),library=resolve('level-editor/library'),stage=join(base,'restart2-state/remaining-seven-package-v2'),candidate=join(base,'restart2-textures/post-batch15-static-candidate-v6'),out=resolve(process.argv[3]||'');
const read=async p=>JSON.parse(await readFile(p,'utf8')),mapPath=join(library,'scenes/croisement02.rhlos-map.json'),mapBytes=await readFile(mapPath),map=JSON.parse(mapBytes),manifestBytes=await readFile(join(stage,'manifest.json')),manifest=JSON.parse(manifestBytes);
if(!/^[a-f0-9]{64}$/.test(process.argv[2]??'')||!process.argv[3])throw Error('Expected explicit installed map hash and fresh output directory');
if(sha(mapBytes)!==process.argv[2])throw Error('Installed static selection changed');
const sources=map.assetSources.concat(map.sceneAssets),descriptors=new Map();for(const source of sources){const bytes=await readFile(join(library,source.descriptor));if(sha(bytes)!==source.descriptor_sha256)throw Error('Descriptor changed '+source.id);descriptors.set(source.id,JSON.parse(bytes));}
const document=parseStoredMap(map,descriptors),checks=[],verified=new Map();for(const entry of manifest.entries){const bytes=await readFile(join(stage,'library',entry.contract.path));if(sha(bytes)!==entry.contract.sha256)throw Error('Contract changed '+entry.id);const contract=JSON.parse(bytes);verifyStaticStateReplacements(contract,document);for(const family of contract.families)for(const rows of Object.values(family.static_replacements??{}))for(const part of rows){if(verified.has(part.asset_id))continue;const source=sources.find(a=>a.id===part.asset_id);if(!source)throw Error('Missing replacement asset');const bytes=await readFile(join(library,source.model));if(sha(bytes)!==part.model_sha256)throw Error('Actual installed replacement model changed');verified.set(part.asset_id,{path:source.model,sha256:sha(bytes)});}checks.push({id:entry.id,status:'PASS'});}
const indexPath=join(library,'mission-states/index.json'),indexBytes=await readFile(indexPath),index=JSON.parse(indexBytes);await mkdir(out,{recursive:false});const report={status:'PASS',scope:'Installed static dependency gate only. Seven private mission entries are not published by this check.',map_sha256:sha(mapBytes),manifest_sha256:sha(manifestBytes),prior_static_promotion_sha256:sha(await readFile(join(candidate,'promotion.json'))),note:'Any later metadata change requires its own reviewed supplement; this proof checks actual current replacement semantics only.',mission_index_sha256:sha(indexBytes),mission_index_entries:(index.entries??index).length,checks,verified_replacement_resources:[...verified.values()]};await writeFile(join(out,'verification.json'),JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify(report));
