"""Freeze the reviewed sign-neighbor shrub geometry without selecting it canonically."""
import sys,json,shutil
from pathlib import Path
ROOT=Path(__file__).resolve().parents[3]
sys.path[:0]=[str(Path(__file__).parent),str(ROOT/'level-editor/refinement/blender')]
from catalog import OUT
from evidence_io import sha,write_json
from build_review_gallery import build

def main():
 base=OUT/'restart2-fence/shrub57-sign-bend-v9';digest=sha(base/'model.blend');assert digest=='d8281fe58969556b760a81cc7feb4b5bf8b9b2e149355e53d8620e313a9fa253'
 source=json.loads((base/'report.json').read_text());ground=json.loads((base/'ground-parity-proof/report.json').read_text());contact=json.loads((base/'native-physical-comparison/report.json').read_text());joint=json.loads((base/'joint-proof/report.json').read_text())
 assert all(r['model_sha256']==digest for r in [source,ground,contact,joint]);assert source['native_first_hit_rgba_max_error']==0;assert all(r['newly_inside_by_parity']==0 and r['newly_negative_beyond_halfunit']==0 for r in ground['results']);assert contact['phase26_noncontact_residual_resolved'] and contact['total_residual_samples']==87
 notes=['Approve only this exact shrub57 depth correction. The original approved model remains selected until a separate decision; contextual signs, rocks and bank are not being approved by this card.','Native first-hitRGBA is unchanged. One final paired leaf fragment moved0.734217 source-ray unit; opaque ground support remainsZ0.5 and depth/width is1.323.','Four possible planted-post native pixel centers remain:1–4 body pixels per pose,87samples across32poses. Complete post and bank meet there with no usable exterior depth interval within0.001ray unit. No leaves were buried or clipped to erase this contact.','Native painted sign shadows remain partly obscured in true3D context. Exact shadow/native scene composition and full mission integration are separate; body visibility metrics exclude painted shadows.','Sparse native foliage follows the rock margins; rear and off-map volume are inferred. Original approved source contour report retains9missing/12extra pixels. Exact savedRGBA preservation is not100% source coverage.','Bank/rock comparison uses59,333 matched opaque samples, with zero new inside or negative-beyond0.5unit samples. Preexisting overlaps remain; this is not an exhaustive surface-intersection certificate.']
 files=[base/p for p in ['report.json','root-visual-review.json','actual-eight.png','native-after.png','joint-proof/report.json','joint-proof/joint-eight.png','ground-parity-proof/report.json','native-physical-comparison/report.json','native-physical-comparison/all32-native-physical.png','native-physical-comparison/all32-foot-closeups.png','native-context/report.json','native-context/source-context.png','painted-shadow-appearance.json']]
 ready=base/'root-geometry-readiness.json';assert not ready.exists();write_json(ready,dict(status='PASS scoped shrub57 geometry with explicit planted-contact/native-shadow limits',reviewer='root coordinator',ready_for_geometry_review=True,model_sha256=digest,files={str(p):sha(p) for p in files},notes=notes,root_instruction='Root viewed all32-native-physical sheet v9: sign body coherent through fullturn, foliage/body correction passes scoped geometry with tiny plantedfoot residual and native-vs-physical shadow caveat explicitly retained. Exactd8281fe5 geometry readiness PASS once receipt bound. Prepare frozen geometry card shrub57 + nativecontext + actual8 + all32comparison. Do not label shadow/source coverage fully solved.',user_approval=None))
 dest=OUT/'restart2-fence/shrub57-geometry-review-v1';dest.mkdir(exist_ok=False);shutil.copy2(base/'model.blend',dest/'model.blend');assert sha(dest/'model.blend')==digest
 validation=dest/'validation.json';write_json(validation,dict(status='PASS scoped geometry checks',model_sha256=digest,source_projection_and_native_rgba=source,ground_contact=ground,body_contact=contact,root_readiness_sha256=sha(ready),approval_scope='Exact shrub57 geometry only; native painted shadows, full source contour parity, mission integration and canonical selection remain separate.'))
 item=dict(id='croisement02-shrub-57',name='West rock foliage57 — sign clearance refinement',status='ready-for-user',technical_eligible=True,model=str(dest/'model.blend'),solid=str(base/'actual-eight.png'),solid_label='Saved shrub geometry: actual materials, original game camera first',textured=str(base/'joint-proof/joint-eight.png'),textured_label='Physical sign neighborhood: actual materials, original game camera first',context=str(base/'native-context/source-context.png'),source_comparison=str(base/'native-physical-comparison/all32-native-physical.png'),source_comparison_label='All32 sign poses: native artwork left, physical context right; planted-contact and shadow caveats retained',source_trace=str(base/'native-physical-comparison/all32-foot-closeups.png'),source_trace_label='All32 planted-post close-ups: native left, physical right',validation=str(validation),review=str(ready),ownership=str(base/'native-context/report.json'),stored_material_audit=str(base/'report.json'),notes=notes)
 manifest=dest/'review-candidates.json';write_json(manifest,dict(map='Croisement02 shrub57 geometry',items=[item],scope='Single exact shrub geometry decision; no blanket state or appearance approval. All eight-view sheets have the original native camera at top-left.'))
 build(manifest,dest/'gallery',pending_only=True)
 html=dest/'gallery/index.html';document=html.read_text();document=document.replace('Solid geometry</option>','Saved shrub geometry</option>').replace('Original textures + gray</option>','Physical neighborhood</option>');html.write_text(document)
 write_json(dest/'freeze.json',dict(status='Frozen geometry-only card awaiting user decision',model_sha256=digest,manifest_sha256=sha(manifest),root_readiness_sha256=sha(ready),gallery_evidence_sha256=sha(dest/'gallery/evidence.json'),gallery_html_sha256=sha(html),canonical_selection_changed=False,user_approval=None))
 print(dest/'gallery/index.html')
if __name__=='__main__':main()
