// Read-only geometric receiver audit of the exact delivered state resources.
import {readFile,writeFile,mkdir} from 'node:fs/promises';
import {resolve,join} from 'node:path';
import {createHash} from 'node:crypto';
import * as THREE from '../../app/node_modules/three/build/three.module.js';
import {GLTFLoader} from '../../app/node_modules/three/examples/jsm/loaders/GLTFLoader.js';
import {MeshoptDecoder} from '../../app/node_modules/meshoptimizer/meshopt_decoder.mjs';
const root=resolve('.'),base=join(root,'level-editor/work/croisement02-refinement/restart2-state'),manifestPath=join(base,'installed-seven-http-snapshot-v9/contacts/manifest.json'),out=resolve(process.argv[2]);
const sha=b=>createHash('sha256').update(b).digest('hex'),bytes=await readFile(manifestPath),manifest=JSON.parse(bytes),loader=new GLTFLoader();await MeshoptDecoder.ready;loader.setMeshoptDecoder(MeshoptDecoder);
async function load(pin){const path=pin.url.slice('/@fs'.length),b=await readFile(path);if(sha(b)!==pin.sha256)throw Error('Resource hash changed '+path);const len=b.readUInt32LE(12),doc=JSON.parse(b.subarray(20,20+len).toString()),bin=b.subarray(28+len);if(doc.skins?.length||doc.animations?.length)throw Error('Dynamic geometry unsupported');for(const m of doc.meshes||[])for(const p of m.primitives){delete p.material;if(p.targets)throw Error('Morph geometry unsupported')}delete doc.materials;delete doc.images;delete doc.textures;delete doc.samplers;doc.extensionsUsed=doc.extensionsUsed?.filter(x=>['EXT_meshopt_compression','KHR_mesh_quantization'].includes(x));doc.extensionsRequired=doc.extensionsRequired?.filter(x=>['EXT_meshopt_compression','KHR_mesh_quantization'].includes(x));const j=Buffer.from(JSON.stringify(doc)),pad=(4-j.length%4)%4,jb=Buffer.concat([j,Buffer.alloc(pad,32)]),dst=Buffer.alloc(28+jb.length+bin.length);dst.writeUInt32LE(0x46546c67,0);dst.writeUInt32LE(2,4);dst.writeUInt32LE(dst.length,8);dst.writeUInt32LE(jb.length,12);dst.writeUInt32LE(0x4e4f534a,16);jb.copy(dst,20);dst.writeUInt32LE(bin.length,20+jb.length);dst.writeUInt32LE(0x004e4942,24+jb.length);bin.copy(dst,28+jb.length);const gltf=await loader.parseAsync(dst.buffer.slice(dst.byteOffset,dst.byteOffset+dst.byteLength),'');return gltf.scene;}
function meshes(scene){scene.updateMatrixWorld(true);const rows=[];scene.traverse(o=>{if(!o.isMesh)return;const a=o.geometry.getAttribute('position'),ix=o.geometry.index,verts=[];for(let i=0;i<a.count;i++){const v=new THREE.Vector3().fromBufferAttribute(a,i).applyMatrix4(o.matrixWorld);verts.push([v.x,v.y,v.z])}const faces=[];for(let i=0;i<(ix?ix.count:a.count);i+=3)faces.push([0,1,2].map(j=>ix?ix.getX(i+j):i+j));rows.push({name:o.name,vertices:verts,faces})});return rows;}
const cell=32,grid=new Map(),triangles=[];
function key(x,z){return Math.floor(x/cell)+','+Math.floor(z/cell)}
function addTriangle(v,owner){const [a,b,c]=v,det=(b[2]-c[2])*(a[0]-c[0])+(c[0]-b[0])*(a[2]-c[2]);if(Math.abs(det)<1e-9)return;const t={v,det,owner},id=triangles.length;triangles.push(t);for(let x=Math.floor(Math.min(...v.map(p=>p[0]))/cell);x<=Math.floor(Math.max(...v.map(p=>p[0]))/cell);x++)for(let z=Math.floor(Math.min(...v.map(p=>p[2]))/cell);z<=Math.floor(Math.max(...v.map(p=>p[2]))/cell);z++){const k=x+','+z;if(!grid.has(k))grid.set(k,[]);grid.get(k).push(id)}}
function receiver(p){let best=null;for(const id of grid.get(key(p[0],p[2]))||[]){const t=triangles[id],[a,b,c]=t.v,u=((b[2]-c[2])*(p[0]-c[0])+(c[0]-b[0])*(p[2]-c[2]))/t.det,v=((c[2]-a[2])*(p[0]-c[0])+(a[0]-c[0])*(p[2]-c[2]))/t.det;if(u< -1e-7||v< -1e-7||u+v>1+1e-7)continue;const y=u*a[1]+v*b[1]+(1-u-v)*c[1];if(!best||y>best.y)best={y,owner:t.owner,triangle:id}}return best}
const receiverPins=[];for(const r of manifest.receivers){const scene=await load(r.model);scene.position.add(new THREE.Vector3(...r.position));scene.rotation.x+=r.rotation[0];const ms=meshes(scene);for(const m of ms)for(const f of m.faces)addTriangle(f.map(i=>m.vertices[i]),r.id+'/'+m.name);receiverPins.push({id:r.id,model_sha256:r.model.sha256,position:r.position,rotation:r.rotation,meshes:ms.map(m=>({name:m.name,vertices:m.vertices.length,triangles:m.faces.length}))})}
function logSupport(ms){const pairs=[];for(let i=0;i<ms.length;i++)for(let j=0;j<i;j++){const a=ms[i],b=ms[j];let best=Infinity,witness=null;for(const [one,two] of [[a,b],[b,a]]){const samples=[...one.vertices,...one.faces.map(f=>[0,1,2].map(axis=>f.reduce((n,k)=>n+one.vertices[k][axis],0)/3))];for(const face of two.faces){const t=new THREE.Triangle(...face.map(k=>new THREE.Vector3(...two.vertices[k]))),q=new THREE.Vector3();for(const point of samples){const p=new THREE.Vector3(...point);t.closestPointToPoint(p,q);const distance=p.distanceTo(q);if(distance<best){best=distance;witness={from:one.name,to:two.name,point,nearest:q.toArray()}}}}}pairs.push({a:a.name,b:b.name,sampled_surface_distance:best,witness})}return pairs}
const records=[];for(const rec of manifest.records)for(const endpoint of ['initial','applied']){const bindings=rec.family.physical[endpoint];if(!Array.isArray(bindings)){records.push({id:rec.id,endpoint,absent:true});continue}for(const binding of bindings){const scene=await load(rec.models[binding.model]);scene.position.add(new THREE.Vector3(...binding.position));const ms=meshes(scene),rows=[];for(const m of ms){let minimum=Infinity,maximum=-Infinity,misses=0,below=0,touch=0,worst=null;const contacts=[];const samples=[...m.vertices,...m.faces.map(f=>[0,1,2].map(axis=>f.reduce((n,i)=>n+m.vertices[i][axis],0)/3))];for(const p of samples){const hit=receiver(p);if(!hit){misses++;continue}const delta=p[1]-hit.y;if(delta<minimum){minimum=delta;worst={point:p,receiver:hit}}maximum=Math.max(maximum,delta);if(delta< -.05)below++;if(Math.abs(delta)<=.05){touch++;if(contacts.length<12)contacts.push({point:p,receiver:hit})}}rows.push({name:m.name,vertices:m.vertices.length,triangles:m.faces.length,sampled_vertices_and_centroids:samples.length,min_clearance:minimum,max_clearance:maximum,receiver_misses:misses,below_tolerance_samples:below,touch_samples:touch,contacts,worst})}records.push({id:rec.id,endpoint,binding_id:binding.id,model_sha256:binding.model_sha256,position:binding.position,meshes:rows,log_pair_surface_distances:binding.id.includes("log-trap")?logSupport(ms):undefined});console.log(binding.id,rows.length,'min',Math.min(...rows.map(r=>r.min_clearance)),'touches',rows.reduce((n,r)=>n+r.touch_samples,0))}}
await mkdir(out,{recursive:false});await writeFile(join(out,'report.json'),JSON.stringify({status:'MEASURED_FOR_ROLE_AWARE_REVIEW',manifest_sha256:sha(bytes),receivers:receiverPins,receiver_triangles:triangles.length,records,method:'Exact delivered GLB positions/indices decoded by production Three GLTFLoader and MeshoptDecoder, material loading omitted only. Exact scene graph and manifest transforms. Vertical receiver rays at every vertex and triangle centroid; no fallback ground when receiver absent.',limitations:['Vertex/centroid sampling does not prove continuous nonpenetration or stable balance.','Rigid elevated body parts need connected supporting wheel/log contacts, not contact at every vertex.','Alpha-cutout surfaces require source/material ownership classification before treating their full polygon extent as a solid.']},null,2));
