import {readFile,writeFile,mkdir} from 'node:fs/promises';import {resolve,join} from 'node:path';import {createHash} from 'node:crypto';
import {parseStoredMap} from '../../shared/src/stored-level.ts';import {verifyStaticStateReplacements} from '../../shared/src/state-delivery.ts';
const revision=process.argv[2]??'v2';if(!/^v[0-9]+$/.test(revision))throw Error('Invalid private candidate revision');
const base=resolve('level-editor/work/croisement02-refinement'),candidate=join(base,'restart2-textures/post-batch15-static-candidate-'+revision),stage=join(base,'restart2-state/remaining-seven-package-v2'),out=join(base,'restart2-state/post-batch15-static-compatibility-'+revision),read=async p=>JSON.parse(await readFile(p,'utf8')),sha=b=>createHash('sha256').update(b).digest('hex');
const mapPath=join(candidate,'croisement02.rhlos-map.json'),raw=await read(mapPath),manifest=await read(join(stage,'manifest.json')),descriptors=new Map(),resources=[];
for(const a of [...raw.assetSources,...raw.sceneAssets]){for(const key of ['model','descriptor']){const bytes=await readFile(join(candidate,'map-assets',a[key]));if(sha(bytes)!==a[key+'_sha256'])throw Error('Static resource mismatch '+a.id);resources.push({path:a[key],sha256:sha(bytes)})}descriptors.set(a.id,await read(join(candidate,'map-assets',a.descriptor)))}
const document=parseStoredMap(raw,descriptors),checks=[];
for(const e of manifest.entries){const c=await read(join(stage,'library',e.contract.path));verifyStaticStateReplacements(c,document);checks.push({id:e.id,status:'PASS',replacement_parts:c.families.flatMap(f=>Object.values(f.static_replacements??{}).flat().map(p=>p.object_id))});}
const baseline=await read(join(base,'restart2-textures/batch10-private-level3d-exact-v2/croisement02.rhlos-map.json'));if(JSON.stringify(baseline.placements)!==JSON.stringify(raw.placements))throw Error('Placement delta');
const report={status:'PASS',scope:'Read-only source/model/descriptor hash and semantic placement compatibility for seven existing contracts. Candidate still requires changed-asset visual approvals and publication; this does not extend97assertions to unreviewed pixels.',map_sha256:sha(await readFile(mapPath)),contract_manifest_sha256:sha(await readFile(join(stage,'manifest.json'))),tested_map_sha256:manifest.static_map_sha256,checks,source_resources:resources,placements_exact:true,delta_assets:raw.assetSources.concat(raw.sceneAssets).filter(a=>baseline.assetSources.concat(baseline.sceneAssets).find(x=>x.id===a.id)?.model_sha256!==a.model_sha256).map(a=>({id:a.id,model_sha256:a.model_sha256}))};await mkdir(out,{recursive:true});await writeFile(join(out,'verification.json'),JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify({checks:checks.length,map:report.map_sha256,deltas:report.delta_assets}));
