"""Freeze approved-direction cap appearance reuse for the next grouped texture review."""
import sys,json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[3];sys.path[:0]=[str(Path(__file__).parent),str(ROOT/'level-editor/refinement/blender')]
from catalog import OUT
from evidence_io import sha,write_json
from build_review_gallery import build

def main():
 d=OUT/'restart7-fence-residual/wall101-appearance-reuse-v1';dest=OUT/'restart7-fence-residual/frozen-wall101-appearance-card-v1';dest.mkdir(exist_ok=False);model=d/'model.blend';digest=sha(model);assert digest=='3204d38f8b94a3ef78662b4633b7219b131ff8d61450d0fa8b8c562be64b0475';guard=json.loads((d/'receipt.json').read_text());assert guard['geometry_and_all_uv_exact']and guard['other_six_receivers_exact']and all(r['exact_unchanged']for r in guard['native_front_samples'])
 full=d/'full-asset-review-v1';paths=[d/'source-comparison.png',d/'actual-eight.png',full/'actual-eight.png',full/'solid-eight.png',d/'receipt.json',d/'native-render-preservation.json',d/'self-review.json',full/'receipt.json'];review=dest/'root-review.json';write_json(review,dict(status='PASS scoped restored same-face rear cap appearance',reviewer='root coordinator',model_sha256=digest,approved_geometry_sha256=guard['approved_geometry_sha256'],review_method='Personally viewed native source comparison, close actual eight, complete actual eight and solid eight.',findings='Continuous muted rear stone, native front retained; inherited blurry rear material disclosed.',scope='Appearance only on the exact approved cap geometry; no API needed, no inherited user appearance decision.',user_approved=False,api_calls=0,files={str(p):sha(p)for p in paths}))
 item=dict(id='croisement02-east-stone-wall-and-gate-cap101-appearance',name='East stone wall — restored cap appearance',status='ready-for-user',technical_eligible=True,model=str(model),solid=str(full/'solid-eight.png'),textured=str(full/'actual-eight.png'),context=str(d/'source-comparison.png'),source_comparison=str(d/'source-comparison.png'),source_comparison_label='Native source / approved cap geometry with gray / restored same-face appearance',validation=str(d/'receipt.json'),ownership=str(d/'native-render-preservation.json'),review=str(review),notes='Fills newly gray rear-cap faces by reusing their exact previously approved materials and UVs. No AI generation. Approved geometry, all UVs, six other receivers and unselected faces remain unchanged. All five recovered native center samples remain exact. Three antialiased boundary samples mix differently where gray becomes retained stone; source RGB and alpha are preserved. Inherited blurry rear texture and front projection streaking remain disclosed.',approval_scope='Saved appearance of exact3204d38f worker on already approved05151df8 geometry; no geometry reapproval or publication.',animation_reviews=[dict(id='cap-appearance-detail',name='Cap appearance contact detail',description='Same saved worker from eight close views; native camera first.',solid=str(OUT/'restart7-fence-residual/wall101-cap-v2/solid-eight.png'),textured=str(d/'actual-eight.png'),context=str(d/'source-comparison.png'))])
 manifest=dest/'review-candidates.json';write_json(manifest,dict(map='Croisement02 cap appearance',review_kind='texture',scope='V15 grouped appearance pool. Geometry approved separately in batch14; no new geometry decision requested.',items=[item]));build(manifest,dest/'gallery');write_json(dest/'freeze-receipt.json',dict(status='Frozen V15 appearance pool card',model_sha256=digest,approved_geometry_sha256=guard['approved_geometry_sha256'],user_approved=False,api_calls=0,files={str(p):sha(p)for p in [manifest,review,dest/'gallery/evidence.json',d/'receipt.json']}));print(dest/'gallery/index.html')
if __name__=='__main__':main()
