"""Separate measured screen evidence from an inferred flight-depth proposal."""
import hashlib,json,math
from pathlib import Path
import numpy as np
ROOT=Path(__file__).resolve().parents[3];W=ROOT/'level-editor/work/croisement02-refinement';B=W/'restart14-butterflies';OUT=B/'butterfly07-depth-provenance-v1'
sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()

def main():
    assert not OUT.exists()
    baseline=W/'baseline/Croisement02.rhp.json';planp=B/'all7-context-plan-v1/plan.json';pathp=B/'footprint-path-proposal-v2/proposal.json';auditp=B/'all7-footprint-audit-v2/report.json'
    source=json.loads(baseline.read_text())['animations'][14];plan=next(s for s in json.loads(planp.read_text())['sequences']if s['index']==14);proposal=json.loads(pathp.read_text());path=next(r for r in proposal['rows']if r['sequence']==14);audit=json.loads(auditp.read_text());records=[r for r in audit['phase_records']if r['sequence']==14];assert sha(auditp)==proposal['footprint_sha256']
    sin=math.sin(math.radians(35));cos=math.cos(math.radians(35));world=np.array(path['world_zup_knots']);screen=np.array(path['source_screen_anchors']);measured=np.array([r['alpha_centroid_display']for r in plan['path']]);assert np.array_equal(screen,measured)
    for frame in plan['path']:assert sha(Path(frame['source']))==frame['sha256']
    assert np.max(abs(np.c_[world[:,0],-sin*world[:,1]-cos*world[:,2]]-screen))<1e-10
    lower=np.array([max(10,r['maximum_noncanopy_receiver_height']+r['z_extent']+8)for r in records]);rows=[]
    for i,r in enumerate(records):
        rows.append({'phase':i,'screen_alpha_centroid':screen[i].tolist(),'current_inferred_height':float(world[i,2]),'sampled_noncanopy_max_height':r['maximum_noncanopy_receiver_height'],'conservative_extent':r['z_extent'],'old_inferred_lower_bound':float(lower[i]),'height_delta_interval_preserving_old_noncanopy_bound_and_proposed6unit_trust_region':[float(max(-6,lower[i]-world[i,2])),6.],'world_y_change_per_height_unit':-cos/sin})
    tests=[]
    for dz in [-6,-3,0,3,6]:
        candidate=world+np.array([0,-cos/sin*dz,dz]);error=np.max(abs(np.c_[candidate[:,0],-sin*candidate[:,1]-cos*candidate[:,2]]-screen));tests.append({'uniform_height_delta_diagnostic_only':dz,'max_screen_error':float(error)});assert error<1e-10
    report={'status':'PROVENANCE_ONLY_NO_PATH_MUTATION','recipe_sha256':sha(Path(__file__)),'inputs':{str(p.relative_to(ROOT)):sha(p)for p in [baseline,planp,pathp,auditp]},'native_serialized':source,'directly_observed':['Sprite origin98,246 and elevation100 metadata; preserve in native state/composition.','99 own RGBA frames, per-frame image placement, delay1 yielding2ticks perphase.','Projected alpha centroid computed exactly from positive-alpha pixel centers; not an observed anatomical body root.'],'inferred':['Physical flight depth/height at every phase.','Body-center correction, body orientation and hidden wing depth.','Continuous interpolation between stepped native frames.','Current solver minimum10/maximum400Z, conservative8Zextent,8unit receiver clearance,3Z/2tick slope limit and curvature penalty.'],'current_height_minmax':[float(world[:,2].min()),float(world[:,2].max())],'current_solver':'Minimize mean(h)+0.3*sum(cyclicSecondDifference(h)^2), subject to h>=max(10,maxNoncanopyReceiver+8conservativeExtent+8clearance), h<=400, abs(cyclicFirstDifference)<=3. Crown visibility not an objective. All these geometric regularizers are inferred choices.','ray_freedom':{'equation':'For screen(sx,sy), worldZup=(sx,-(sy+cos35*z)/sin35,z). Any deltaZ gives deltaWorld=(0,-cot35*deltaZ,deltaZ) and exact same projection.','initial_search_proposal':'Symmetric±6worldZ around current inferred curve; both shallower and deeper, smooth low-frequency corrections. This is a bounded investigation budget, not a native measured range or guaranteed feasible corridor.','constraints':'Keep exact99screen anchors and native timing, retain sourcemetadata100 and composition separately. Validate complete anatomy, all scene receivers and cyclic swept motion; do not maximize visibility or demand above-canopy placement.','old_bounds':'Per-phase negative range below keeps prior sampled noncanopy+8clearance bound only. That old bound itself is inferred and conservative; it is not a native requirement or continuous-body proof.','native_elevation_note':'Serialized100 is a real sprite-position/order parameter, not an exported99phase moving-body depth track. Do not erase it or claim it was absent. Geometry depth may be independently reconstructed while preserving native sprite placement and composition.'},'projection_invariance_checks':tests,'rows':rows,'limits':['No candidate depth path selected, installed or rendered.','No physically feasible interval proven by this provenance audit; trust region needs actual geometry and swept contact evaluation.','Existing anatomy omits source pixels and has uncertain body/filament registration.']}
    OUT.mkdir();(OUT/'report.json').write_text(json.dumps(report,indent=2)+'\n');print('heights',report['current_height_minmax']);print([(r['phase'],r['height_delta_interval_preserving_old_noncanopy_bound_and_proposed6unit_trust_region'])for r in rows if r['phase']in[18,19,20,21,22,91,92,93]])

if __name__=='__main__':main()
