"""Bind independently reviewed kindling geometry, native appearance and context."""
from pathlib import Path
import json,sys
sys.path.insert(0,str(Path(__file__).resolve().parents[3]/"level-editor/refinement/blender"))
from catalog import OUT
from evidence_io import sha,write_json
base=OUT/'restart3-kindling';w=base/'native-rgb-v1/assets/croisement02-southwest-kindling-bundle';h=sha(w/'model.blend');assert h=='87b1183d7ae1db8600901889e4b533089a6e19e61e8239e3ca38f6b6e5f0c85c';j=base/'neighbour-v3/f61971e3-3462cda5-b650c6da-665b1710';native=base/'native-rgb-review-v1/source-comparison.png';audit=base/'texel-audit-final-v1/texel-audit.json'
notes=['New geometry: 28 grounded closed sticks, taller staggered cut ends and one binding follow original source artwork. Hidden arrangement and depth are inferred.','Ground and shrub79/stump/log-pile contact reviewed on exact parent f61971e3; final geometry and UVs unchanged. Context world matrices restored from independently reopened source files.','58 neutral native samples restored to exact source RGB; all other texels preserved. Final first-hit audit:1060/1116 native centers hit,924 exact RGB,990 source3x3 matches,zero neutral sampled centers.56 perimeter geometry gaps and70 non-neutral subpixel sampling differences remain disclosed.','Rear and hidden surfaces remain gray; prior generated texture does not apply to this new geometry. Fresh texture fill follows user geometry approval.']
root=dict(model_sha256=h,status='PASS scoped geometry ready for user',reviewer='root independent',exact_review_text='Root final87b1183d actual8/native and preservedf619contact4 reviewed: bundle sourcefit/ground/shrubjoin coherent, exact58restore confirmedreport. Scoped geometry readiness PASS, texture unknown rear and perimeter/subpixel stats disclosed.',contact_model_sha256='f61971e3506de38e31899911e275352f70fa67dadb45fd6d696aeee1529a8fb0',geometry_preservation=str(w/'inspection/native-rgb-restoration.json'),notes=notes)
for p in [w/'inspection/root-review.json',w/'inspection/visual-review.json',base/'ready-candidate-v1.json']:
 if p.exists():raise FileExistsError(p)
write_json(w/'inspection/root-review.json',root);write_json(w/'inspection/visual-review.json',dict(model_sha256=h,sheet_sha256=sha(w/'inspection/actual-materials/sheet.png'),ready_for_geometry_review=True,notes=notes))
files=[w/x for x in ['model.blend','workspace.json','source-masks.json','validation.json','modified/views.json','modified/solid.png','modified/textured.png','inspection/root-review.json','inspection/visual-review.json','inspection/refinement.json','inspection/native-rgb-restoration.json','inspection/saved-model-audit.json','inspection/source-coverage/report.json','inspection/actual-materials/sheet.png','inspection/actual-materials/evidence.json']]+[native,audit,j/'evidence.json',j/'source-comparison.png',j/'contact-sheet.png',base/'candidate-v2/assets/croisement02-southwest-kindling-bundle/inspection/refinement.json',base/'candidate-v2/assets/croisement02-southwest-kindling-bundle/model.blend']
receipt=dict(asset_id=w.name,worker=str(w),model_sha256=h,part_ids=['building-129'],native_mask_indices=[104],status='root reviewed; pending user geometry approval',texture_status='New geometry unknown rear fill pending user approval; no new API call',source_trace=str(native),source_comparison=str(j/'source-comparison.png'),contact_sheet=str(j/'contact-sheet.png'),notes=notes,files={str(p):sha(p) for p in files});write_json(base/'ready-candidate-v1.json',receipt);print(base/'ready-candidate-v1.json')
