"""Freeze paired initial-rig appearance after independent saved-model review."""
import sys,json,hashlib
from pathlib import Path
HERE=Path(__file__).resolve().parent
sys.path[:0]=[str(HERE),str(HERE.parents[1]/'refinement/blender')]
from catalog import OUT
from evidence_io import sha,write_json
ROOT=OUT/'restart5-initial-nets'
def main(version):
 items=[];target=ROOT/'paired-texture-bound-members-v1.json';assert not target.exists()
 for key,number in [('00','01'),('01','03')]:
  exp=ROOT/f'texture-fill-v1/profile-{key}/experiment';w=exp/version;h=sha(w/'worker.blend');guard=json.loads((w/'preservation.json').read_text());root=json.loads((w/'root-review.json').read_text());contact=json.loads((w/'contact-v1/evidence.json').read_text());assert guard['model_sha256']==root['model_sha256']==contact['model_sha256']==h;assert root['status']=='PASS scoped initial rig appearance ready for user';assert guard['native_sample_count']==guard['native_exact_RGBA'];assert guard['geometry_uv_unchanged']and guard['original_native_image_packed_bytes_and_RGBA_exact'];assert contact['wood_crossing_count']==0;original=ROOT/f'candidate-v5/profile-{key}';ambiguous=49 if key=='00' else 117
  notes=[f'Appearance only on the Batch9-approved initial net {number} geometry. Thin hemp cord, upper fastening loop and unknown camouflage reverse/edges filled with own approved post-trigger material references.',f'All {guard["native_sample_count"]} classified native sample colors and source UVs remain exact. The {ambiguous} uncertain high source pixels remain native-only and unassigned.','Ground silhouette, cord routing and physical attachment remain unchanged; actual supporting tree context and native-first eight-view materials independently reviewed.','Generated raw and protected outputs remain archived. Source alpha restored exactly; unknown-color correction avoids treating neutral antialias fringe as native color evidence. Triggered hanging bags remain distinct state assets.']
  continuation=json.loads((w/'continuation.json').read_text());assert continuation['model_sha256']==h;assert json.loads((w/'occupied-closure.json').read_text())['model_sha256']==h;assert json.loads((w/'reopened-generated-guard.json').read_text())['model_sha256']==h;assert all(r['remaining_over_bound']==0 and r['original_protected_and_padding_exact'] for r in continuation['objects']);notes.append('Previously unseen backs and ground-facing surfaces use bounded same-object continuation from this rig’s generated RGB. Exact physical atlas occupancy limits edits; native pixels and padding remain untouched. Maximum rope donor distance is below 1.64 world units; ground underside material uses this rig’s existing generated native-view top pattern with same-object ray witnesses; remaining edges use bounded generated atlas donors.');write_json(w/'disclosures.json',dict(model_sha256=h,notes=notes));images=[('Saved filled rig, original game camera first',w/'actual/textured.png'),('Actual wood attachments and ground contact',w/'contact-v1/contact-sheet.png'),('Native artwork and final scene context',w/'contact-v1/source-comparison.png'),('Source-protected fill input',exp/'input.png'),('Original unchanged solid geometry',exp/'solid.png'),('Original camera followed by exposed underside views',w/'underside-v2/sheet.png')]
  g=exp/'generation-short-no-mask-with-lighting-openrouter-with-auxiliary';bake=exp/('bake-v3-identity' if key=='00' else 'bake-v2-identity');paths=[w/'worker.blend',w/'preservation.json',w/'continuation.json',w/'occupied-closure.json',w/'underside-v2/evidence.json',w/'reopened-generated-guard.json',w/'root-review.json',w/'disclosures.json',w/'report.json',w/'contact-v1/evidence.json',w/'contact-v1/geometry-clearance.json',w/'contact-v1/wood-support-native.png',exp/'approval.json',exp/'preparation.json',exp/'views.json',exp/'mask.png',exp/'generation-review-v2.json',exp/'auxiliary-references.json',exp/'reference-rope.png',exp/'reference-camouflage.png',g/'generation.json',g/'generated-raw.png',g/'generated-preserved.png',g/'generated-native-alpha-preserved.png',bake/'reopened-preservation.json',bake/'validation.json',bake/'identity-reconciliation.json',original/'attachment-audit.json',original/'root-review.json',original/'model.blend',ROOT/'paired-bound-members-v1.json',OUT/'restart3-review-batches/batch-v9/user-approval.json']+[p for _,p in images]+list(w.glob('*.npz'));assert all(p.is_file()for p in paths);evidence={str(p):sha(p)for p in paths};display=[dict(label=l,file=str(p),sha256=sha(p))for l,p in images];asset='croisement02-initial-net-'+number;revision=hashlib.sha256(json.dumps(dict(asset_id=asset,scope='texture',model_sha256=h,evidence=evidence,displayed_images=display,notes=notes),sort_keys=True,separators=(',',':')).encode()).hexdigest();items.append(dict(asset_id=asset,name='Initial net '+number+' filled rigging',model_sha256=h,review_revision=revision,decision='pending',scope='texture',evidence=evidence,displayed_images=display,notes=notes,worker=str(w),model=str(w/'worker.blend'),approved_geometry_sha256=sha(original/'model.blend')))
 write_json(target,dict(status='Independent saved appearance review passed; pending exact user texture decisions',items=items,cards=[dict(card_id='croisement02-initial-net-rigging-texture-pair',title='Initial net rigging textures (01 / 03)',asset_ids=[i['asset_id']for i in items])],canonical_mutation=False));print(target)
if __name__=='__main__':main(sys.argv[1])
