"""Measure actual saved native views without equating source retention with parity."""
from pathlib import Path
import json,sys,hashlib
import numpy as np
from PIL import Image,ImageDraw
ROOT=Path(__file__).resolve().parents[3];version=sys.argv[1] if len(sys.argv)>1 else 'rig-full-v1';OUT=ROOT/'level-editor/work/croisement02-refinement/restart14-butterflies'/version
p=json.loads((OUT/'fit.json').read_text());rows=[];sheet=Image.new('RGB',(3168,1188),'#252525');d=ImageDraw.Draw(sheet)
for row in p['poses']:
 phase=row['phase'];src=np.array(Image.open(row['source']['source']).convert('RGBA'));render=np.array(Image.open(OUT/'motion'/f'phase-{phase:02d}-view-0.png').convert('RGBA'));center=np.array(row['source_center'])+np.array(row['parameters'][5:7]);ys,xs=np.nonzero(src[:,:,3]);pixel=np.column_stack((xs+.5,ys+.5));loc=np.floor((pixel-center)*8+96).astype(int);inside=(loc[:,0]>=0)&(loc[:,0]<192)&(loc[:,1]>=0)&(loc[:,1]<192);samples=np.zeros((len(xs),4),dtype=np.uint8);samples[inside]=render[loc[inside,1],loc[inside,0]];hit=samples[:,3]>127;color=np.abs(samples[hit,:3].astype(int)-src[ys[hit],xs[hit],:3].astype(int));rows.append({'phase':phase,'source_positive_centers':len(xs),'native_render_covered':int(hit.sum()),'native_render_missing':int((~hit).sum()),'covered_rgb_mae':float(color.mean()) if color.size else None,'covered_rgb_exact':int(np.all(color==0,axis=1).sum()),'render_sha256':hashlib.sha256((OUT/'motion'/f'phase-{phase:02d}-view-0.png').read_bytes()).hexdigest()})
 x=phase%11*288;y=phase//11*132;d.text((x+4,y+3),f'{phase:02d} source / native / rear (same scale)',fill='white');im=Image.fromarray(src);im=im.resize((im.width*4,im.height*4),Image.Resampling.NEAREST);sheet.paste(im,(x+round(48-center[0]*4),y+24+round(48-center[1]*4)),im)
 for col,view in [(1,0),(2,4)]:im=Image.open(OUT/'motion'/f'phase-{phase:02d}-view-{view}.png').convert('RGBA').resize((96,96));sheet.paste(im,(x+col*96,y+24),im)
sheet.save(OUT/'all99-source-native-rear.png');report={'method':'Native orthographic192x192, scale24; sample at original source positive pixel centers after model anchor offset. Source retained PNG alone is not rendered parity.','frames':rows,'source_centers':sum(r['source_positive_centers'] for r in rows),'covered':sum(r['native_render_covered'] for r in rows),'missing':sum(r['native_render_missing'] for r in rows),'covered_rgb_exact':sum(r['covered_rgb_exact'] for r in rows),'covered_rgb_mae_mean':float(np.mean([r['covered_rgb_mae'] for r in rows]))};(OUT/'native-render-errors.json').write_text(json.dumps(report,indent=2)+'\n');print({k:v for k,v in report.items() if k not in ('frames','method')})
