"""Freeze paired initial-net geometry decisions after exact independent review."""
import json,hashlib,sys
from pathlib import Path
HERE=Path(__file__).resolve().parent
sys.path[:0]=[str(HERE),str(HERE.parents[1]/'refinement/blender')]
from catalog import OUT
from evidence_io import sha,write_json
ROOT=OUT/'restart5-initial-nets'
def main():
 out=ROOT/'paired-bound-members-v1.json';assert not out.exists();items=[]
 for key,number in [('00','01'),('01','03')]:
  w=ROOT/f'candidate-v5/profile-{key}';h=sha(w/'model.blend');report=json.loads((w/'report.json').read_text());root=json.loads((w/'root-review.json').read_text());guard=json.loads((w/'saved-native-guard.json').read_text());contact=json.loads((w/'contact-v1/evidence.json').read_text());review=json.loads((w/'final-review-evidence.json').read_text());attachment=json.loads((w/'attachment-audit.json').read_text())
  assert all(r['model_sha256']==h for r in [report,root,guard,contact,review,attachment]);assert root['status']=='PASS scoped initial geometry ready for user';assert guard['target']==guard['hits']==guard['exact_native_RGBA'];assert contact['wood_crossing_count']==0 and attachment['physically_connected'] and attachment['endpoint_inside_by_majority'];assert contact['source_world_matrices_verified']
  notes=[f"Initial net {number}: shallow ground camouflage and lifting cord for {report['source']['profile']} action0/direction0. This is distinct from the already reviewed triggered empty/occupied bags.",f"All {guard['target']} classified source sample centers meet physical geometry and exact native RGBA. The {guard['ambiguous_native_only']} sparse high pixels retain uncertain native-only status; no floating solid or tree ownership is invented.","Camouflage thickness, hidden cord route and upper fastening loop are inferred. The loop wraps unchanged actual supporting wood; exact endpoint parity and intersecting joint surfaces establish cord/loop attachment. Closed mesh and ground contact checks passed.","The cord clears neighboring wood. Existing tree context appearance belongs to its previously approved models. Gray inferred line, loop and reverse surfaces still require texture fill after this geometry approval; no API has been called."]
  write_json(w/'self-review.json',dict(model_sha256=h,status='Self-viewed final actual8/solid8/native and contact8',notes=notes));write_json(w/'disclosures.json',dict(model_sha256=h,notes=notes))
  images=[('Original source and final native geometry',w/'source-comparison.png'),('Final actual materials, eight views',w/'actual-sheet.png'),('Final solid geometry, eight views',w/'solid-sheet.png'),('Actual tree support and ground contact, eight views',w/'contact-v1/contact-sheet.png'),('Native neighborhood comparison',w/'contact-v1/source-comparison.png')]
  files=[w/p for p in ['model.blend','report.json','root-review.json','self-review.json','disclosures.json','saved-native-guard.json','attachment-audit.json','final-review-evidence.json','observed-source.png','native.png','contact-v1/evidence.json','contact-v1/geometry-clearance.json','contact-v1/wood-support-native.png']]+[p for _,p in images]+[Path(report['source']['source']),Path(report['source']['source']).parent/'native-profile.json',ROOT/'source/plan.json',ROOT/f'source/profile-{key}-roles.png',ROOT/f'source/profile-{key}-ground-mask.png',ROOT/f'source/profile-{key}-rope-mask.png',ROOT/f'source/profile-{key}-uncertain-mask.png',ROOT/'source/support-survey.json',ROOT/'source/context-selection-final.json',OUT/'restart2-state/net-initial-action-audit-v1/report.json']
  assert all(p.is_file()for p in files);evidence={str(p):sha(p)for p in files};display=[dict(label=label,file=str(p),sha256=sha(p))for label,p in images];asset='croisement02-initial-net-'+number;revision=hashlib.sha256(json.dumps(dict(asset_id=asset,model_sha256=h,evidence=evidence,displayed_images=display,notes=notes),sort_keys=True,separators=(',',':')).encode()).hexdigest();items.append(dict(asset_id=asset,name='Initial net '+number+' ground rigging',model_sha256=h,review_revision=revision,decision='pending',scope='initial h-rig geometry only; triggered e/i bags and future unknown-surface fill excluded',evidence=evidence,displayed_images=display,notes=notes,worker=str(w),canonical_profile=dict(bank='Trapcr02',profile=report['source']['profile'],action=0,direction=0,frame=0,native_anchor=report['source']['anchor'],native_offset=report['source']['offset'],resolved_ground_z=0)))
 write_json(out,dict(status='Independently reviewed paired initial geometry; pending two exact user decisions',items=items,cards=[dict(card_id='croisement02-initial-net-rigging-pair',title='Initial ground nets and lifting lines (01 / 03)',asset_ids=[i['asset_id']for i in items])],canonical_mutation=False));print(out)
if __name__=='__main__':main()
