"""Freeze independently reviewed saved bark appearance and its exact guards."""
from pathlib import Path
import json,hashlib
O=Path.cwd()/'level-editor/work/croisement02-refinement';B=O/'restart8-toe-bark-fill-v1';read=lambda p:json.loads(p.read_text());h=lambda p:hashlib.sha256(p.read_bytes()).hexdigest();items=[];cards=[]
for n,expected in [(19,'f715f5364938bc98eeb27d428a96f9cf9608bb22bfd3984f0ca9075cf8a1c734'),(25,'0c92f9de1f5f340d59b012865c2eb5d9fdc65827508824d47ef135d8adacce15')]:
 D=B/f'tree-{n}-fill-v1/unseen-complete-v3';I=B/f'tree-{n}-input-v1';E=D.parent/'experiment';model=D/'worker.blend';assert h(model)==expected;g=read(D/'saved-native-guard.json');assert g['lower_native_exact']==(614 if n==19 else 2011);assert not g['lower_native_failures'];assert all(g[k]for k in ('crown_exact','upper_triangles_exact','retained_packed_images_exact'));assert all(x['outside_bound']==0 for x in read(D/'continuation.json')['objects'])
 notes=['Appearance only on exact Batch15 approved geometry and Batch16 approved texture inputs.','Native source colors, grazing overlays, all original UVs, crown and physical geometry remain unchanged.','Unknown reverse bark completed; underside uses coarse/streaked same-object generated continuation, explicitly inferred.','Protected native ivy and bark stretch in oblique views remains inherited, not newly fixed.','Exact lower native RGBA samples retained: '+str(g['lower_native_exact'])+'. Rendered antialias differences at source/generated transitions are measured separately; no screenshot-wide RGB identity claim.','Tree19 single accepted dark source-edge residual and Tree25 partial-AA corner remain separate geometry limitations.','No final user appearance approval or live integration yet.']
 paths=[D/f for f in ['close/textured.png','full/textured.png','underside/sheet.png','contact-review-v1/after/contact4.png','contact-review-v1/after/source-comparison.png']]
 root=dict(status='PASS scoped saved bark appearance for grouped V17 review',authority='Root personally viewed all ten final sheets across both trees',model_sha256=expected,reviewed_files={str(p):h(p)for p in paths},findings=['Crowns and native fronts retained.','Reverse bark coherent, no neutral underside gaps.','Coarse same-object underside and protected oblique ivy stretches must remain explicitly disclosed.'],user_appearance_approval='pending')
 (D/'root-review.json').write_text(json.dumps(root,indent=2)+'\n');files=[p for p in D.rglob('*')if p.is_file()]+[I/'input-review.json',I/'ready-candidate-v1.json',I/'auxiliary-references.json',I/'input.png',I/'actual.png',I/'solid.png',B/'source-authority.json',B/'approved-geometry.json',O/'restart3-review-batches/batch-v15/user-approval.json',O/'restart3-review-batches/batch-v16/user-approval.json',E/'generation-review.json',E/'approval.json',D.parent/'shader-restored-v1/preservation.json']
 for ref in read(I/'auxiliary-references.json')['references']:files.append(Path(ref['file']))
 evidence={str(p):h(p)for p in files};asset=f'croisement02-tree-{n}';identity=dict(asset_id=asset,model_sha256=expected,evidence=evidence);rev=hashlib.sha256(json.dumps(identity,sort_keys=True,separators=(',',':')).encode()).hexdigest();labels=['Completed bark — native camera first','Unchanged full crown with completed bark','Native-first and underside supplement','Root contacts on Z0 guide','Native source / overlay / actual wood'];images=[dict(label=label,file=str(p),sha256=h(p))for label,p in zip(labels,paths)]+[dict(label='Approved pre-fill appearance',file=str(I/'actual.png'),sha256=h(I/'actual.png'))]
 item=dict(asset_id=asset,name=f'Tree {n} — completed inferred bark',model_sha256=expected,review_revision=rev,decision='pending',scope='texture',evidence=evidence,displayed_images=images,notes=notes);items.append(item);card_id=f'{asset}-bark-appearance-v3';cards.append(dict(card_id=card_id,title=item['name'],asset_ids=[asset]));ready=dict(version=1,id=card_id,name=item['name'],asset_ids=[asset],scope='texture',status='Root PASS; awaiting grouped user appearance approval',candidate_model=str(model),candidate_model_sha256=expected,review_revision=rev,root_review=root,presentation=dict(main_actual=str(paths[0]),full_actual=str(paths[1]),underside=str(paths[2]),contact=str(paths[3]),source_comparison=str(paths[4]),before_actual=str(I/'actual.png'),main_solid=str(I/'solid.png')),disclosures=notes,input_approval=dict(path=str(O/'restart3-review-batches/batch-v16/user-approval.json'),sha256=h(O/'restart3-review-batches/batch-v16/user-approval.json'),scope='texture-input'),files={p:dict(path=p,sha256=s)for p,s in evidence.items()});(D/'ready-candidate-v1.json').write_text(json.dumps(ready,indent=2)+'\n')
F=B/'appearance-ready-v17';F.mkdir(exist_ok=False);(F/'bound-members.json').write_text(json.dumps(dict(items=items,cards=cards),indent=2)+'\n');print(F/'bound-members.json',h(F/'bound-members.json'))
