"""Pin private scene authorities and exact per-mission metadata differences."""
from pathlib import Path
import json,hashlib
r=Path('level-editor/work/croisement02-refinement');lib=Path('level-editor/library');source=r/'restart2-state/trap-mission-package-v1';out=r/'restart2-state/trap-scene-integration-plan-v1';out.mkdir(exist_ok=True)
read=lambda p:json.loads(p.read_text());sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest();package=read(source/'manifest.json');original=read(lib/'game-data/Data/Levels/Emb05_FoB_MP.rhm.json');level=read(lib/'game-data/Data/Levels/Croisement02.rhp.json');rows=[]
for row in package['entries']:
 mission=read(lib/'game-data/Data/Levels'/(row['mission']+'.rhm.json'));contract=read(source/'library'/row['entry']['contract']['path']);base=read(lib/'mission-states/croisement02/contracts'/(row['family']+'.json'));parts=[]
 for new_id,old_id in zip(contract['families'][0]['element_ids'],base['families'][0]['element_ids']):
  ni,oi=int(new_id[6:]),int(old_id[6:]);a,b=original['targets'][oi],mission['targets'][ni];diff={k:{'baseline':a.get(k),'mission':b.get(k)}for k in sorted(set(a)|set(b))if a.get(k)!=b.get(k)};parts.append({'baseline_target':oi,'mission_target':ni,'differences':diff})
 np=contract['native']['background_states'][0]['source']['index'];op=base['native']['background_states'][0]['source']['index'];a,b=original['mission_patches'][op],mission['mission_patches'][np];patchdiff={k:{'baseline':a.get(k),'mission':b.get(k)}for k in sorted(set(a)|set(b))if a.get(k)!=b.get(k)}
 rows.append({'mission':row['mission'],'family':row['family'],'targets':parts,'receiver_patch_indices':{'baseline':op,'mission':np},'receiver_patch_differences':patchdiff,'receiver_ordering_requires_reconciliation':a['element_fx']['display_polyline']!=b['element_fx']['display_polyline'],'duplicate_profile_targets_not_activated':row['duplicate_profile_targets_not_activated']})
plan_path=r/'restart2-textures/post-batch8-approved-integration-plan-v1/manifest.json';plan=read(plan_path);assembly_path=r/'restart2-textures/batch-v3-coherent-scene-v1/assembly.json';assembly=read(assembly_path);scene_path=lib/'scenes/croisement02.rhlos-map.json';scene=read(scene_path)
metadata=[]
for family,index in [('log-trap',5),('rock-trap',6)]:
 p=level['patches'][index];metadata.append({'family':family,'zero_based_level_patch_index':index,'source':p,'interpretation':'Invisible mask/sight/pathfinder metadata; retain separately from visible target solids and decorative receiver patch. Do not count as geometry.'})
result={'status':'PRIVATE FINITE INTEGRATION PLAN; NO EXECUTION','package':{'manifest':str(source/'manifest.json'),'sha256':sha(source/'manifest.json'),'verification':str(source/'verification.json'),'verification_sha256':sha(source/'verification.json')},'active_private_scene':{'assembly':str(assembly_path),'assembly_sha256':sha(assembly_path),'declared_blend_sha256':assembly['model_sha256'],'selection':assembly['selection'],'selection_sha256':assembly['selection_sha256'],'scope':'Existing frozen126 Blender scene only; no new Level3D placement IDs inferred.'},'approved_delta_authority':{'path':str(plan_path),'sha256':sha(plan_path),'approved_ground':plan['approved_ground'],'approved_geometry_with_retained_appearance':plan['approved_geometry_with_retained_appearance'],'pending_excluded_from_import':plan['pending_excluded_from_import']},'canonical_projection_scene':{'path':str(scene_path),'sha256':sha(scene_path),'scene_metadata':scene.get('sceneMetadata'),'scope':'Current projection WIP, not the refined replacement scene.'},'mission_metadata_differences':rows,'native_metadata_to_preserve':metadata,'integration_steps':[
'Root selects and assembles approved static deltas over pinned private scene; pending v9 initial wagon/nets and cumulative ground output remain excluded until their exact decisions.',
'Export final scene with stable placed object IDs, asset model hashes, part/group transforms and retained invisible native patch metadata. No fake static replacement IDs are inserted now.',
'Bind approved physical endpoint common origins at exact existing positions. Per-mission source frame anchors/order stay exact; Emb09 first log part has y529, not530. Assess that one-pixel source difference separately from reused physical endpoint hypothesis.',
'Keep native mask/sight metadata application separate from decorative receiver background restoration; repeated runtime patch indices are never substituted for zero-based source indices.',
'Preserve each mission polyline/action point/script identity and duplicate rock trigger IDs. The controlled preview selects one family activation; it does not execute mission scripts or activate both duplicate targets together.',
'Root schedules one actual Editor check of11 staged catalog entries using unchanged installed artwork/GLBs, then exact scene integration checks for endpoint visibility, receiver reset, mission switch and failed placement/resource guards.',
'Only after those scoped checks use a coordinated mission-state index slot; current installed3entry catalog remains unchanged during this preparation.'
],'holds':['S03 tie-specific acceptance remains outside this package.','Tac21 log receiver has a nonempty source display polyline; initial/transition FX ordering must be reconciled before publication. Final stamping alone does not establish transient ordering.','No latest refined Level3D fence placement exists; cleared-fence exact static replacement waits that publication authority.','No physical transition identity, actor reconstruction or new gameplay runtime is implied.']}
(out/'report.json').write_text(json.dumps(result,indent=2)+'\n');print('Pinned11 contract metadata comparisons and current scene/delta authorities')
