"""Bind explicit approved initial geometry to unchanged texture input derivatives."""
import sys,json,hashlib
from pathlib import Path
from PIL import Image
HERE=Path(__file__).resolve().parent
sys.path[:0]=[str(HERE),str(HERE.parents[1]/'refinement'),str(HERE.parents[1]/'refinement/blender')]
from catalog import OUT
from evidence_io import sha,write_json
from prepare_texture_packet import prepare
ROOT=OUT/'restart5-initial-nets'
def main(key):
 worker=ROOT/f'texture-inputs-v1/profile-{key}';asset='croisement02-initial-net-'+('01'if key=='00'else'03');d=json.loads((worker/'derivation.json').read_text());approval=OUT/'restart3-review-batches/batch-v9/user-approval.json';user=json.loads(approval.read_text());frozen=approval.parent/'evidence.json';assert sha(frozen)==user['evidence_sha256'];a=next(dict(m,scope=c['scope'])for c in user['decisions']for m in c['members']if m['asset_id']==asset);assert a['scope']=='geometry'and a['model_sha256']==d['source_model_sha256'];assert d['geometry_uv_materials_unchanged'];assert all(v['protected_rgba_exact']for v in d['views']);assert sha(worker/'model.blend')==d['prepared_model_sha256'];assert sha(Path(d['source_model']))==a['model_sha256']
 target=ROOT/f'texture-fill-v1/profile-{key}';target.mkdir(parents=True,exist_ok=False);workspace=target/'parent-workspace';workspace.mkdir();(workspace/'model.blend').symlink_to(d['source_model']);selection=dict(parent_geometry_revision=a['review_revision'],preparation_model=str(worker/'model.blend'));sp=target/'preparation-selection.json';write_json(sp,selection)
 review=dict(status='Self-viewed complete native-first textured and solid eight-view packet',ready_for_texture_preparation=True,model_sha256=a['model_sha256'],derivation_sha256=sha(worker/'derivation.json'),scope='Existing saved material first-hit ownership protects native image alpha; geometry and UV unchanged.');write_json(target/'input-review.json',review)
 evidence={str(p):dict(path=str(p),sha256=sha(p))for p in [approval,frozen,sp,target/'input-review.json',*[p for p in worker.rglob('*')if p.is_file()]]};bridge=dict(kind='approved-state-endpoint-preparation-derivative',source_user_decision=a,exact_user_text=user['answer'],source_user_receipt_sha256=sha(approval),derivation=d,preparation_review=review,scope='Exact user-approved initial h geometry. Derived masks protect saved native alpha/UV material. New rendered inputs are not represented as a separate user decision. No post-trigger bag geometry reused.');bp=target/'approval-bridge.json';write_json(bp,bridge);evidence[str(bp)]=dict(path=str(bp),sha256=sha(bp));identity=dict(asset_id=asset,model_sha256=a['model_sha256'],evidence={k:v['sha256']for k,v in evidence.items()});rev=hashlib.sha256(json.dumps(identity,sort_keys=True,separators=(',',':')).encode()).hexdigest();item=dict(id=asset,workspace=str(workspace),status='ready-for-user',stored_material_validation='PASS',solid=str(worker/'modified/solid.png'),textured=str(worker/'modified/textured.png'),revision=dict(sha256=rev,model_sha256=a['model_sha256'],evidence=evidence),approval_provenance=bridge,preparation_selection=str(sp),**selection);write_json(target/'review-manifest.json',dict(version=1,items=[item]));write_json(target/'decisions.json',dict(version=1,decisions=[dict(asset_id=asset,scope='geometry',decision='approved',exact_user_text=user['answer'],revision_sha256=rev,original_gallery_decision=a,translation='Explicit batch9 approval with unchanged preparation; appearance remains pending')]));prepare(target/'review-manifest.json',asset,target/'experiment',target/'decisions.json')
 exp=target/'experiment';refs=[];authority=OUT/'restart2-textures/batch-v6-texture-approval-v1/state-endpoint-decisions.json';dec=next(x for x in json.loads(authority.read_text())['decisions']if x['asset_id']=='croisement02-net-piege01-empty-final-0');pic=Path(dec['candidate'])/'actual/textured.png';assert sha(pic)==dec['evidence_sha256'][str(pic)];im=Image.open(pic).convert('RGBA')
 for name,box,role in [('rope',[233,22,250,71],'Approved own post-trigger net cord: weathered thin brown hemp fiber color only. Do not copy bag shape or layout.'),('camouflage',[215,170,260,255],'Approved own post-trigger camouflage net fabric: subdued ochre brown leaf litter and woven fiber texture only. Do not copy hanging bag volume.')]:
  p=exp/f'reference-{name}.png';im.crop(box).save(p);refs.append(dict(source='material',file=str(p),sha256=sha(p),asset_id=dec['asset_id'],role=role,parent_image=str(pic),parent_sha256=sha(pic),crop=box,approval_receipt=str(authority),approval_receipt_sha256=sha(authority)))
 write_json(exp/'auxiliary-references.json',dict(input_sha256=sha(exp/'input.png'),lighting_sha256=sha(exp/'solid.png'),references=refs));print(exp)
if __name__=='__main__':main(sys.argv[1])
