import {readFile,writeFile,mkdir,mkdtemp} from 'node:fs/promises';
import {resolve,join} from 'node:path';
import {tmpdir} from 'node:os';
import {spawn} from 'node:child_process';
import {createHash} from 'node:crypto';
import {chromeEndpoint,socketOpen} from '../../app/tests/cdp.mjs';
import {stateProofCommand} from './restart6_verify_remaining_state_editor.mjs';
const root=resolve('.'),base=join(root,'level-editor/work/croisement02-refinement/restart7-source-patch-delivery'),out=join(base,'ui-proof-v3');await mkdir(out,{recursive:true});
const {createServer}=await import('../../app/node_modules/vite/dist/node/index.js');
const {default:solid}=await import('../../app/node_modules/@solidjs/vite-plugin/dist/esm/index.mjs');
const source=await readFile(join(root,'level-editor/blender/croisement02/restart7_native_patch_ui_fixture.tsx'));
const html='<html><body><div id="view" style="position:absolute;inset:0 300px 0 0"></div><div id="panel" style="position:absolute;right:0;width:280px"></div><script type="module" src="/@fs/'+join(root,'level-editor/blender/croisement02/restart7_native_patch_ui_fixture.tsx')+'"></script></body></html>';
const server=await createServer({configFile:false,root:join(root,'level-editor/app'),cacheDir:join(out,'vite-cache'),plugins:[solid({solid:{delegateEvents:false}}),{name:'private-native-patch-proof',configureServer(s){s.middlewares.use((req,res,next)=>{if(req.url!=='/native-patch-proof')return next();res.setHeader('Content-Type','text/html');res.end(html)})}}],resolve:{alias:[{find:/^three\/addons\//,replacement:join(root,'level-editor/app/node_modules/three/examples/jsm/')+'/'},{find:/^three$/,replacement:join(root,'level-editor/app/node_modules/three/build/three.module.js')},{find:/^three\//,replacement:join(root,'level-editor/app/node_modules/three/')+'/' }]},optimizeDeps:{entries:[]},server:{host:'127.0.0.1',port:0,watch:null,hmr:false,fs:{allow:[root]}}});await server.listen();await server.watcher.close();
const profile=await mkdtemp(join(tmpdir(),'c02-native-patch-ui-')),chrome=spawn('/usr/lib/chromium/chromium',['--headless','--no-sandbox','--disable-dev-shm-usage','--disable-background-networking','--enable-unsafe-swiftshader','--use-angle=swiftshader','--remote-debugging-port=0','--user-data-dir='+profile,'about:blank'],{stdio:['ignore','ignore','pipe']});const exited=new Promise(r=>chrome.on('close',r));let ws,id=0;const checks=[];
try{
 const endpoint=new URL(await chromeEndpoint(chrome)),pages=await(await fetch('http://'+endpoint.host+'/json/list')).json();ws=new WebSocket(pages.find(p=>p.type==='page').webSocketDebuggerUrl);await socketOpen(ws);const cmd=(m,p)=>stateProofCommand(ws,()=>++id,m,p),run=async expression=>{const r=await cmd('Runtime.evaluate',{expression:expression.includes('await ')?'(async()=>('+expression+'))()':expression,awaitPromise:true,returnByValue:true});if(r.exceptionDetails)throw Error(JSON.stringify(r.exceptionDetails));return r.result?.value},pause=ms=>new Promise(r=>setTimeout(r,ms)),until=async e=>{for(let i=0;i<500;i++){if(await run(e))return;await pause(50)}throw Error('Timeout '+e)},check=async(name,e)=>{const pass=await run(e);checks.push({name,pass});if(!pass)throw Error(name)},shot=async name=>{const r=await cmd('Page.captureScreenshot',{format:'png'});await writeFile(join(out,name+'.png'),Buffer.from(r.data,'base64'))};
 await cmd('Runtime.enable');await cmd('Page.enable');await cmd('Emulation.setDeviceMetricsOverride',{width:1260,height:820,deviceScaleFactor:1,mobile:false});const loaded = new Promise((resolve, reject) => {
   const timeout = setTimeout(() => { ws.removeEventListener('message', listener); reject(Error('Initial page load timed out')); }, 30000);
   const listener = event => { if (JSON.parse(event.data).method === 'Page.loadEventFired') { clearTimeout(timeout); ws.removeEventListener('message', listener); resolve(); } };
   ws.addEventListener('message', listener);
 });
 await cmd('Page.navigate',{url:'http://127.0.0.1:'+server.httpServer.address().port+'/native-patch-proof'});await loaded;await until('window.patchProof?.ready && patchProof.snapshot().ready');
 const manifest=JSON.parse(await readFile(join(base,'contracts-v1/manifest.json'))),reference=JSON.parse(await readFile(join(base,'contracts-v1/independent-reference.json'))),seen=new Set();let n=0;
 for(const row of manifest.records){if(seen.has(row.profile))continue;seen.add(row.profile);const ref=reference.records.find(r=>r.id===row.id),expected=t=>ref.cases.find(c=>c.tick===t).rgba_sha256;
 await run(`patchProof.mission(${JSON.stringify(row.mission)})`);await until(`!![...document.querySelectorAll('[aria-label="State preview asset"] option')].find(o=>o.value===${JSON.stringify('source-'+row.id)})`);await run(`patchProof.select(${JSON.stringify('source-'+row.id)})`);await until(`patchProof.snapshot().focus===${JSON.stringify(row.id)}`);
 await check(row.id+' initial hash',`(await patchProof.hash())===${JSON.stringify(expected(-1))}`);await check(row.id+' no physical option',`JSON.stringify(patchProof.snapshot().physicalOptions)==='["art"]'`);
 const tick=Math.floor(row.terminal_tick/2);await run(`patchProof.frame(${tick})`);await check(row.id+' seek parity',`(await patchProof.hash())===${JSON.stringify(expected(tick))}`);await shot(n+'-transition');await run(`patchProof.frame(${row.terminal_tick})`);await check(row.id+' applied parity',`(await patchProof.hash())===${JSON.stringify(expected(row.terminal_tick))}`);await shot(n+'-applied');await writeFile(join(out,n+'-applied-crop.png'),Buffer.from(await run(`patchProof.crop(${JSON.stringify(row.id)})`),'base64'));await run("patchProof.click('Reset')");await check(row.id+' reset parity',`(await patchProof.hash())===${JSON.stringify(expected(-1))}`);await run("patchProof.click('Play')");await until('patchProof.snapshot().tick>0');if(await run('patchProof.snapshot().playing'))await run("patchProof.click('Pause')");await check(row.id+' paused','!patchProof.snapshot().playing');n++;
 }
 await run('patchProof.hide()');await check('hidden panel restores physical editor',"patchProof.snapshot().mode==='physical'&&!patchProof.snapshot().playing");await run('patchProof.show()');await run("patchProof.mission('NoMission')");await until('!patchProof.snapshot().ready');await check('mission cleanup','!patchProof.snapshot().focus');await run("patchProof.fault('held');patchProof.mission('Emb05_FoB_MP')");await pause(200);await run("patchProof.mission('NoMission');patchProof.releaseHeld()");await pause(300);await check('stale load cannot reappear','!patchProof.snapshot().ready&&!patchProof.snapshot().focus');
 for(const fault of ['missing','hash']){await run(`patchProof.fault(${JSON.stringify(fault)});patchProof.mission('Emb05_FoB_MP')`);await until('patchProof.snapshot().status.length>0 && !patchProof.snapshot().status.includes("Loading state preview…")');await check(fault+' resource failure atomic','!patchProof.snapshot().ready');await shot('error-'+fault);await run("patchProof.mission('NoMission')")}
 const disposed=await run('patchProof.dispose()');if(!disposed.retired||disposed.canvases)throw Error('Unmount cleanup failed');await writeFile(join(out,'verification.json'),JSON.stringify({status:'PASS',checks,profiles:n,disposed,fixture_sha256:createHash('sha256').update(source).digest('hex'),scope:'Actual production source preview controls and viewport. No physical endpoint completion or publication.'},null,2)+'\n');console.log('PASS '+checks.length+' checks');
}catch(error){await writeFile(join(out,'failure.json'),JSON.stringify({error:String(error),checks},null,2)+'\n');throw error}finally{ws?.close();chrome.kill('SIGTERM');await exited;await server.close()}
