"""Freeze the bounded inferred trap underlay for a later combined appearance review."""
import sys,json
from pathlib import Path
HERE=Path(__file__).resolve().parent
sys.path[:0]=[str(HERE),str(HERE.parents[1]/'refinement/blender')]
from catalog import OUT
from evidence_io import sha,write_json
from build_review_gallery import build
def main():
 base=OUT/'restart2-state';worker=base/'trap-ground-continuation-model-v1';proposal=base/'trap-ground-continuation-v1';context=base/'trap-ground-continuation-context-v2';digest=sha(worker/'model.blend');assert digest=='fe8da24ebb5f696f8df6453baf2a82454737bf4157f1a65ecdf78b2380d8e7ec';validation=json.loads((worker/'validation.json').read_text());assert validation['model_sha256']==digest and validation['changed_pixels']==14
 review={'status':'Root scoped appearance PASS; user pending','model_sha256':digest,'reviewer':'root','scope':'Fourteen inferred underlay pixels only','evidence':{str(p):sha(p)for p in [worker/'validation.json',proposal/'before-after.png',proposal/'sample-authority.png',proposal/'phase-comparison.json',context/'manifest.json',context/'joint-sheet.png',context/'native-art-comparison.png',base/'trap-context-transparency-convergence-v2/pixel-convergence.json']},'finding':'Narrow boundary continuation visually unobtrusive; exact outsideRGBA and geometry preserved.','limits':['Not overall rock source-camera parity; physical foliage/visibility differs from the native source presentation.','No inferred3D transition, new geometry or publication approval.']};write_json(worker/'root-review.json',review)
 item={'id':'croisement02-trap-ground-underlay-continuation','name':'Trap ground — fourteen-pixel boundary continuation','status':'ready-for-user','technical_eligible':True,'user_approval':None,'review_scope':'inferred ground appearance','model':str(worker/'model.blend'),'solid':str(context/'joint-sheet.png'),'solid_label':'Initial/applied rock context; original camera first in each row','textured':str(context/'croisement02-rock-trap-covered-native.png'),'textured_label':'Original game camera with inferred underlay','source_comparison':str(proposal/'before-after.png'),'source_comparison_label':'Exact approved atlas before / fourteen-pixel continuation after','source_comparison_secondary':str(proposal/'sample-authority.png'),'source_comparison_secondary_label':'Same-ground sample authority; cyan edit boundary and magenta sample pixels','projection_errors':str(context/'native-art-comparison.png'),'projection_errors_label':'Original artwork / physical context; not a claim of complete scene parity','validation':str(worker/'validation.json'),'review':str(worker/'root-review.json'),'notes':['Appearance only: exactly fourteen unknown ground pixels continue colors from the nearest accepted same-ground samples. No API synthesis or geometry change.','Every sample lies outside trap and foreign scenery reservations and is verified against the current physical ground receiver. Distances are1–22.36source pixels.','All other atlasRGBA and ground geometry/UV/transform remain exact after reopening. All464native receiver phases retain their original opaque pixels.','Context uses a converged512transparent-surface budget and unchanged approved scenery. This does not approve overall physical foliage ordering, transition motion or publication.']}
 index=worker/'review-candidates.json';write_json(index,{'map':'Croisement02 inferred trap underlay','items':[item],'without_packets':[]});build(index,worker/'gallery');write_json(worker/'ready-candidate-v1.json',{'id':item['id'],'status':'Root scoped appearance PASS; next grouped user batch pending','model_sha256':digest,'review_candidates':str(index),'evidence_sha256':sha(worker/'gallery/evidence.json'),'scope':item['review_scope']})
if __name__=='__main__':main()
