"""Freeze independently reviewed empty net geometry for a combined review batch."""
import sys,json
from pathlib import Path
HERE=Path(__file__).resolve().parent
sys.path[:0]=[str(HERE),str(HERE.parents[1]/'refinement/blender')]
from catalog import OUT
from evidence_io import sha,write_json
from build_review_gallery import build
def main():
 b=OUT/'restart2-state/net-empty01-v11';digest=sha(b/'model.blend');assert digest=='3c80a9ce19306de621d170713663159059493c60a3b5131eb415bcd47a7dedf2';audit=json.loads((b/'reopened-audit.json').read_text());assert audit['model_sha256']==digest;review={'status':'ready-for-user','reviewer':'Codex /root','model_sha256':digest,'scope':'Empty piege01 endpoint geometry only','inspected':['review/actual-eight.png','review/solid-eight.png','joint/sheet.png','native-source-missing.png','self-review.json'],'finding':'Slim collapsed bag plausible; corrected stem and wood underside match source.38fringe misses and14gray source pixels disclosed.','limits':['No texture generation, temporal motion or complete net implementation approval.']};write_json(b/'root-review.json',review)
 item={'id':'croisement02-net-piege01-empty-endpoint','name':'Net trap01 — empty hanging endpoint','status':'ready-for-user','technical_eligible':True,'user_approval':None,'review_scope':'geometry','model':str(b/'model.blend'),'solid':str(b/'review/solid-eight.png'),'textured':str(b/'review/actual-eight.png'),'context':str(b/'joint/sheet.png'),'source_comparison':str(b/'native-source.png'),'source_comparison_label':'Original empty net artwork','projection_errors':str(b/'native-source-missing.png'),'projection_errors_label':'Original /38remaining fringe and isolated edge pixels in magenta','validation':str(b/'reopened-audit.json'),'review':str(b/'root-review.json'),'notes':['Approve this exact empty hanging endpoint geometry only. Original game camera is the top-left view in both sheets.','Closed collapsed cloth volume, counterweight, two hanging cords and upper knot. Current branch attachments verified with zero tested treewood interior overlap.','1,381of1,433native source pixels are textured exactly;14gray source pixels and38fringe/isolated edge misses remain. Unknown rear surfaces are gray and need later appearance completion.','This card does not approve generated texture, lifting motion, actors, other net family endpoints or integrated mission behavior.']};index=b/'review-candidates.json';write_json(index,{'map':'Croisement02 empty net endpoint','items':[item],'without_packets':[]});build(index,b/'gallery');write_json(b/'ready-candidate-v1.json',{'id':item['id'],'status':'Root geometry PASS; pending later grouped user batch','model_sha256':digest,'review_candidates':str(index),'evidence_sha256':sha(b/'gallery/evidence.json'),'scope':'geometry','root_review':review})
if __name__=='__main__':main()
