import {readFile,writeFile,mkdir} from 'node:fs/promises';import {resolve,join} from 'node:path';import {createHash} from 'node:crypto';
import {validateStateDelivery} from '../../shared/src/state-delivery.ts';import {verifyNativePresentationSource} from '../../app/src/native-state-presentation.ts';
const b=resolve('level-editor/work/croisement02-refinement'),lib=resolve('level-editor/library'),out=join(b,'restart2-state/fence-contract-preparation-v2'),read=async p=>JSON.parse(await readFile(p,'utf8')),sha=b=>createHash('sha256').update(b).digest('hex');
const sources=[],records=[],level=await read(join(lib,'game-data/Data/Levels/Croisement02.rhp.json')),evidence=await read(join(b,'state-target-evidence/south-cart/manifest.json')),initial=await read(join(b,'restart2-state/initial-fence-family-origin-v1/manifest.json')),ends=await read(join(b,'restart2-state/remaining-local-origins-v1/manifest.json')),cleared=ends.records.find(r=>r.id==='croisement02-south-field-wattle-fence-cleared-state'),receiver=await read(join(b,'restart2-state/cleared-fence-receiver-export-v2/manifest.json'));
const model=async(id,file,expected,position)=>{const bytes=await readFile(file);if(sha(bytes)!==expected)throw Error('Model revision changed');const path='mission-states/croisement02/resources/'+expected+'.glb';sources.push({path,sha256:expected,source:file,bytes:bytes.length});return{id,role:'objects',model:path,model_sha256:expected,resources:[],...(position?{position}:{})}};
const first=await model('croisement02-intact-field-fence',resolve(initial.model),initial.model_sha256,initial.position),last=await model(cleared.id,join(b,'restart2-state/remaining-local-origins-v1',cleared.glb),cleared.glb_sha256,cleared.position),floor=await model('croisement02-cleared-fence-source-overlay',join(b,'restart2-state/cleared-fence-receiver-export-v2/model.glb'),receiver.glb_sha256);
await mkdir(join(out,'contracts'),{recursive:true});
for(const binding of evidence.background_bindings){const missionName=binding.mission,mission=await read(join(lib,'game-data/Data/Levels',missionName+'.rhm.json')),template=missionName==='Tac19_FoB_EC'?'net-03-empty':'net-01-empty',contract=await read(join(lib,'mission-states/croisement02/contracts',missionName+'-'+template+'.json')),native=contract.native;
native.background_states=[];native.patch_states=native.patch_states.filter(s=>s.integrate_in_background);const patch=native.patch_states.find(p=>p.id===binding.id);if(!patch)throw Error('Missing source fence state');patch.activation='phases';
contract.families=[{id:'south-field-fence',element_ids:[],background_ids:[],patch_ids:[patch.id],body_terminal_tick:Math.max(1,patch.transition.reduce((n,f)=>n+f.delay+1,0)-1),physical:{initial:[first],applied:[last,floor]},static_replacements:{initial:initial.static_replacements,applied:initial.static_replacements}}];
try{validateStateDelivery(contract);await verifyNativePresentationSource(native,{name:missionName,data:mission,level,camera:{kind:'oblique-orthographic',elevation_deg:35}});const path=join('contracts',missionName+'-south-field-fence.json'),bytes=JSON.stringify(contract,null,2)+'\n';await writeFile(join(out,path),bytes);records.push({mission:missionName,contract:path,sha256:sha(bytes),status:'SOURCE_BINDINGS_PASS; matching refined static document and context/Editor proof pending',terminal_tick:contract.families[0].body_terminal_tick});}catch(e){records.push({mission:missionName,status:'HOLD',error:String(e)});}}
await writeFile(join(out,'manifest.json'),JSON.stringify({scope:'Private independently controlled fence-clearing source state. Exact real static019/020 replacement pins required; existing WIP placement must reject, not hide unrelated geometry. Approved narrow native floor overlay only; no full-ground replacement or automatic cart/fence script sequence.',records,resources:sources,placement_pins_sha256:initial.placement_pins_sha256},null,2)+'\n');console.log(records);
