import {spawn} from 'node:child_process';
import fs from 'node:fs/promises';
import path from 'node:path';
import {createHash} from 'node:crypto';
import {stripTypeScriptTypes} from 'node:module';
import {chromeEndpoint,socketOpen,evaluate} from '../../app/tests/cdp.mjs';
const root=process.cwd(),namespace=process.env.C02_EXPORT_NAMESPACE||'restart7-tree07-approved-export-v1',base=path.join(root,'level-editor/work/croisement02-refinement',namespace),out=path.join(base,process.env.C02_TREE07_REVIEW_DIR||'webgl-v2');await fs.mkdir(out,{recursive:true});
const displaySource=await fs.readFile(path.join(root,'level-editor/app/src/texture-display.ts'),'utf8'),displayHash=createHash('sha256').update(displaySource).digest('hex');await fs.writeFile(path.join(out,'texture-display.js'),stripTypeScriptTypes(displaySource,{mode:'strip'}));
const modelUrl=process.env.C02_TREE07_MODEL_URL||'../delivery-v2/lossless.glb';
const source=JSON.parse(await fs.readFile(process.env.C02_REVIEW_CAMERAS||path.join(root,'level-editor/work/croisement02-refinement/restart6-tree07-bark-fill-v1/native-restored-v1/full/renders.json'),'utf8'));const exportProof=JSON.parse(await fs.readFile(path.join(base,'export.json'),'utf8'));const resolution=source.resolution||384;const closeSource=JSON.parse(await fs.readFile(path.join(path.dirname(exportProof.source_model),'close/renders.json'),'utf8'));const woodNames=exportProof.source_receivers.filter(o=>!o.object.toLowerCase().includes('crown')).map(o=>o.object);
await fs.writeFile(path.join(out,'views.json'),JSON.stringify(source.renders));
const html=`<!doctype html><meta charset="utf-8"><style>body{margin:0;background:#303030}</style><script type="importmap">{"imports":{"three":"/level-editor/app/node_modules/three/build/three.module.js","three/addons/":"/level-editor/app/node_modules/three/examples/jsm/"}}</script><script type="module">
import * as T from 'three';import{TextureDisplay}from'./texture-display.js';import {GLTFLoader}from'three/addons/loaders/GLTFLoader.js';import{MeshoptDecoder}from'/level-editor/app/node_modules/meshoptimizer/meshopt_decoder.mjs';
window.proof={status:'loading'};try{
const loader=new GLTFLoader().setMeshoptDecoder(MeshoptDecoder);loader.register(parser=>{parser.textureLoader=new T.TextureLoader(loader.manager).setCrossOrigin(parser.options.crossOrigin).setRequestHeader(parser.options.requestHeader);return{name:'RLE_reloadable_texture_images'};});
const loaded=await loader.loadAsync('${modelUrl}'),scene=new T.Scene(),C=new T.Matrix4().makeRotationX(-Math.PI/2),Ci=C.clone().invert(),M=new T.Matrix4().makeTranslation(...${JSON.stringify(exportProof.pivot)});loaded.scene.updateMatrixWorld(true);let meshes=0,triangles=0;const parts=${JSON.stringify(exportProof.parts)};
for(const name of parts){const part=loaded.scene.getObjectByName(name);if(!part)throw Error('Missing stable part '+name);const clone=part.clone(true);clone.matrixAutoUpdate=false;clone.matrix.copy(C.clone().multiply(M).multiply(Ci).multiply(part.matrixWorld));scene.add(clone);}
scene.traverse(o=>{if(!o.isMesh)return;meshes++;triangles+=(o.geometry.index?.count??o.geometry.attributes.position.count)/3;});scene.updateMatrixWorld(true);
const depthRanges=[];const views=await(await fetch('views.json')).json(),renderer=new T.WebGLRenderer({antialias:true,preserveDrawingBuffer:true,alpha:true});renderer.setClearColor(0x303030,1);renderer.outputColorSpace=T.SRGBColorSpace;renderer.toneMapping=T.NoToneMapping;new TextureDisplay().apply(scene,renderer.capabilities.getMaxAnisotropy());document.body.append(renderer.domElement);
function draw(matrix,scale,width,height){const aspect=width/height,camera=new T.OrthographicCamera(-scale/2,scale/2,scale/2/aspect,-scale/2/aspect,.01,30000),mat=new T.Matrix4().set(...matrix.flat()).premultiply(C);camera.matrixAutoUpdate=false;camera.matrix.copy(mat);camera.matrixWorld.copy(mat);camera.matrixWorldInverse.copy(mat).invert();const bounds=new T.Box3().setFromObject(scene),depths=[];for(const x of[bounds.min.x,bounds.max.x])for(const y of[bounds.min.y,bounds.max.y])for(const z of[bounds.min.z,bounds.max.z])depths.push(-new T.Vector3(x,y,z).applyMatrix4(camera.matrixWorldInverse).z);camera.near=Math.max(.01,Math.min(...depths)-1);camera.far=Math.max(...depths)+1;depthRanges.push({near:camera.near,far:camera.far,width,height});camera.updateProjectionMatrix();renderer.setSize(width,height);renderer.render(scene,camera);return renderer.domElement.toDataURL('image/png');}
window.renderView=i=>draw(views[i].camera_matrix,views[i].ortho_scale,${resolution},${resolution});const closeViews=${JSON.stringify(closeSource.renders)},woodNames=new Set(${JSON.stringify(woodNames)});window.renderCloseView=i=>{const visibility=[];scene.traverse(o=>{if(o.isMesh){visibility.push([o,o.visible]);o.visible=woodNames.has(o.name);}});try{return draw(closeViews[i].camera_matrix,closeViews[i].ortho_scale,${resolution},${resolution});}finally{for(const[o,value]of visibility)o.visible=value;}};
window.renderNative=()=>{const a=35*Math.PI/180,m=new T.Matrix4().compose(new T.Vector3(896,-576/Math.sin(a)-6000*Math.cos(a),6000*Math.sin(a)),new T.Quaternion().setFromEuler(new T.Euler(Math.PI/2-a,0,0,'ZYX')),new T.Vector3(1,1,1));const rows=Array.from({length:4},(_,i)=>Array.from({length:4},(_,j)=>m.elements[j*4+i]));return draw(rows,1792,1792,1152);};window.proof={status:'ready',parts,meshes,triangles,renderer:renderer.getContext().getParameter(renderer.getContext().VERSION),sourceCameraFirst:true,modelUrl:'${modelUrl}',productionTextureLoader:true,productionTextureDisplaySha256:'${displayHash}',depthRanges,pivot:${JSON.stringify(exportProof.pivot)},scope:'Private approved ${exportProof.asset_id} lossless derivative with production ownership shader semantics; no catalog or live state changes.'};
}catch(e){window.proof={status:'FAIL',error:String(e),stack:e.stack};}</script>`;
await fs.writeFile(path.join(out,'index.html'),html);await fs.mkdir('/home/phire/.cache/c02-tree07-export',{recursive:true});const profile=await fs.mkdtemp('/home/phire/.cache/c02-tree07-export/profile-');const port=process.env.C02_TREE07_PORT;const chrome=spawn('/usr/bin/chromium',['--headless','--disk-cache-size=16777216','--media-cache-size=16777216','--no-sandbox','--disable-dev-shm-usage','--disable-background-networking','--enable-unsafe-swiftshader','--use-angle=swiftshader','--remote-debugging-port=0','--user-data-dir='+profile,`http://127.0.0.1:${port}/level-editor/work/croisement02-refinement/${namespace}/${path.basename(out)}/index.html`],{stdio:['ignore','ignore','pipe']});let ws,id=0;chrome.stderr.on('data',x=>fs.appendFile(path.join(out,'browser.log'),x));
try{const endpoint=new URL(await chromeEndpoint(chrome,{timeoutMs:15000}));const pages=await(await fetch('http://'+endpoint.host+'/json/list')).json();ws=new WebSocket(pages.find(x=>x.type==='page').webSocketDebuggerUrl);await socketOpen(ws);let proof;for(let i=0;i<180;i++){proof=await evaluate(ws,++id,'window.proof',{timeoutMs:30000});if(proof?.status==='FAIL')throw Error(JSON.stringify(proof));if(proof?.status==='ready')break;await new Promise(r=>setTimeout(r,1000));}if(proof?.status!=='ready')throw Error('Load timeout '+JSON.stringify(proof));for(let i=0;i<source.renders.length;i++){const data=await evaluate(ws,++id,`window.renderView(${i})`,{timeoutMs:60000});await fs.writeFile(path.join(out,`view-${i}.png`),Buffer.from(data.split(',')[1],'base64'));console.log('VIEW',i);}for(let i=0;i<closeSource.renders.length;i++){const data=await evaluate(ws,++id,`window.renderCloseView(${i})`,{timeoutMs:60000});await fs.writeFile(path.join(out,`close-${i}.png`),Buffer.from(data.split(',')[1],'base64'));console.log('CLOSE',i);}const native=await evaluate(ws,++id,'window.renderNative()',{timeoutMs:60000});await fs.writeFile(path.join(out,'native.png'),Buffer.from(native.split(',')[1],'base64'));proof=await evaluate(ws,++id,'window.proof',{timeoutMs:30000});await fs.writeFile(path.join(out,'runtime.json'),JSON.stringify(proof,null,2));}finally{ws?.close();chrome.kill('SIGTERM');await new Promise(r=>{if(chrome.exitCode!==null||chrome.signalCode!==null)return r();const timer=setTimeout(r,5000);chrome.once('exit',()=>{clearTimeout(timer);r();});});}
