/** Isolated headless standard-loader check; uses the repository's existing CDP helpers. */
import {spawn} from 'node:child_process';
import {readFile,writeFile,mkdtemp,rm} from 'node:fs/promises';
import {createServer} from 'node:http';
import {resolve,join,extname} from 'node:path';
import {chromeEndpoint,socketOpen,evaluate} from '../../app/tests/cdp.mjs';
const repo=resolve('.'),output=resolve('level-editor/work/croisement02-refinement/tree41-phase-appearance-proof-v2');
const server=createServer(async(req,res)=>{try{const pathname=decodeURIComponent(new URL(req.url,'http://local').pathname);const file=pathname.startsWith('/@fs/')?pathname.slice(5):join(output,pathname==='/'?'index.html':pathname);if(!resolve(file).startsWith(repo+'/'))throw Error('Outside workspace');const types={'.html':'text/html','.js':'text/javascript','.mjs':'text/javascript','.json':'application/json','.glb':'model/gltf-binary','.png':'image/png'};res.setHeader('Content-Type',types[extname(file)]??'application/octet-stream');res.end(await readFile(file));}catch(e){res.writeHead(404);res.end(String(e))}});
await new Promise(r=>server.listen(0,'127.0.0.1',r));const port=server.address().port,profile=await mkdtemp('/tmp/tree41-proof-browser-');
const chrome=spawn('/usr/lib/chromium/chromium',['--headless','--no-sandbox','--disable-dev-shm-usage','--disable-background-networking','--enable-unsafe-swiftshader','--use-angle=swiftshader','--window-size=1000,900','--remote-debugging-port=0','--user-data-dir='+profile,`http://127.0.0.1:${port}/`],{stdio:['ignore','ignore','pipe']});let logs='';chrome.stderr.on('data',d=>{logs+=d.toString()});const closed=new Promise(r=>chrome.on('close',r));let ws,id=0;
try{const endpoint=new URL(await chromeEndpoint(chrome));const pages=await(await fetch('http://'+endpoint.host+'/json/list')).json();ws=new WebSocket(pages.find(p=>p.type==='page').webSocketDebuggerUrl);await socketOpen(ws);let status;
for(let i=0;i<120;i++){status=await evaluate(ws,++id,'window.animationProof ? {loaded:window.animationProof.loaded,error:window.animationProof.error} : null');if(status)break;await new Promise(r=>setTimeout(r,500))}if(!status?.loaded)throw Error(JSON.stringify(status));
await evaluate(ws,++id,'window.animationProof.pause()');const samples=[];for(const phase of Array.from({length:14},(_,i)=>i)){samples.push(await evaluate(ws,++id,`(()=>{animationProof.setTime(${phase*.1+.001});return {phase:${phase},states:animationProof.weights()}})()`));if(![0,7,11].includes(phase))continue;await new Promise(r=>setTimeout(r,300));const screenshot=await new Promise((ok,no)=>{const request=++id;const listener=event=>{const d=JSON.parse(event.data);if(d.id===request){ws.removeEventListener('message',listener);d.error?no(d.error):ok(d.result.data)}};ws.addEventListener('message',listener);ws.send(JSON.stringify({id:request,method:'Page.captureScreenshot',params:{format:'png'}}))});await writeFile(join(output,`browser-phase-${phase}.png`),Buffer.from(screenshot,'base64'))}
for(const sample of samples){const active=sample.states.filter(s=>s.scale.some(v=>v>.5));if(active.length!==1)throw Error('Phase visibility count '+active.length);if(sample.phase&& !active[0].name.includes(`phase_${String(sample.phase).padStart(2,'0')}`)&&!active[0].name.includes(`phase ${String(sample.phase).padStart(2,'0')}`))throw Error('Wrong active phase '+JSON.stringify(active))}
const framing=await evaluate(ws,++id,'animationProof.bounds');const result={status:'PASS',framing,loader:'Three.js GLTFLoader + AnimationMixer',samples};await writeFile(join(output,'browser-verification.json'),JSON.stringify(result,null,2));console.log(JSON.stringify({status:result.status,framing,verified_phases:samples.length,loader:result.loader}));
}catch(error){await writeFile(join(output,'browser-verification.json'),JSON.stringify({status:'FAIL',error:String(error),logs:logs.slice(-4000)},null,2));throw error}finally{ws?.close();chrome.kill('SIGTERM');await closed;await new Promise(r=>server.close(r));await rm(profile,{recursive:true,force:true})}
