"""Rebuild the watchtower's curved shaft and cap from reviewed silhouette evidence."""
import math
import bpy
import bmesh
from mathutils import Vector

ASSET = 'derby-east-watchtower'
TAG = 'east-watchtower-round2-curved-shell-v3'


def _replace(obj, verts, faces):
    mesh = bpy.data.meshes.new(obj.name + ' / round two')
    inverse = obj.matrix_world.inverted()
    mesh.from_pydata([inverse @ Vector(v) for v in verts], [], faces)
    for material in obj.data.materials:
        mesh.materials.append(material)
    mesh.uv_layers.new(name='Round2 placeholder')
    bm = bmesh.new(); bm.from_mesh(mesh)
    bmesh.ops.remove_doubles(bm, verts=list(bm.verts), dist=.0001)
    bmesh.ops.recalc_face_normals(bm, faces=list(bm.faces))
    bm.to_mesh(mesh); bm.free()
    obj.data = mesh
    for polygon in mesh.polygons:
        polygon.use_smooth = abs(polygon.normal.z) < .98
    obj['round2_recipe'] = TAG
    # Source-only projection is regenerated by the workspace handoff.
    obj['projection_min_cosine'] = .05


def _lathe(profiles, segments=96, start=0, end=2*math.pi):
    """Closed solid, including radial end walls for a partial canonical cap."""
    partial = end-start < 2*math.pi-.0001
    count = segments+1 if partial else segments
    verts = [(cx+rx*math.cos(start+(end-start)*i/segments),
              cy+ry*math.sin(start+(end-start)*i/segments), z)
             for z,cx,cy,rx,ry in profiles for i in range(count)]
    faces=[]
    for row in range(len(profiles)-1):
        for i in range(segments):
            j=(i+1)%count
            faces.append((row*count+i,row*count+j,(row+1)*count+j,(row+1)*count+i))
    # A tiny positive terminal radius avoids coincident pole faces.
    if partial:
        bottom=len(verts);top=bottom+1
        z,cx,cy,_,_=profiles[0];verts.append((cx,cy,z))
        z,cx,cy,_,_=profiles[-1];verts.append((cx,cy,z))
        faces.extend((tuple(reversed([bottom]+list(range(count)))),
                      tuple([top]+[(len(profiles)-1)*count+i for i in range(count)])))
        for side in (0,count-1):
            faces.append(tuple([bottom]+[row*count+side for row in range(len(profiles))]+[top]))
    else:
        faces.extend((tuple(reversed(range(count))),
                      tuple((len(profiles)-1)*count+i for i in range(count))))
    return verts,faces


def refine():
    owned=[o for o in bpy.data.collections['Derby Working'].all_objects
           if o.type=='MESH' and not o.hide_render and o.get('asset_group')==ASSET]
    by={o.get('source_node'):o for o in owned}
    if by['building-214'].get('round2_recipe')==TAG:
        return {'status':'existing'}
    # A constant polygonal column contradicted the narrow midshaft and flared
    # base of reviewed mask162. Heights/depth remain a conservative reconstruction.
    profiles=[(0,1783,-2478,87,85),(55,1783,-2478,85,83),
              (115,1783,-2478,77,77),(190,1783.5,-2478,70.8,72),
              (310,1783.5,-2478,71.5,72),(430,1785,-2478,73,74),
              (510,1789,-2478,80,78),(558.4,1791,-2478,86,82),
              (579.87,1791,-2478,86,82)]
    _replace(by['building-214'],*_lathe(profiles))
    # Remove the second full-height shell while preserving the reviewed seven
    # crenels and the access opening. Boundary closures stay below the walk.
    obj=by['building-215']; bm=bmesh.new(); bm.from_mesh(obj.data)
    bm.transform(obj.matrix_world)
    bmesh.ops.bisect_plane(bm,geom=list(bm.verts)+list(bm.edges)+list(bm.faces),
                          plane_co=(0,0,558.4),plane_no=(0,0,1),dist=.001,clear_inner=True)
    edges=[e for e in bm.edges if e.is_boundary]
    if any(v.co.z>580 for e in edges for v in e.verts):
        raise ValueError('Unexpected boundary above the roof walk')
    bmesh.ops.holes_fill(bm,edges=edges,sides=0)
    bmesh.ops.recalc_face_normals(bm,faces=list(bm.faces))
    bm.transform(obj.matrix_world.inverted()); bm.to_mesh(obj.data);bm.free()
    obj['round2_recipe']=TAG
    _replace(by['building-219'],*_lathe([(579.87,1847.8,-2432,38.6,41),
                                       (661.5,1847.8,-2432,38.6,41)],72))
    for part in range(3):
        profiles=[]
        for row in range(25):
            t=row/24
            r=max(.06,43.335*(1-t)**1.24)
            profiles.append((661.6+115.79*t,1846.3,-2435,r,r*41.5/40.5))
        # Each source part is a closed third of one continuous roof, rather
        # than a collection of individually extruded triangle prisms.
        verts,faces=_lathe(profiles,24,part*2*math.pi/3,(part+1)*2*math.pi/3)
        _replace(by[f'building-{220+part}'],verts,faces)
    # Small finial visible above the roof tip, assigned to its existing roof part.
    obj=by['building-220']; verts=[tuple(obj.matrix_world@v.co) for v in obj.data.vertices]
    faces=[tuple(p.vertices) for p in obj.data.polygons]
    more,polys=_lathe([(776.5,1846.8,-2435,1.2,1.2),
                      (810,1846.8,-2435,.65,.65),(815,1846.8,-2435,.08,.08)],12)
    off=len(verts);verts.extend(more);faces.extend(tuple(off+i for i in p) for p in polys)
    _replace(obj,verts,faces)
    # Give the three canonical sectors the same analytic surface normals at
    # their shared edges; end-wall normals must not crease the roof exterior.
    for number in (220,221,222):
        obj=by[f'building-{number}']; mesh=obj.data; normals=[]
        for polygon in mesh.polygons:
            for loop in polygon.loop_indices:
                if len(polygon.vertices)==4:
                    p=obj.matrix_world@mesh.vertices[mesh.loops[loop].vertex_index].co
                    t=max(0,min(1,(p.z-661.6)/115.79))
                    angle=math.atan2((p.y+2435)/(41.5/40.5),p.x-1846.3)
                    slope=43.335*1.24/115.79*max(0,1-t)**.24
                    normal=Vector((math.cos(angle),math.sin(angle)/(41.5/40.5),slope)).normalized()
                    normals.append(tuple(obj.matrix_world.to_3x3().transposed()@normal))
                else:
                    normals.append(tuple(polygon.normal))
        mesh.normals_split_custom_set(normals)
    report=[]
    for obj in owned:
        bm=bmesh.new();bm.from_mesh(obj.data)
        bad=sum(not e.is_manifold for e in bm.edges)
        degenerate=sum(f.calc_area()<1e-8 for f in bm.faces)
        bm.free()
        report.append({'node':obj['source_node'],'name':obj.name,
                       'nonmanifold_edges':bad,'degenerate_faces':degenerate})
        if bad or degenerate:
            raise ValueError(report[-1])
    bpy.context.view_layer.update()
    return {'status':'refined','recipe':TAG,'objects':report}
