"""Rebuild the watchtower's curved shaft and cap from reviewed silhouette evidence."""
import math
import bpy
import bmesh
from mathutils import Vector

ASSET = 'derby-east-watchtower'
TAG = 'east-watchtower-round2-curved-shell-v3'


def _replace(obj, verts, faces, weld=True):
    mesh = bpy.data.meshes.new(obj.name + ' / round two')
    inverse = obj.matrix_world.inverted()
    mesh.from_pydata([inverse @ Vector(v) for v in verts], [], faces)
    for material in obj.data.materials:
        mesh.materials.append(material)
    mesh.uv_layers.new(name='Round2 placeholder')
    bm = bmesh.new(); bm.from_mesh(mesh)
    if weld:
        bmesh.ops.remove_doubles(bm, verts=list(bm.verts), dist=.0001)
    bmesh.ops.recalc_face_normals(bm, faces=list(bm.faces))
    bm.to_mesh(mesh); bm.free()
    obj.data = mesh
    for polygon in mesh.polygons:
        polygon.use_smooth = abs(polygon.normal.z) < .98
    obj['round2_recipe'] = TAG
    # Source-only projection is regenerated by the workspace handoff.
    obj['projection_min_cosine'] = .05


def _lathe(profiles, segments=96, start=0, end=2*math.pi):
    """Closed solid, including radial end walls for a partial canonical cap."""
    partial = end-start < 2*math.pi-.0001
    count = segments+1 if partial else segments
    verts = [(cx+rx*math.cos(start+(end-start)*i/segments),
              cy+ry*math.sin(start+(end-start)*i/segments), z)
             for z,cx,cy,rx,ry in profiles for i in range(count)]
    faces=[]
    for row in range(len(profiles)-1):
        for i in range(segments):
            j=(i+1)%count
            faces.append((row*count+i,row*count+j,(row+1)*count+j,(row+1)*count+i))
    # A tiny positive terminal radius avoids coincident pole faces.
    if partial:
        bottom=len(verts);top=bottom+1
        z,cx,cy,_,_=profiles[0];verts.append((cx,cy,z))
        z,cx,cy,_,_=profiles[-1];verts.append((cx,cy,z))
        faces.extend((tuple(reversed([bottom]+list(range(count)))),
                      tuple([top]+[(len(profiles)-1)*count+i for i in range(count)])))
        for side in (0,count-1):
            faces.append(tuple([bottom]+[row*count+side for row in range(len(profiles))]+[top]))
    else:
        faces.extend((tuple(reversed(range(count))),
                      tuple((len(profiles)-1)*count+i for i in range(count))))
    return verts,faces


def _refine_shell():
    owned=[o for o in bpy.data.collections['Derby Working'].all_objects
           if o.type=='MESH' and not o.hide_render and o.get('asset_group')==ASSET]
    by={o.get('source_node'):o for o in owned}
    if by['building-214'].get('round2_recipe')==TAG:
        return {'status':'existing'}
    # A constant polygonal column contradicted the narrow midshaft and flared
    # base of reviewed mask162. Heights/depth remain a conservative reconstruction.
    profiles=[(0,1783,-2478,87,85),(55,1783,-2478,85,83),
              (115,1783,-2478,77,77),(190,1783.5,-2478,70.8,72),
              (310,1783.5,-2478,71.5,72),(430,1785,-2478,73,74),
              (510,1789,-2478,80,78),(558.4,1791,-2478,86,82),
              (579.87,1791,-2478,86,82)]
    _replace(by['building-214'],*_lathe(profiles))
    # Remove the second full-height shell while preserving the reviewed seven
    # crenels and the access opening. Boundary closures stay below the walk.
    obj=by['building-215']; bm=bmesh.new(); bm.from_mesh(obj.data)
    bm.transform(obj.matrix_world)
    bmesh.ops.bisect_plane(bm,geom=list(bm.verts)+list(bm.edges)+list(bm.faces),
                          plane_co=(0,0,558.4),plane_no=(0,0,1),dist=.001,clear_inner=True)
    edges=[e for e in bm.edges if e.is_boundary]
    if any(v.co.z>580 for e in edges for v in e.verts):
        raise ValueError('Unexpected boundary above the roof walk')
    bmesh.ops.holes_fill(bm,edges=edges,sides=0)
    bmesh.ops.recalc_face_normals(bm,faces=list(bm.faces))
    bm.transform(obj.matrix_world.inverted()); bm.to_mesh(obj.data);bm.free()
    obj['round2_recipe']=TAG
    _replace(by['building-219'],*_lathe([(579.87,1847.8,-2432,38.6,41),
                                       (661.5,1847.8,-2432,38.6,41)],72))
    for part in range(3):
        profiles=[]
        for row in range(25):
            t=row/24
            r=max(.06,43.335*(1-t)**1.24)
            profiles.append((661.6+115.79*t,1846.3,-2435,r,r*41.5/40.5))
        # Each source part is a closed third of one continuous roof, rather
        # than a collection of individually extruded triangle prisms.
        verts,faces=_lathe(profiles,24,part*2*math.pi/3,(part+1)*2*math.pi/3)
        _replace(by[f'building-{220+part}'],verts,faces)
    # Small finial visible above the roof tip, assigned to its existing roof part.
    obj=by['building-220']; verts=[tuple(obj.matrix_world@v.co) for v in obj.data.vertices]
    faces=[tuple(p.vertices) for p in obj.data.polygons]
    more,polys=_lathe([(776.5,1846.8,-2435,1.2,1.2),
                      (810,1846.8,-2435,.65,.65),(815,1846.8,-2435,.08,.08)],12)
    off=len(verts);verts.extend(more);faces.extend(tuple(off+i for i in p) for p in polys)
    _replace(obj,verts,faces)
    # Give the three canonical sectors the same analytic surface normals at
    # their shared edges; end-wall normals must not crease the roof exterior.
    for number in (220,221,222):
        obj=by[f'building-{number}']; mesh=obj.data; normals=[]
        for polygon in mesh.polygons:
            for loop in polygon.loop_indices:
                if len(polygon.vertices)==4:
                    p=obj.matrix_world@mesh.vertices[mesh.loops[loop].vertex_index].co
                    t=max(0,min(1,(p.z-661.6)/115.79))
                    angle=math.atan2((p.y+2435)/(41.5/40.5),p.x-1846.3)
                    slope=43.335*1.24/115.79*max(0,1-t)**.24
                    normal=Vector((math.cos(angle),math.sin(angle)/(41.5/40.5),slope)).normalized()
                    normals.append(tuple(obj.matrix_world.to_3x3().transposed()@normal))
                else:
                    normals.append(tuple(polygon.normal))
        mesh.normals_split_custom_set(normals)
    report=[]
    for obj in owned:
        bm=bmesh.new();bm.from_mesh(obj.data)
        bad=sum(not e.is_manifold for e in bm.edges)
        degenerate=sum(f.calc_area()<1e-8 for f in bm.faces)
        bm.free()
        report.append({'node':obj['source_node'],'name':obj.name,
                       'nonmanifold_edges':bad,'degenerate_faces':degenerate})
        if bad or degenerate:
            raise ValueError(report[-1])
    bpy.context.view_layer.update()
    return {'status':'refined','recipe':TAG,'objects':report}


def _rod(vertices, faces, start, end, radius, sides=10):
    """Closed rod, including both caps; endpoints are map-world coordinates."""
    a,b=Vector(start),Vector(end)
    axis=(b-a).normalized()
    side=axis.cross(Vector((0,0,1)))
    if side.length < .01:
        side=axis.cross(Vector((1,0,0)))
    side.normalize();other=axis.cross(side).normalized()
    offset=len(vertices)
    for point in (a,b):
        vertices.extend(tuple(point+radius*(math.cos(i*2*math.pi/sides)*side+
                                            math.sin(i*2*math.pi/sides)*other))
                        for i in range(sides))
    faces.extend(tuple(offset+j for j in face) for face in
                 [tuple(reversed(range(sides))),tuple(sides+i for i in range(sides))])
    faces.extend((offset+i,offset+(i+1)%sides,
                  offset+sides+(i+1)%sides,offset+sides+i) for i in range(sides))


def _machinery():
    obj=next(o for o in bpy.data.collections['Derby Working'].all_objects
             if o.type=='MESH' and not o.hide_render and
             o.get('asset_group')==ASSET and o.get('source_node')=='building-215')
    tag='watchtower-hoist-native-mask233-v2'
    if obj.get('round2_machinery')==tag:
        return {'status':'existing'}
    if obj.get('round2_machinery'):
        raise ValueError('Apply a changed machinery recipe to the immutable baseline, not an older machinery build')
    vertices=[tuple(obj.matrix_world@v.co) for v in obj.data.vertices]
    faces=[tuple(p.vertices) for p in obj.data.polygons]
    before=len(faces)
    # Two timber uprights and a framed projecting boom. Source mask233 is
    # distinct from the tower mask and belongs to the roof-walk layer.
    for x,y in ((1752,-2467),(1764,-2457)):
        _rod(vertices,faces,(x,y,579.87),(x,y,700),3.5,4)
    root=(1758,-2462,686);tip=(1659,-2548.4,692.2)
    _rod(vertices,faces,root,tip,3.8,4)
    _rod(vertices,faces,(1758,-2462,674),(1659,-2548.4,680.2),3.1,4)
    for t in (0,.25,.7,1):
        x=root[0]+t*(tip[0]-root[0]);y=root[1]+t*(tip[1]-root[1])
        _rod(vertices,faces,(x,y,673+t*6.2),(x,y,688+t*6.2),1.9,4)
    # Visible diagonal support and foot braces terminate on the roof walk.
    _rod(vertices,faces,(1758,-2462,602),(1711,-2503,677),3.2,4)
    _rod(vertices,faces,(1752,-2467,605),(1729,-2478,580),2.8,4)
    _rod(vertices,faces,(1764,-2457,605),(1780,-2449,580),2.8,4)
    # The source shows an exposed star-shaped windlass handle at the frame foot.
    hub=Vector((1746,-2490,600))
    _rod(vertices,faces,hub,(1758,-2462,600),2.1,10)
    for spoke in range(6):
        angle=2*math.pi*spoke/6+.2
        end=hub+Vector((11*math.cos(angle),0,11*math.sin(angle)))
        _rod(vertices,faces,hub,end,1.25,6)
    # Basket ribs use a rounded, tapered profile; ten ribs and three hoops
    # preserve genuine empty space instead of an opaque sprite-shaped cage.
    cx,cy=1672,-2537
    profiles=((667,.8),(660,6),(647,14),(632,19.3),
              (621,19.1),(607,15.5),(595,10),(589,5),(586,2))
    _rod(vertices,faces,(cx,cy,691.4),(cx,cy,667),.65,8)
    for rib in range(10):
        angle=2*math.pi*rib/10
        points=[(cx+max(0,(610-z)/24)*1.2+r*math.cos(angle),
                 cy+r*math.sin(angle),z) for z,r in profiles]
        for a,b in zip(points,points[1:]):
            _rod(vertices,faces,a,b,.48,6)
    for z,r in ((647,14),(626,19.2),(604,14)):
        points=[(cx+r*math.cos(i*2*math.pi/48),cy+r*math.sin(i*2*math.pi/48),z)
                for i in range(48)]
        for i,a in enumerate(points):
            _rod(vertices,faces,a,points[(i+1)%48],.55,6)
    _replace(obj,vertices,faces,weld=False)
    for polygon in obj.data.polygons:
        polygon.use_smooth=False
    obj['round2_machinery']=tag
    obj['round2_machinery_first_polygon']=before
    obj['reviewed_occlusion_mask_indices']='162,233'
    bm=bmesh.new();bm.from_mesh(obj.data)
    bad=sum(not edge.is_manifold for edge in bm.edges)
    degenerate=sum(face.calc_area()<1e-8 for face in bm.faces)
    bm.free()
    if bad or degenerate:
        raise ValueError(f'Invalid machinery: {bad} nonmanifold edges, {degenerate} degenerate faces')
    return {'status':'refined','added_faces':len(faces)-before,
            'native_mask':233,'owner':'building-215',
            'nonmanifold_edges':bad,'degenerate_faces':degenerate}


def refine():
    shell=_refine_shell()
    machinery=_machinery()
    return {'shell':shell,'machinery':machinery}
