"""Align the lower east stair's risers and close its landing junction."""
import math

import bpy
import bmesh
from mathutils import Vector

ASSET = 'derby-lower-east-curtain'
TAG = 'lower-east-stair-landing-and-tread-phase-v4'


def refine():
    objects = [o for o in bpy.data.collections['Derby Working'].objects
               if o.type == 'MESH' and o.get('asset_group') == ASSET
               and not o.hide_render]
    stair = next(o for o in objects if o.get('source_node') == 'building-012')
    landing = next(o for o in objects if o.get('source_node') == 'building-044')
    if stair.get('round2_refinement') == TAG:
        return {'asset': ASSET, 'status': 'already applied'}
    points = [stair.matrix_world @ v.co for v in stair.data.vertices]
    # Retain the audited footprint. Twenty painted bright tread bands run
    # from source y1831 to y2068. A riser immediately below the landing and
    # another at the toe require twenty-one rises around those twenty treads.
    # A full-height twentieth tread projects the painted first riser onto a
    # horizontal surface, shifting the entire stair's material phase.
    count = 21
    half = len(points) // 2
    lower_left, lower_right = points[0].copy(), points[half].copy()
    upper_left = max(points[:half], key=lambda p: (p.z, p.y)).copy()
    upper_right = max(points[half:], key=lambda p: (p.z, p.y)).copy()
    walk = [landing.matrix_world @ v.co for v in landing.data.vertices]
    top = max(p.z for p in walk)
    walk_top = [p for p in walk if abs(p.z - top) < .001]
    upper_left = min(walk_top, key=lambda p: (p - upper_left).length).copy()
    upper_right = min(walk_top, key=lambda p: (p - upper_right).length).copy()
    # Join the cheek to the same straight inner wall, rather than retaining a
    # subpixel gap between independently rounded exported footprints.
    inner_end = min(walk_top, key=lambda p: (p - Vector((1016.74, -3991.42, top))).length)
    fraction = (lower_right.y - upper_right.y) / (inner_end.y - upper_right.y)
    lower_right.x = upper_right.x + fraction * (inner_end.x - upper_right.x)
    base = min(lower_left.z, lower_right.z)
    rise = (top - base) / count
    profile = [(0.0, base)]
    # The landing wall supplies the final riser. Extending this stair to its
    # height at the same run coordinate would retrace the closed cheek profile
    # and create two opposite faces over the top riser (a zero-volume flap).
    # Stop at the final tread, leaving the existing landing face exposed.
    for i in range(count - 1):
        profile.append((i / (count - 1), base + (i + 1) * rise))
        profile.append(((i + 1) / (count - 1), base + (i + 1) * rise))
    profile.append((1.0, base))
    vertices = []
    inverse = stair.matrix_world.inverted()
    for start, end in ((lower_left, upper_left), (lower_right, upper_right)):
        for t, z in profile:
            p = start.lerp(end, t)
            p.z = z
            vertices.append(inverse @ p)
    n = len(profile)
    faces = [tuple(range(n)), tuple(range(n, 2 * n))]
    faces.extend((i, (i + 1) % n, (i + 1) % n + n, i + n) for i in range(n))
    mesh = bpy.data.meshes.new('Lower east stair / twenty treads joining landing riser')
    mesh.from_pydata(vertices, [], faces)
    bm = bmesh.new()
    bm.from_mesh(mesh)
    bmesh.ops.recalc_face_normals(bm, faces=list(bm.faces))
    if any(not e.is_manifold for e in bm.edges) or any(f.calc_area() < 1e-8 for f in bm.faces):
        raise ValueError('Stair reconstruction is not closed and nondegenerate')
    bm.to_mesh(mesh)
    bm.free()
    # A simple source UV exists for the mandatory visibility-aware reprojection
    # pass. Hidden-side donors are regenerated by the editor's synthesis layer.
    uv = mesh.uv_layers.new(name='UVMap')
    sine, cosine = math.sin(math.radians(35)), math.cos(math.radians(35))
    for loop in mesh.loops:
        p = stair.matrix_world @ mesh.vertices[loop.vertex_index].co
        uv.data[loop.index].uv = (p.x / 1920, 1 - (-p.y * sine - p.z * cosine) / 2752)
    mesh.materials.append(stair.data.materials[0])
    stair.data = mesh
    stair['round2_refinement'] = TAG
    stair['step_count'] = count
    stair['tread_count'] = count - 1
    stair['landing_riser_source_node'] = 'building-044'
    stair['todo'] = 'Hidden cheek detail remains unconstrained; do not treat synthesized masonry as geometry evidence.'
    bpy.context.view_layer.update()
    validation = []
    for obj in objects:
        bm = bmesh.new()
        bm.from_mesh(obj.data)
        record = {'source_node': obj['source_node'], 'faces': len(bm.faces),
                  'nonmanifold_edges': sum(not e.is_manifold for e in bm.edges),
                  'degenerate_faces': sum(f.calc_area() < 1e-8 for f in bm.faces)}
        bm.free()
        validation.append(record)
    if any(r['nonmanifold_edges'] or r['degenerate_faces'] for r in validation):
        raise ValueError(validation)
    return {'asset': ASSET, 'changed_nodes': ['building-012'],
            'unchanged_nodes': ['building-007', 'building-010', 'building-024', 'building-041', 'building-044'],
            'risers': count, 'treads': count - 1,
            'landing_riser_source_node': 'building-044',
            'landing_riser_height': rise,
            'validation': validation}
