[package]
name = "robin_modding_tools"
version.workspace = true
edition.workspace = true
publish.workspace = true

[features]
default = ["cli"]
cli = ["dep:clap", "dep:png", "dep:tracing-subscriber"]

[[bin]]
name = "cpf_to_json"
required-features = ["cli"]

[[bin]]
name = "disasm_scb"
required-features = ["cli"]

[[bin]]
name = "dump_res"
required-features = ["cli"]

[[bin]]
name = "encode_mod_sprites"
required-features = ["cli"]

[dependencies]
anyhow.workspace = true
clap = { workspace = true, features = ["derive"], optional = true }
png = { workspace = true, optional = true }
robin_assets.workspace = true
robin_data_io.workspace = true
robin_engine.workspace = true
robin_util.workspace = true
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
tracing.workspace = true
tracing-subscriber = { workspace = true, features = ["env-filter"], optional = true }

[dev-dependencies]
robin_test_support.workspace = true
tempfile.workspace = true

[lints]
workspace = true
