"""Save a private same-leaf inferred RGB extension, freezing every other pixel."""
import hashlib,json,shutil,sys
from pathlib import Path
import bpy,numpy as np
ROOT=Path(__file__).resolve().parents[3];sys.path.insert(0,str(ROOT/'level-editor/refinement'));sys.path.insert(0,str(Path(__file__).parent))
from render_slots import acquire
from restart2_bake_texture_candidate import snapshot,pixels,array_hash
R=ROOT/'level-editor/work/croisement01-refinement/restart2';C=R/'approved-tree02-fill-v1/croisement01-tree-02';B=C/'baked-v2-two-sided-crown';O=C/'baked-v3-same-leaf-crown';P=R/'tree02-leaf-donor-probe-v1';D=R/'tree02-same-leaf-fill-cpu-v1'
sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
assert not O.exists();assert shutil.disk_usage(R).free>=10*1024**3+32*1024**2;assert next(int(s.split()[1]) for s in Path('/proc/meminfo').read_text().splitlines() if s.startswith('MemAvailable:'))>=6*1024**2
plan=json.loads((D/'report.json').read_text());assert sha(B/'worker.blend')==plan['model_sha256'];assert sha(P/'mesh.json')==plan['probe_mesh_sha256'] and sha(P/'atlas.npz')==plan['probe_atlas_sha256'];assert plan['planned_texels']==316;assert all(x['max_distance_fraction']<=.2 for x in plan['leaves']);acquire();O.mkdir();bpy.context.preferences.filepaths.save_version=0;bpy.ops.wm.open_mainfile(filepath=str(B/'worker.blend'))
manifest=json.loads((C/'experiment/views.json').read_text());scene=bpy.data.scenes[manifest['scene_name']];names=set(manifest['object_names']);before=snapshot(scene,names);all_uvs={o.name:{uv.name:array_hash([x.uv[:] for x in uv.data]) for uv in o.data.uv_layers} for o in scene.objects if o.type=='MESH'}
m=bpy.data.objects['Tree02 inferred crown'].data;used={f.material_index for f in m.polygons};a=np.load(P/'atlas.npz');own=a['ownership'];expected=np.stack([a['values_'+str(c)][a['index_'+str(c)]] for c in range(4)],axis=-1);h,w=own.shape;images={n.image.name:n.image for i,mat in enumerate(m.materials) if i in used and mat and mat.use_nodes for n in mat.node_tree.nodes if n.type=='TEX_IMAGE' and n.image and tuple(n.image.size)==(w,h)};assert len(images)==1;image=next(iter(images.values()));image_name=image.name;assert np.array_equal(pixels(image),expected)
other={im.name:array_hash(pixels(im)) for im in bpy.data.images if im!=image and len(im.pixels)};after=expected.copy();ownership=own.copy()
for item in plan['plan']:
 x,y=item['target'];sx,sy=item['donor'];assert own[y,x]==0 and own[sy,sx]==2;after[y,x,:3]=expected[sy,sx,:3];ownership[y,x]=3
assert np.array_equal(after[own!=0],expected[own!=0]) and np.array_equal(after[:,:,3],expected[:,:,3]);assert np.any(after!=expected,axis=2).sum()==316
image.pixels.foreach_set(after.ravel());image.update();image.pack();model=O/'worker.blend';bpy.ops.wm.save_as_mainfile(filepath=str(model),compress=True);assert model.stat().st_size<29*1024**2;bpy.ops.wm.open_mainfile(filepath=str(model));assert snapshot(bpy.data.scenes[manifest['scene_name']],names)==before;assert np.array_equal(pixels(bpy.data.images[image_name]),after)
assert all(array_hash(pixels(bpy.data.images[n]))==v for n,v in other.items());assert {o.name:{uv.name:array_hash([x.uv[:] for x in uv.data]) for uv in o.data.uv_layers} for o in bpy.data.scenes[manifest['scene_name']].objects if o.type=='MESH'}==all_uvs
validation=json.loads((B/'validation.json').read_text());entry=next(x for x in validation['layers'][0]['objects'] if x['object']=='Tree02 inferred crown');provenance=O/'crown-provenance.npz';np.savez_compressed(provenance,ownership=ownership);entry['texel_provenance']['path']=str(provenance.resolve());entry['texel_provenance']['sha256']=sha(provenance);entry['texel_provenance']['packed_image_sha256']=hashlib.sha256(bpy.data.images[image_name].packed_file.data).hexdigest();entry['texel_provenance']['rgba8_sha256']=hashlib.sha256(np.rint(np.clip(after,0,1)*255).astype(np.uint8).tobytes()).hexdigest();entry['texel_provenance']['semantics']['3']='bounded-same-leaf-extrapolation';entry['inferred_gap_repairs']=[{'faces':x['faces'],'repaired_texels':x['unknown_targets'],'scope':'same physical leaf generated donor only','maximum_distance_fraction':x['max_distance_fraction']} for x in plan['leaves']];entry['inferred_same_leaf_extension']={'texels':316,'donor_plan':str(D/'report.json'),'donor_plan_sha256':sha(D/'report.json'),'native_ownership_changed':False};(O/'validation.json').write_text(json.dumps(validation,indent=2)+'\n')
W=O/'actual-review-v1';W.mkdir();(W/'inspection').mkdir();(W/'modified').mkdir();(W/'model.blend').symlink_to(model.resolve());shutil.copy2(B/'actual-review-v1/workspace.json',W/'workspace.json');shutil.copy2(B/'actual-review-v1/modified/views.json',W/'modified/views.json')
report={'status':'SAVED PRESERVATION PASS; ACTUAL REVIEW PENDING','model_sha256':sha(model),'parent_model_sha256':plan['model_sha256'],'same_leaf_inferred_rgb_texels':316,'all_other_rgba_unchanged':True,'all_alpha_unchanged':True,'geometry_uv_ownership_foreign_appearance_unchanged':True,'cpu_donor_plan':str(D/'report.json'),'texture_approval':'pending','canonical_writes':False};(O/'reopened-preservation.json').write_text(json.dumps(report,indent=2)+'\n');assert sha(B/'worker.blend')==plan['model_sha256'];assert sum(x.stat().st_size for x in O.rglob('*') if x.is_file() and not x.is_symlink())+2.5*1024**2<=32*1024**2;print(json.dumps(report),flush=True)
