"""Privately transfer the approved Tree03 source domain out of native017 paint."""
import copy,hashlib,json,math,struct
from pathlib import Path
import numpy as np
from PIL import Image
ROOT=Path(__file__).resolve().parents[3];R=ROOT/'level-editor/work/croisement01-refinement/restart2';LIB=ROOT/'level-editor/library';source=LIB/'3d-assets/croisement01/croisement01-group-005';out=R/'tree03-visual-transfer-v1';out.mkdir(exist_ok=False);asset=out/'3d-assets/croisement01/croisement01-group-005';asset.mkdir(parents=True);blobs=out/'3d-assets/blobs';blobs.mkdir()
sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
def write(p,d):p.write_text(json.dumps(d,indent=2)+'\n')
b=(source/'model.glb').read_bytes();length=struct.unpack_from('<I',b,12)[0];original=json.loads(b[20:20+length]);g=copy.deepcopy(original);descriptor=json.loads((source/'asset.json').read_text());node=next(n for n in g['nodes'] if n.get('name')=='building-017');mesh=g['meshes'][node['mesh']];assert len(mesh['primitives'])==1;primitive=mesh['primitives'][0]
def accessor(index):
 a=g['accessors'][index];v=g['bufferViews'][a['bufferView']];buffer=g['buffers'][v['buffer']];raw=(source/buffer['uri']).read_bytes() if 'uri' in buffer else b[28+length:];dtype={5126:'<f4',5123:'<u2',5125:'<u4'}[a['componentType']];components={'SCALAR':1,'VEC2':2,'VEC3':3}[a['type']];size=np.dtype(dtype).itemsize;stride=v.get('byteStride',components*size);return np.ndarray((a['count'],components),dtype=dtype,buffer=raw,offset=v.get('byteOffset',0)+a.get('byteOffset',0),strides=(stride,size)).copy()
pos=accessor(primitive['attributes']['POSITION'])+np.array(descriptor['source_origin_scene']);uv=accessor(primitive['attributes']['TEXCOORD_0']);indices=accessor(primitive['indices']).reshape(-1,3);screen=np.column_stack([pos[:,0],-pos[:,1]*math.sin(math.radians(35))-pos[:,2]*math.cos(math.radians(35))]);domainpath=R/'tree03-ownership-v2/building-017-tree03-overlap.png';domain=np.asarray(Image.open(domainpath).convert('L'))>0;assert int(domain.sum())==46
oldmaterial=primitive['material'];texture=g['materials'][oldmaterial]['pbrMetallicRoughness']['baseColorTexture']['index'];oldimage=g['textures'][texture]['source'];imagepath=(source/g['images'][oldimage]['uri']).resolve();rgba=np.array(Image.open(imagepath).convert('RGBA'));height,width=rgba.shape[:2];mask=np.zeros((height,width),bool);source_hits=set()
for tri in indices:
 p=uv[tri]*[width,height];left,top=np.floor(p.min(0)).astype(int);right,bottom=np.ceil(p.max(0)).astype(int);left=max(0,left);top=max(0,top);right=min(width,right);bottom=min(height,bottom)
 if right<=left or bottom<=top:continue
 matrix=np.column_stack([p[1]-p[0],p[2]-p[0]])
 if abs(np.linalg.det(matrix))<1e-9:continue
 yy,xx=np.mgrid[top:bottom,left:right];q=np.stack([xx+.5,yy+.5],axis=-1);weights=(q-p[0])@np.linalg.inv(matrix).T;inside=(weights[:,:,0]>=-1e-7)&(weights[:,:,1]>=-1e-7)&(weights.sum(2)<=1+1e-7);sourcepoints=screen[tri[0]]+weights[:,:,0,None]*(screen[tri[1]]-screen[tri[0]])+weights[:,:,1,None]*(screen[tri[2]]-screen[tri[0]]);sx=np.floor(sourcepoints[:,:,0]).astype(int);sy=np.floor(sourcepoints[:,:,1]).astype(int);valid=inside&(sx>=0)&(sx<domain.shape[1])&(sy>=0)&(sy<domain.shape[0]);selected=np.zeros(inside.shape,bool);selected[valid]=domain[sy[valid],sx[valid]];mask[top:bottom,left:right]|=selected;source_hits.update(zip(sx[selected].tolist(),sy[selected].tolist()))
assert int(mask.sum())>0;expected={(int(x),int(y)) for y,x in zip(*np.where(domain))};assert source_hits==expected,(len(source_hits),len(expected));result=rgba.copy();result[mask,3]=0;assert np.array_equal(result[~mask],rgba[~mask]) and np.array_equal(result[:,:,:3],rgba[:,:,:3]);temp=out/'transferred-atlas.png';Image.fromarray(result).save(temp);digest=sha(temp);target=blobs/(digest+'.png');temp.rename(target)
g['images'].append(dict(name='Native017 excluding approved Tree03 pixels',mimeType='image/png',uri='../../blobs/'+target.name));g['textures'].append(dict(g['textures'][texture],source=len(g['images'])-1));material=copy.deepcopy(g['materials'][oldmaterial]);material['name']='Native017 retained paint';material['alphaMode']='MASK';material['alphaCutoff']=.5;material['pbrMetallicRoughness']['baseColorTexture']['index']=len(g['textures'])-1;g['materials'].append(material);primitive['material']=len(g['materials'])-1
assert g['nodes']==original['nodes'] and g['accessors']==original['accessors'] and g['bufferViews']==original['bufferViews'] and g['buffers']==original['buffers'];check=copy.deepcopy(g);check['meshes'][node['mesh']]['primitives'][0]['material']=oldmaterial;assert check['meshes']==original['meshes'];assert g['materials'][:-1]==original['materials'] and g['textures'][:-1]==original['textures'] and g['images'][:-1]==original['images']
encoded=json.dumps(g,separators=(',',':')).encode();encoded+=b' '*((-len(encoded))%4);tail=b[20+length:];packed=struct.pack('<III',0x46546C67,2,20+len(encoded)+len(tail))+struct.pack('<II',len(encoded),0x4E4F534A)+encoded+tail;(asset/'model.glb').write_bytes(packed);newdescriptor=copy.deepcopy(descriptor);newdescriptor['resources'].append(dict(path='3d-assets/blobs/'+target.name,sha256=digest));write(asset/'asset.json',newdescriptor)
write(out/'proof.json',dict(status='Private transfer; native/oblique rendered proof required before publication',source_model_sha256=sha(source/'model.glb'),source_descriptor_sha256=sha(source/'asset.json'),output_model_sha256=sha(asset/'model.glb'),output_descriptor_sha256=sha(asset/'asset.json'),source_domain_sha256=sha(domainpath),source_pixels=len(source_hits),atlas_texels=int(mask.sum()),atlas_sha256=digest,geometry_buffers_exact=True,all_other_nodes_materials_exact=True,gameplay_and_part_metadata_exact=newdescriptor['gameplay']==descriptor['gameplay'] and newdescriptor['parts']==descriptor['parts'],all_decoded_rgb_exact=True,outside_domain_rgba_exact=True,scope='Only building017 receives a separate alpha-masked atlas.46approved Tree03 source pixel cells transferred; native017geometry/collision and every other material remain exact.'))
print(out)
