"""Pin scoped York appearance and channel approvals for private integration work."""
import hashlib,json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[3];W=ROOT/'level-editor/work/york-refinement/restart2';O=W/'restart40-approved-integration-v1';assert not O.exists();sha=lambda p:hashlib.sha256(Path(p).read_bytes()).hexdigest();R=ROOT/'level-editor/work/croisement02-refinement/restart3-review-batches/next-six-textures-channels-v1/user-approval.json';assert sha(R)=='7f6abc55fa21eee6ebd3b10c4f079e91e7f8159127a30a23fb9a6955d52e3f9d';a=json.loads(R.read_text());assert a['user_text']=='all approved';members=[m for m in a['decisions']if m['asset_id'].startswith('york-')];assert len(members)==3;pins={str(R):sha(R)}
for m in members:
 assert sha(m['model'])==m['model_sha256'];pins[m['model']]=m['model_sha256']
 if m['scope']=='texture':
  b=Path(m['model']).parent;h=json.loads((b/'grouped-review-handoff.json').read_text());item=h['items'][0];assert item['review_revision']==m['review_revision']
  for p,d in item['evidence'].items():assert sha(p)==d;pins[p]=d
 else:
  b=Path(m['model']).parent;v=json.loads((b/'validation.json').read_text());assert v['native_owner_material_uv_changes']==0 and len(v['contacts'])==45 and all(not r['crossings']for r in v['contacts']);pins[str(b/'validation.json')]=sha(b/'validation.json');pins[str(b/'saved-native-guard.json')]=sha(b/'saved-native-guard.json')
well=ROOT/'level-editor/library/3d-assets/york/york-market-roofed-stone-well';gate=ROOT/'level-editor/library/3d-assets/york/york-castle-west-gatehouse';live={str(p):sha(p)for d in (well,gate)for p in (d/'model.glb',d/'asset.json')};desc=json.loads((well/'asset.json').read_text());freeze=W/'winch-components-source-v2/component-freeze.json';pins[str(freeze)]=sha(freeze);f=json.loads(freeze.read_text());assert len(f['scope'])==24
plan={'status':'APPROVED_SCOPES_PRIVATE_PREPARATION_ONLY','receipt':{'path':str(R),'sha256':sha(R)},'approved_members':members,'pins':pins,'live_baseline':live,'operations':[
 {'asset_id':'york-market-roofed-stone-well','operation':'Replace only the seven asset-owned meshes with exact approved saved texture worker; preserve original source pivot and complete descriptor/gameplay metadata.','source_origin_scene':desc['source_origin_scene'],'existing_parts':desc['parts'],'candidate':next(m for m in members if m['asset_id']=='york-market-roofed-stone-well'),'requires':['Exact receiver mapping and existing canonical source ownership audit.','Private GLB roundtrip with protected UV/material preservation and derivative checks.','Root-only publication plus saved-map pin update and runtime verification.']},
 {'asset_id':'york-castle-winch-stable-components','operation':'Transfer only appearance onto the exact 24 approved components of a future private winch assembly. Preserve every component transform and approved source-frame44 geometry.','object_names':f['scope'],'candidate':next(m for m in members if m['asset_id']=='york-castle-winch-stable-components'),'must_not_infer':['Approval of chain, inferred return hardware, room, audio, complete mechanism, motion or runtime.','Authority to publish a complete winch from this 24-component appearance approval.'],'requires':['Exact named-component material/UV transfer proof to current assembly.','Separate pending mechanism/motion/state approvals and native parity before runtime publication.']},
 {'asset_id':'york-castle-west-gatehouse','operation':'Replace only approved structural volumes778/779 channel geometry; retain previously approved gate/jamb and every other gatehouse part.','candidate':next(m for m in members if m['scope']=='geometry'),'texture_scope':'Exactly eight new gray channel-interior faces, four each in building-778 and building-779. Existing materials/images and all other faces must remain exact.','requires':['Generate input packet from exact approved geometry with native camera top-left and fixed lighting.','Protect all existing material appearance; editable domain limited to eight gray interior faces.','Provide nearby gatehouse masonry material examples because channels have no observed source detail.','Self-review generated material then exact scoped bake and grouped user appearance approval.','Repeat full45pose clearance and native union source audit after private assembly.']}], 'canonical_mutations':False,'exports_created':False}
O.mkdir();(O/'integration-plan.json').write_text(json.dumps(plan,indent=2)+'\n');print(O,sha(O/'integration-plan.json'),len(pins))
