"""Partition only approved gray channel interiors for a private unknown-only packet."""
import hashlib,json,shutil,sys
from pathlib import Path
ROOT=Path(__file__).resolve().parents[3];W=ROOT/'level-editor/work/york-refinement/restart2';O=W/'restart41-channel-texture-inputs-v1';assert not O.exists();sha=lambda p:hashlib.sha256(Path(p).read_bytes()).hexdigest();receipt=ROOT/'level-editor/work/croisement02-refinement/restart3-review-batches/next-six-textures-channels-v1/user-approval.json';assert sha(receipt)=='7f6abc55fa21eee6ebd3b10c4f079e91e7f8159127a30a23fb9a6955d52e3f9d';member=next(m for m in json.loads(receipt.read_text())['decisions']if m['scope']=='geometry');source=Path(member['model']);assert sha(source)==member['model_sha256']
assert shutil.disk_usage(ROOT).free>10*1024**3
assert int(next(x.split()[1]for x in Path('/proc/meminfo').read_text().splitlines()if x.startswith('MemAvailable:')))*1024>6*1024**3
sys.path[:0]=[str(ROOT/'level-editor/refinement'),str(ROOT/'level-editor/refinement/blender')]
from render_slots import acquire
acquire(slots=2)
import bpy,bmesh
from PIL import Image
from refinement_workspace import _geometry
from refinement_review import render_review
bpy.ops.wm.open_mainfile(filepath=str(source));scene=bpy.context.scene;scene.render.threads_mode='FIXED';scene.render.threads=2;bpy.context.view_layer.update();asset='york-castle-west-gatehouse--guide-interiors';targets=[o for o in scene.objects if o.type=='MESH'and o.get('source_node')in('building-778','building-779')and any(m and m.name=='Unknown new guide-channel interior'for m in o.data.materials)];assert len(targets)==2;outside={o.name:_geometry(o,protect_appearance=True)for o in scene.objects if o not in targets};rows=[]
def face_signature(o,p):
 uv=o.data.uv_layers.active
 return {'xyz':[list(o.matrix_world@o.data.vertices[i].co)for i in p.vertices],'uv':[list(uv.data[i].uv)for i in p.loop_indices]if uv else [],'material':o.data.materials[p.material_index].name,'smooth':p.use_smooth}
for old in targets:
 faces=[p.index for p in old.data.polygons if old.data.materials[p.material_index].name=='Unknown new guide-channel interior'];assert len(faces)==4;original=[face_signature(old,p)for p in old.data.polygons];data=old.data.copy();new=bpy.data.objects.new(old.name+' / approved guide interiors',data);scene.collection.objects.link(new);new.matrix_world=old.matrix_world.copy()
 for k in old.keys():new[k]=old[k]
 new['asset_group']=asset;new['projection_component']='approved-guide-interiors';new['part_name']='Eight approved hidden guide faces';new['texture_scope']='Extracted exact approved faces, not changed geometry'
 bm=bmesh.new();bm.from_mesh(data);bm.faces.ensure_lookup_table();bmesh.ops.delete(bm,geom=[f for f in bm.faces if f.index not in faces],context='FACES');bm.to_mesh(data);bm.free();data.update()
 bm=bmesh.new();bm.from_mesh(old.data);bm.faces.ensure_lookup_table();bmesh.ops.delete(bm,geom=[f for f in bm.faces if f.index in faces],context='FACES');bm.to_mesh(old.data);bm.free();old.data.update()
 split=[face_signature(old,p)for p in old.data.polygons]+[face_signature(new,p)for p in new.data.polygons];canonical=lambda rows:sorted(json.dumps(r,sort_keys=True)for r in rows);assert canonical(original)==canonical(split),'Face partition changed coordinates, UV, material or winding';rows.append({'source_node':old['source_node'],'original_object':old.name,'derived_object':new.name,'original_face_indices':faces,'face_records':[original[i]for i in faces],'all_faces_union_exact':True})
assert outside=={o.name:_geometry(o,protect_appearance=True)for o in scene.objects if o.name in outside};O.mkdir();collection=bpy.data.collections.new('Approved channel texture context');scene.collection.children.link(collection)
for o in scene.objects:
 if o.type=='MESH':collection.objects.link(o)
Image.new('L',(1,1),0).save(O/'empty-native-domain.png');source_image=ROOT/'level-editor/work/york-refinement/baseline/covered.png';inventory={'version':1,'index_namespace':'Approved hidden interiors have no source-visible domain','masks':[{'index':0,'kind':'authored-artwork-domain','box_top_left':[0,0],'box_size':[1,1],'png':'empty-native-domain.png'}]};(O/'inventory.json').write_text(json.dumps(inventory,indent=2)+'\n');authority={'approved_receipt':str(receipt),'sha256':sha(receipt),'approved_model_sha256':sha(source),'scope':'Only eight new hidden faces; known source domain is empty, not inferred from color. Existing walls, gate, jamb and all other faces remain excluded from synthesis.','partition':rows};(O/'authority.json').write_text(json.dumps(authority,indent=2)+'\n');label='hidden-channel-interiors';manifest={'version':1,'mask_inventory':str(O/'inventory.json'),'projections':{label:{'source_sha256':sha(source_image),'state':'Approved static hidden channel interiors','assignments':[{'reviewed':True,'asset_group':asset,'mask_indices':[0],'review_evidence':str(O/'authority.json')}]}}};(O/'source-masks.json').write_text(json.dumps(manifest,indent=2)+'\n');bpy.context.preferences.filepaths.save_version=0;bpy.ops.wm.save_as_mainfile(filepath=str(O/'model.blend'),compress=True);before={o.name:_geometry(o,protect_appearance=True)for o in scene.objects};names=[r['derived_object']for r in rows]
render_review(O/'modified',scene_name=scene.name,collection_name=collection.name,asset_id=asset,source_path=source_image,width=320,height=384,source_mask_manifest=O/'source-masks.json',projection_layers=[{'source_path':str(source_image),'projection_label':label,'receiver_nodes':['building-778','building-779'],'occluder_nodes':sorted({o.get('source_node')for o in collection.objects if o.get('source_node')})}],render_object_names=names)
assert before=={o.name:_geometry(o,protect_appearance=True)for o in scene.objects if o.name in before};v=json.loads((O/'modified/views.json').read_text());assert all(x['counts']['source']==0 for x in v['views']);(O/'input-review.json').write_text(json.dumps({'status':'PRIVATE_INPUT_REQUIRES_VISUAL_REVIEW','approved_scope':member,'receipt_sha256':sha(receipt),'derived_model_sha256':sha(O/'model.blend'),'render_asset':asset,'object_names':names,'face_partition_union_exact':True,'source_counts':[x['counts']['source']for x in v['views']],'source_pixel_policy':'All unknown; material references mandatory. Existing walls are protected context and are not texture receivers.','synthesis':'Not requested','final_transfer_policy':'Transfer generated appearance only to original eight face indices; all other geometry, UV, material bindings and images stay exact.'},indent=2)+'\n');assert sha(source)==member['model_sha256'];print(O)
