"""Validate York generation provenance and local source protection before private baking."""
import hashlib,json,sys
from pathlib import Path
import numpy as np
from PIL import Image
ROOT=Path(__file__).resolve().parents[3];key=sys.argv[1];assert key in ('storehouse','well','stable24');E=ROOT/'level-editor/work/york-refinement/restart2/approved-texture-inputs-v1'/key/(sys.argv[2]if len(sys.argv)>2 else 'experiment');G=E/'generation-short-no-mask-with-lighting-openrouter-with-auxiliary';C=Path(json.loads((G/'generation.json').read_text())['cache']);sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
approval=json.loads((E/'approval.json').read_text());request=json.loads((C/'request.json').read_text());generation=json.loads((G/'generation.json').read_text());aux=json.loads((E/'auxiliary-references.json').read_text())
assert request['input_sha256']==approval['input_sha256']==sha(E/'input.png')==sha(C/'input.png');assert request['lighting_sha256']==approval['solid_sha256']==sha(E/'solid.png')==sha(C/'lighting.png');assert sha(E/'mask.png')==sha(C/'mask.png');assert request['parameters']['prompt']==generation['prompt'];assert request['parameters']['size']=='1280x768';assert request['parameters']['model']==generation['model']=='openai/gpt-image-2.5-sunburst';assert generation['status']==200;assert generation['cache']==str(C);assert generation['auxiliary_references']==request['auxiliary_references'];assert sha(E/'auxiliary-references.json')==request['auxiliary_references']['manifest_sha256'];assert aux['references']==request['auxiliary_references']['references']
for i,r in enumerate(aux['references']):assert sha(Path(r['file']))==r['sha256']==sha(C/f'auxiliary-{i}.png')
arrays={}
for k,p in [('input',E/'input.png'),('mask',E/'mask.png'),('raw',G/'generated-raw.png'),('preserved',G/'generated-preserved.png')]:
 im=Image.open(p);assert im.format=='PNG'and im.size==(1280,768);arrays[k]=np.asarray(im.convert('RGBA'))
protected=arrays['mask'][:,:,3]>0;editable=~protected;changed=np.any(arrays['input']!=arrays['preserved'],axis=2);assert not np.any(changed&protected);assert int(editable.sum())==generation['filled'];assert np.array_equal(arrays['preserved'][editable,:3],arrays['raw'][editable,:3]);assert sha(E/'approved-model.blend')==approval['saved_model_sha256']
receipt=ROOT/'level-editor/work/croisement02-refinement/restart3-review-batches/pending-v17-v23-plus-two-hub-v1/user-approval.json';assert sha(receipt)=='ca25ba9362b26dfb8ac1239f7acd7b56929463498b125bed0f42dcd98ec628f4'
clean_storehouse=key=='storehouse' and E.name=='retry-material-regions-v3'
if clean_storehouse:
 assert 'four-sided HIP roof' in request['parameters']['prompt'] and len(aux['references'])==2 and aux['references'][1]['source']=='region-guide'
report={'status':'PASS_PRIVATE_BAKE_CANDIDATE' if clean_storehouse else ('HOLD_ROOF_MATERIAL_MISCLASSIFICATION' if E.name!='experiment' else 'HOLD_NEW_ARCHITECTURAL_FEATURES') if key=='storehouse' else 'PASS_PRIVATE_BAKE_CANDIDATE','asset_id':approval['asset_id'],'bake_authorized':key!='storehouse' or clean_storehouse,'user_texture_approval':'PENDING','generated_raw_sha256':sha(G/'generated-raw.png'),'generated_preserved_sha256':sha(G/'generated-preserved.png'),'input_sha256':sha(E/'input.png'),'request_sha256':sha(C/'request.json'),'generation_sha256':sha(G/'generation.json'),'independent_protected_pixel_changes':int((changed&protected).sum()),'editable_pixels':int(editable.sum()),'dimensions':[1280,768],'exact_request_and_references_verified':True,'visual_review':['All eight raw and preserved views inspected. Hidden walls are blank masonry without invented openings; all sloping roof planes, including top-right triangular hip, retain roof tiles. Correct material guide verified in request.'] if clean_storehouse else ({'storehouse':(['HOLD: top-right view 3 paints an approved sloping hip-roof triangle as stone masonry, inconsistent with the tile roof in other views. No extra rear openings remain, but this material assignment changes the perceived architecture.'] if E.name!='experiment' else ['HOLD: generated rear walls add unsupported painted windows/slits in views 2–5. Exact local protection passes, but these architectural features violate the requested scope.']), 'well':['All eight raw and preserved views inspected; hollow stone ring, wood posts and pail retained. Existing source roof/wall projection stretch remains protected and is not generated detail. Hidden inner stones and timber are consistent enough for saved-model review.'], 'stable24':['All eight raw and preserved views inspected. Warm timber fill retains all 24 components and detached round part. Source orange facets remain locally protected; hidden wood is finer than source and requires saved-model seam review.']}[key]),'scope':'Permits private bake/self-review only; manual generation completion is not final texture approval.'};(G/'generation-review.json').write_text(json.dumps(report,indent=2)+'\n');print(json.dumps({k:report[k]for k in ['status','independent_protected_pixel_changes','editable_pixels','dimensions']}))
