"""Freeze a geometry-only riverside shed card for the next grouped review."""
import sys,json,hashlib,os
from pathlib import Path
ROOT=Path(__file__).resolve().parents[3];sys.path[:0]=[str(ROOT/'level-editor/refinement/blender')]
from build_review_gallery import build
B=ROOT/'level-editor/work/york-refinement';D=B/'restart7-riverside-shed-v2';F=B/'restart7-riverside-shed-frozen-v1'
def sha(p):return hashlib.sha256(Path(p).read_bytes()).hexdigest()
def write(p,v):p.write_text(json.dumps(v,indent=2)+'\n')
def main():
 digest='28e68eaaca4c8fe81d04c2ac7064fcde03d5137fdcc791a182d946e8258e91a5';assert sha(D/'model.blend')==digest;F.mkdir(exist_ok=False);os.link(D/'model.blend',F/'model.blend')
 receipt=dict(status='PASS scoped geometry by root coordinator',model_sha256=digest,viewed=['native-first actual8','native-first solid8','native source comparison','exact context contact4'],findings='Native lean-to roof/wall silhouette and shallow plank relief follow artwork; base/junction contact coherent. Unknown backs remain gray, texture pending. Five source boundary first-hit exceptions disclosed.',guards={f:sha(D/f)for f in ['construction.json','review.json','source-guard.json','self-review.json']},geometry_user_approved=False,texture_approved=False,publication=False);write(F/'root-review.json',receipt)
 item=dict(id='york-riverside-storehouse-timber-shed',name='York riverside storehouse timber shed',status='ready-for-user',technical_eligible=True,model=str(F/'model.blend'),solid=str(D/'review/solid-eight.png'),textured=str(D/'review/actual-eight.png'),context=str(D/'review/source-comparison.png'),source_comparison=str(D/'review/source-comparison.png'),source_comparison_label='Native artwork and saved geometry in exact storehouse/street context',validation=str(D/'review.json'),ownership=str(D/'source-guard.json'),review=str(F/'root-review.json'),notes='Closed wall and lean-to roof volumes replace a disconnected source proxy. Shallow plank relief follows this shed’s artwork. All31 parts are closed; foot clearance to exact raised street is less than0.00073worldunit. Native mask1 first-hit coverage6586/6591; three isolated eave edge centers hit ground and two warehouse junction centers hit storehouse. Native sourceRGB/mask retained. Hidden rear/underside and small boundary rims remain gray pending texture fill. Storehouse and raised street are unchanged context, not part of this geometry decision.',approval_scope='Exact shed geometry only, with source-facing appearance for inspection. No generated texture, new source ownership, state or publication decision.',animation_reviews=[dict(id='shed-context',name='Storehouse and raised street contacts',description='Unmodified neighbor/terrain in four physical views; native camera first.',textured=str(D/'review/contact-four.png'),solid=str(D/'review/solid-eight.png'),context=str(D/'review/source-comparison.png'))])
 write(F/'review-candidates.json',dict(map='York',review_kind='geometry',scope='Next grouped batch after pendingV17; no individual question.',items=[item]));build(F/'review-candidates.json',F/'gallery');write(F/'freeze-receipt.json',dict(status='Frozen next-pool geometry card',model_sha256=digest,files={str(p.relative_to(F)):sha(p)for p in F.rglob('*')if p.is_file()},user_approved=False,publication=False));print(F/'gallery/index.html')
if __name__=='__main__':main()
