"""Bind already granted exact York geometry scopes to reviewed texture preparation."""
import hashlib,json,sys
from pathlib import Path
ROOT=Path(__file__).resolve().parents[3];WORK=ROOT/'level-editor/work/york-refinement/restart2';worker=WORK/'approved-texture-inputs-v1'/sys.argv[1];sha=lambda p:hashlib.sha256(Path(p).read_bytes()).hexdigest()
report=json.loads((worker/'input-review.json').read_text());member=report['approved_scope'];asset=report['render_asset'];assert json.loads((worker/'visual-input-review.json').read_text())['status']=='PASS';assert report['geometry_uv_materials_preserved'];receipt=ROOT/'level-editor/work/croisement02-refinement/restart3-review-batches/pending-v17-v23-plus-two-hub-v1/user-approval.json';assert sha(receipt)==report['receipt_sha256'];user=json.loads(receipt.read_text());assert sha(worker/'model.blend')==member['model_sha256']
frames=json.loads((worker/'modified/views.json').read_text());lighting=worker/'preparation-lighting.json';lighting.write_text(json.dumps({'lighting':frames['lighting']},indent=2)+'\n')
evidence={str(p.relative_to(worker)):{'path':str(p.resolve()),'sha256':sha(p)}for p in sorted(worker.rglob('*'))if p.is_file()};evidence['user-approval']={'path':str(receipt),'sha256':sha(receipt)}
identity={'asset_id':asset,'model_sha256':member['model_sha256'],'evidence':{k:v['sha256']for k,v in evidence.items()}};revision=hashlib.sha256(json.dumps(identity,sort_keys=True,separators=(',',':')).encode()).hexdigest();translation='Exact user-approved '+member['asset_id']+' scope; new source-owned preparation changes no geometry, UV or stored material. Exact receiver names are pinned in input-review.json. Dependent fill permitted; final appearance unapproved.'
item={'id':asset,'workspace':str(worker.resolve()),'status':'ready-for-user','stored_material_validation':'PASS','solid':str(worker/'modified/solid.png'),'textured':str(worker/'modified/textured.png'),'revision':{'sha256':revision,'model_sha256':member['model_sha256'],'evidence':evidence},'derive_unknown_lighting':True,'solid_view_paths':[str(worker/'modified/views'/f'view-{i}-solid.png')for i in range(8)],'preparation_lighting':{'config':str(lighting),'lighting':frames['lighting']},'approval_provenance':{'receipt':str(receipt),'sha256':sha(receipt),'exact_user_text':user['user_message'],'original_review_revision':member.get('review_revision'),'translation':translation}}
decision={'asset_id':asset,'scope':'geometry','decision':'approved','exact_user_text':user['user_message'],'revision_sha256':revision,'source_user_receipt':str(receipt),'translation':translation}
manifest=worker/'review-manifest.json';decisions=worker/'decisions.json';manifest.write_text(json.dumps({'version':1,'items':[item]},indent=2)+'\n');decisions.write_text(json.dumps({'version':1,'decisions':[decision]},indent=2)+'\n');sys.path.insert(0,str(ROOT/'level-editor/refinement'))
from prepare_texture_packet import prepare
print(json.dumps(prepare(manifest,asset,worker/'experiment',decisions),indent=2))
