"""Choose minimal hidden motion and audit recipe-derived gate/jamb contact envelopes."""
import hashlib,json,math
from pathlib import Path
from shapely.geometry import Polygon,box
ROOT=Path(__file__).resolve().parents[3];WORK=ROOT/'level-editor/work/york-refinement/restart2';OUT=WORK/'gate-motion-proposal-v2';assert not OUT.exists();c=math.cos(math.radians(35));s=math.sin(math.radians(35));prior=WORK/'gate-crossbar-tracking-v1/motion-proposal.json';proposal=json.loads(prior.read_text());rows=proposal['rows'];row36=rows[36];assert rows[35]['nominal_lift_source_pixels']==rows[37]['nominal_lift_source_pixels']==57;row36.update(nominal_lift_source_pixels=57,nominal_lift_world_z=57/c,confidence='INFERRED: minimal-change pose equals both neighboring nominal57pixel lifts; lies inside57..65 uncertainty interval. Not an observed displacement.');assert all(0<=r['nominal_lift_source_pixels']<=57 for r in rows)
# Reconstruct only the approved recipe's planar physical contact envelope.
# This does not claim to have reopened or extracted the saved float32 mesh.
x0,x1=2336.8003,2377.6338;length=math.hypot(x1-x0,(1053.655-1012.82166)/s);factor=length/(x1-x0);floor=90.00101/c;top=floor+62/c
geo=json.loads((WORK/'gate-geometry-v10/geometry-proposal.json').read_text());profile=geo['scoped_gatehouse_correction']['profile_game_xz'];jamb=Polygon([((x-x0)*factor,z/c)for x,z in profile]);assert jamb.is_valid
pieces=[]
for i,x in enumerate([x0]+[2339.9+j*4.5 for j in range(9)]+[x1]):
 u=(x-x0)*factor;pieces.append({'part':f'upright-{i}','umin':u-2.3/2,'umax':u+2.3/2,'zmin':floor,'zmax':top,'normal_depth_overlap':1.05})
for i in range(6):
 z=floor+(8.5+i*9.5)/c;pieces.append({'part':f'crossbar-{i}','umin':0,'umax':length,'zmin':z-3.5/2,'zmax':z+3.5/2,'normal_depth_overlap':1.0})
audit=[]
for row in rows:
 dz=row['nominal_lift_world_z'];contacts=[]
 for p in pieces:
  region=box(p['umin'],p['zmin']+dz,p['umax'],p['zmax']+dz).intersection(jamb)
  if region.area>1e-8:contacts.append({'part':p['part'],'section_overlap_area':region.area,'depth_overlap':p['normal_depth_overlap'],'envelope_overlap_volume':region.area*p['normal_depth_overlap']})
 audit.append({'frame':row['frame'],'lift_source_pixels':row['nominal_lift_source_pixels'],'floor_clearance':dz,'jamb_overlap_envelopes':contacts,'total_overlap_volume':sum(r['envelope_overlap_volume']for r in contacts)})
proposal.update(status='PRIVATE_INFERRED_MOTION_READY_FOR_RENDERED_VALIDATION',conclusion='Frame36 uses57pixel inferred lift, continuous with neighboring nominal poses; no65pixel physical overshoot claimed.',remaining=['Validate saved-mesh contacts and native appearance with exact gatehouse context in later model lane.','Review intermediate poses as inferred mechanics separately from native frame playback.']);proposal['rows']=rows;proposal['native_playback']={'frames':45,'frame_delay':1,'reset_counter':65535,'completion_update':90,'sound_owner':'Existing native presentation; sound361 on frame0 only','native_rgba':'Untouched; proposed mechanical pose does not replace or retime source playback'}
report={'status':'CPU_RECIPE_ENVELOPE_AUDIT_NOT_SAVED_MESH_PROOF','recipe':str(ROOT/'level-editor/blender/york/restart2_gate_geometry.py'),'recipe_sha256':hashlib.sha256((ROOT/'level-editor/blender/york/restart2_gate_geometry.py').read_bytes()).hexdigest(),'jamb_profile_evidence':str(WORK/'gate-geometry-v10/geometry-proposal.json'),'rows':audit,'conclusions':['All45poses retain identical horizontal gate/jamb relationship and stay in the approved0..57endpoint travel envelope.','No inferred floor penetration; minimum lift0 at initial pose.','Recipe envelopes overlap jamb depth already at both approved endpoints; do not report collision-free motion. These may represent guide/recess embedment but require exact saved-mesh/context inspection.','No additional57..65overshoot envelope introduced at the unobservable frame36.'],'minimum_overlap_volume':min(r['total_overlap_volume']for r in audit),'maximum_overlap_volume':max(r['total_overlap_volume']for r in audit)}
spec={'status':'READY_SPEC_PENDING_RENDER_LANE','scope':'Gate intermediate mechanical poses only; native timing/art untouched. Frame36 explicitly inferred.','views':['Original art camera always first; all45native-source versus model poses','Eight solid and textured views at0,22,34,36,38,44','Close-up jamb/guide/crown contacts at maximum envelope overlap and both endpoints'],'required_guards':['Exact approved endpoint vertices preserved','Gatehouse/jamb/terrain meshes unchanged','No worldclock or newaudio emitter','Audit actual triangle intersections and identify existing guide embedment separately from newly introduced penetration','Retain frame36inferred label on every relevant card'],'one_grouped_motion_card':True,'native_parity_claim':'Only source playback/timing unchanged; hidden pose is an inferred mechanical completion, not exact recovered history.'};OUT.mkdir();(OUT/'motion.json').write_text(json.dumps(proposal,indent=2)+'\n');(OUT/'contact-audit.json').write_text(json.dumps(report,indent=2)+'\n');(OUT/'review-specification.json').write_text(json.dumps(spec,indent=2)+'\n');print(json.dumps({'out':str(OUT),'frames':len(rows),'frame36_lift':57,'minimum_overlap_volume':report['minimum_overlap_volume'],'maximum_overlap_volume':report['maximum_overlap_volume']}))
