"""Freeze gate endpoint approvals and native transition evidence for private staging."""
import hashlib,json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[3];WORK=ROOT/'level-editor/work/york-refinement';OUT=WORK/'restart2/gate-state-inventory-v1/report.json'
if OUT.exists():raise FileExistsError(OUT)
sha=lambda p:hashlib.sha256(Path(p).read_bytes()).hexdigest();source=WORK/'geometry-pass-01/native-state-source-v1';manifest=json.loads((source/'manifest.json').read_text());record=next(r for r in manifest['records']if r['id']=='patch-000');initial=next(r['frames']for r in record['rows']if r['action']=='PatchInitial');frames=next(r['frames']for r in record['rows']if r['action']=='PatchTransition');assert len(initial)==1 and len(frames)==45 and not any(r['action']=='PatchFinal'for r in record['rows'])
for f in initial+frames:assert sha(source/f['image'])==f['sha256'];assert f['delay']==1
assert frames[0]['sound_id']==361 and all(f['sound_id']==0 for f in frames[1:])
rows=[{'frame':i,'sample_tick':2*i,'bbox':f['bbox'],'bottom_pixel_exclusive':f['bbox'][1]+f['bbox'][3],'source':str(source/f['image']),'sha256':f['sha256'],'sound_id':f['sound_id']}for i,f in enumerate(frames)]
verified=json.loads((WORK/'restart2/newly-approved-scopes-v1/verified.json').read_text());members=[m for m in verified['members']if m['asset_id'].startswith('york-castle-portcullis--')]
for m in members:assert sha(m['model'])==m['model_sha256']
assert len(members)==2
report={'status':'PRIVATE_ENDPOINT_APPROVAL_AND_MOTION_SOURCE_INVENTORY','patch':'patch-000','source_manifest_sha256':sha(source/'manifest.json'),'approved_endpoint_appearances':members,'approval_receipt_sha256':verified['receipt_sha256'],'native_frames':rows,'timing':{'initial':'One visible initial frame','transition_frames':45,'frame_delay':1,'reset_counter':65535,'inclusive_counter_period_updates':2,'completion_update':90,'final':'Transition44 persists in background after dynamic FX stops; no final row','sound':{'id':361,'source_frame':0,'existing_presentation_owner_only':True}},'source_observation':{'initial_visible_height':71,'smallest_visible_height':6,'minimum_frame':36,'settled_visible_height':14,'nonmonotonic_tail':[r['bbox'][3]for r in rows[34:]],'implication':'A uniform linear57pixel endpoint translation does not reproduce the late visible overshoot/settling. Pixel extent alone does not prove whole-mesh displacement; track a retained crossbar before authoring motion.'},'independence':'Gate000, winch004 and room cover005 require separate authoritative state snapshots; do not synchronize by wall clock.','door_indices':record['record']['door_indices'],'pending':['Track native crossbar/source features through all45frames to distinguish movement from occlusion/art changes.','Prepare private intermediate pose proposal only after source tracking; endpoint approval does not approve unseen interpolation.','Preserve existing door/patch behavior and audio; no new emitter or second clock.'],'runtime_or_library_writes':False};OUT.parent.mkdir();OUT.write_text(json.dumps(report,indent=2)+'\n');print(json.dumps({'path':str(OUT),'frames':len(rows),'minimum_visible_frame':36,'tail':report['source_observation']['nonmonotonic_tail']}))
