"""Validate the exact narrow-channel generation before a private scoped bake."""
import hashlib,json
from pathlib import Path
import numpy as np
from PIL import Image
ROOT=Path(__file__).resolve().parents[3];E=ROOT/'level-editor/work/york-refinement/restart2/restart41-channel-texture-inputs-v1/experiment';G=E/'generation-short-no-mask-with-lighting-openrouter-with-auxiliary';sha=lambda p:hashlib.sha256(Path(p).read_bytes()).hexdigest();a=json.loads((E/'approval.json').read_text());g=json.loads((G/'generation.json').read_text());c=Path(g['cache']);r=json.loads((c/'request.json').read_text());aux=json.loads((E/'auxiliary-references.json').read_text());assert g['status']==200 and g['model']=='openai/gpt-image-2.5-sunburst';assert r['input_sha256']==a['input_sha256']==sha(E/'input.png')==sha(c/'input.png');assert r['lighting_sha256']==a['solid_sha256']==sha(E/'solid.png')==sha(c/'lighting.png');assert sha(E/'mask.png')==sha(c/'mask.png');assert r['parameters']['size']=='1280x768'and r['parameters']['prompt']==g['prompt'];assert r['auxiliary_references']==g['auxiliary_references'];assert sha(E/'auxiliary-references.json')==r['auxiliary_references']['manifest_sha256'];assert aux['references']==r['auxiliary_references']['references']
for i,x in enumerate(aux['references']):assert sha(x['file'])==x['sha256']==sha(c/f'auxiliary-{i}.png')
arrays={}
for k,p in [('input',E/'input.png'),('mask',E/'mask.png'),('raw',G/'generated-raw.png'),('preserved',G/'generated-preserved.png')]:
 im=Image.open(p);assert im.format=='PNG'and im.size==(1280,768);arrays[k]=np.asarray(im.convert('RGBA'))
protected=arrays['mask'][:,:,3]>0;edited=~protected;changed=np.any(arrays['input']!=arrays['preserved'],axis=2);assert not np.any(changed&protected);assert np.array_equal(arrays['preserved'][edited,:3],arrays['raw'][edited,:3]);assert np.array_equal(arrays['input'][:,:,3],arrays['preserved'][:,:,3]);assert int(edited.sum())==g['filled']==29401;assert sha(E/'approved-model.blend')==a['saved_model_sha256'];report={'status':'PASS_FOR_PRIVATE_SCOPED_BAKE','bake_authorized':True,'user_texture_approval':'PENDING','asset_id':a['asset_id'],'model_sha256':sha(E/'approved-model.blend'),'generated_raw_sha256':sha(G/'generated-raw.png'),'generated_preserved_sha256':sha(G/'generated-preserved.png'),'request_sha256':sha(c/'request.json'),'generation_sha256':sha(G/'generation.json'),'dimensions':[1280,768],'editable_pixels':29401,'protected_rgba_changed':0,'alpha_changed':0,'visual_review':['All eight raw and preserved views inspected. Narrow strips contain restrained olive-gray masonry courses and retain exact positions/widths.','No gate, wood, doorway or reference-object layout copied into editable strips.','Sparse sheet cannot establish appearance in assembled channels; exact face-only transfer and saved assembly review required.']};(G/'generation-review.json').write_text(json.dumps(report,indent=2)+'\n');print(report['status'])
