"""Independently bind manually completed shed generation to approved inputs."""
import hashlib,json
from pathlib import Path
import numpy as np
from PIL import Image
ROOT=Path(__file__).resolve().parents[3];E=ROOT/'level-editor/work/york-refinement/restart2/approved-texture-inputs-v1/shed/experiment';G=E/'generation-short-no-mask-with-lighting-openrouter-with-auxiliary';C=E/'api-cache/77b7aff3f87c1200c09bddbbafbbb352b6f9d53555071b21ce3d7d6dd449178d';sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
approval=json.loads((E/'approval.json').read_text());request=json.loads((C/'request.json').read_text());generation=json.loads((G/'generation.json').read_text());aux=json.loads((E/'auxiliary-references.json').read_text())
assert request['input_sha256']==approval['input_sha256']==sha(E/'input.png')==sha(C/'input.png');assert request['lighting_sha256']==approval['solid_sha256']==sha(E/'solid.png')==sha(C/'lighting.png');assert sha(E/'mask.png')==sha(C/'mask.png');assert request['parameters']['prompt']==generation['prompt'];assert request['parameters']['size']=='1280x768';assert request['parameters']['model']==generation['model']=='openai/gpt-image-2.5-sunburst';assert generation['status']==200;assert generation['cache']==str(C);assert generation['auxiliary_references']==request['auxiliary_references'];assert sha(E/'auxiliary-references.json')==request['auxiliary_references']['manifest_sha256'];assert aux['references']==request['auxiliary_references']['references']
for i,r in enumerate(aux['references']):assert sha(Path(r['file']))==r['sha256']==sha(C/f'auxiliary-{i}.png')
arrays={}
for k,p in [('input',E/'input.png'),('mask',E/'mask.png'),('raw',G/'generated-raw.png'),('preserved',G/'generated-preserved.png')]:
 im=Image.open(p);assert im.format=='PNG'and im.size==(1280,768);arrays[k]=np.asarray(im.convert('RGBA'))
protected=arrays['mask'][:,:,3]>0;editable=~protected;changed=np.any(arrays['input']!=arrays['preserved'],axis=2);assert not np.any(changed&protected);assert int(editable.sum())==generation['filled']==308266;assert np.array_equal(arrays['preserved'][editable,:3],arrays['raw'][editable,:3]);assert sha(E/'approved-model.blend')==approval['saved_model_sha256']
report={'status':'PASS_PRIVATE_BAKE_CANDIDATE','asset_id':approval['asset_id'],'bake_authorized':True,'user_texture_approval':'PENDING','generated_raw_sha256':sha(G/'generated-raw.png'),'generated_preserved_sha256':sha(G/'generated-preserved.png'),'input_sha256':sha(E/'input.png'),'request_sha256':sha(C/'request.json'),'generation_sha256':sha(G/'generation.json'),'independent_protected_pixel_changes':int((changed&protected).sum()),'editable_pixels':int(editable.sum()),'dimensions':[1280,768],'exact_request_and_references_verified':True,'visual_review':['All eight preserved views inspected. Hidden walls consistently use dark weathered vertical wood boards; no new openings or masonry.','Native front and roof are locally preserved despite raw model repainting.','Generated wood is finer than native source pixels; inspect saved-model transition and side lighting after bake.'],'scope':'Permits private bake/self-review only; manual generation completion is not final texture approval.'};(G/'generation-review.json').write_text(json.dumps(report,indent=2)+'\n');print(json.dumps({k:report[k]for k in ['status','independent_protected_pixel_changes','editable_pixels','dimensions']}))
