"""Freeze saved shed appearance evidence for a grouped user texture decision."""
import hashlib,json
from pathlib import Path
from PIL import Image,ImageDraw
ROOT=Path(__file__).resolve().parents[3];WORK=ROOT/'level-editor/work/york-refinement/restart2';B=WORK/'shed-texture-baked-v1';E=WORK/'approved-texture-inputs-v1/shed/experiment';G=E/'generation-short-no-mask-with-lighting-openrouter-with-auxiliary';sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
validation=json.loads((B/'validation.json').read_text());assert sha(B/'model.blend')==validation['baked_model_sha256'];assert validation['geometry_verified']and not validation['geometry_changed'];assert json.loads((G/'generation-review.json').read_text())['independent_protected_pixel_changes']==0
before=Image.open(E.parent/'modified/views/view-0-textured.png').convert('RGBA');after=Image.open(B/'actual/view-0-textured.png').convert('RGBA');assert before.size==after.size;w,h=before.size;sheet=Image.new('RGB',(w*2,h+25),(35,40,45));sheet.paste(before,(0,25),before);sheet.paste(after,(w,25),after);d=ImageDraw.Draw(sheet);d.text((5,5),'Original-camera source / unknown',fill='white');d.text((w+5,5),'Saved source-preserving texture bake',fill='white');sheet.save(B/'actual/native-before-after.png')
review={'status':'PASS_FOR_ROOT_GROUPED_REVIEW','model_sha256':sha(B/'model.blend'),'viewed':['actual/textured-eight.png','actual/native-before-after.png'],'findings':['Viewed all eight actual saved-model views; original art camera top-left.','Generated hidden walls read as weathered vertical boards, coherent with the retained source front and roof.','No gray patches apparent on the eight displayed exposed views; thin seams blend acceptably.','Generated wall grain is finer than native source pixels; this difference remains visible near source-to-inferred transitions.'],'limits':['Source blue-gray edge colors are retained, not synthesized repairs.','Unfilled atlas counts include padding and hidden surfaces; no claim that every underside texel is filled.','No texture approval, runtime integration or canonical publication yet.'],'protected_source':'Independent sheet RGBA check zero differences; bake checks protected source atlas texels byte-identical','context':'Ten outside objects verified unchanged before being excluded from this scoped worker'};(B/'self-review.json').write_text(json.dumps(review,indent=2)+'\n')
images=[('Saved model: eight views, original camera first',B/'actual/textured-eight.png'),('Native camera: source-only before and saved texture after',B/'actual/native-before-after.png')];paths=[B/'model.blend',B/'validation.json',B/'self-review.json',G/'generation-review.json',E/'approval.json']+[p for _,p in images];evidence={str(p):sha(p)for p in paths};asset='york-riverside-storehouse-timber-shed';identity={'asset_id':asset,'model_sha256':sha(B/'model.blend'),'evidence':evidence};revision=hashlib.sha256(json.dumps(identity,sort_keys=True,separators=(',',':')).encode()).hexdigest();item={'asset_id':asset,'canonical_asset_id':asset,'model':str(B/'model.blend'),'model_sha256':sha(B/'model.blend'),'review_revision':revision,'scope':'texture','scope_description':'Saved shed texture appearance only; exact approved geometry retained. No surrounding storehouse, terrain or runtime scope.','decision':'pending','evidence':evidence,'displayed_images':[{'label':label,'file':str(p),'source':str(p),'sha256':sha(p)}for label,p in images],'notes':review['findings']+review['limits']};(B/'grouped-review-handoff.json').write_text(json.dumps({'status':'Worker reviewed; root review then grouped user decision pending','cards':[{'card_id':'york-riverside-storehouse-timber-shed-texture','title':'York riverside timber shed texture','asset_ids':[asset]}],'items':[item]},indent=2)+'\n');print(json.dumps({'model_sha256':sha(B/'model.blend'),'revision':revision,'bytes':sum(p.stat().st_size for p in B.rglob('*')if p.is_file())}))
