//! Port-owned Feature 40 catalogue.
//!
//! Retail resource tables cannot provide strings for a feature added by this
//! port. Keep one complete, compile-time catalogue for every locale the
//! shipping-datadir importer accepts. Array order is the public
//! `FEATURE40_PORT_TEXT_KEYS` order; tests in `localization.rs` enforce full
//! coverage and identical named-placeholder contracts in every language.

use super::{FEATURE40_PORT_TEXT_KEYS, PortTextKey, normalize_locale};

const TEXT_COUNT: usize = 70;

pub(super) fn text(locale: &str, key: PortTextKey) -> Option<&'static str> {
    let normalized = normalize_locale(locale);
    let table = match normalized.as_str() {
        "en" | "en-us" | "und" => &EN,
        "de" | "de-de" => &DE,
        "fr" | "fr-fr" => &FR,
        "it" | "it-it" => &IT,
        "pt" | "pt-pt" => &PT,
        "pt-br" => &PT_BR,
        "es" | "es-es" => &ES,
        "ru" | "ru-ru" => &RU,
        "ja" | "ja-jp" => &JA,
        "cs" | "cs-cz" => &CS,
        "pl" | "pl-pl" => &PL,
        "zh" | "zh-tw" => &ZH_TW,
        "zh-cn" => &ZH_CN,
        "ko" | "ko-kr" => &KO,
        "th" | "th-th" => &TH,
        _ => return None,
    };
    FEATURE40_PORT_TEXT_KEYS
        .iter()
        .position(|candidate| *candidate == key)
        .map(|index| table[index])
}

const EN: [&str; TEXT_COUNT] = [
    "Allow Spellforge Missions (Next Launch)",
    "Allow exact, explicitly trusted Spellforge packages to run on the next launch.",
    "Manage Spellforge Content...",
    "Host & Attest",
    "Distribute Complete Mod?",
    "No author licence metadata; your click records a host redistribution attestation.",
    "Host {host} attests permission to redistribute `{title}` from {source} for this multiplayer session",
    "Mission: {value}",
    "Claimed author: {value}",
    "Version: {value}",
    "Source: {value}",
    "Licence: {value}",
    "Authenticated host key: {value}",
    "Players receive the complete Lua/map/art/audio/text mod before joining.",
    "Only choose Host & Attest if redistribution is authorised.",
    "Trust Exact Mod",
    "Trust Host Content?",
    "Vanilla (no Lua package)",
    "Licence/permission: {value}",
    "Distributor key: {value}",
    "Download: {bytes} bytes",
    "Full-mod SHA-256:",
    "Lua package SHA-256:",
    "This mod contains executable mission code. Approval is for these exact hashes only.",
    "This complete map/art/audio/text mod is approved only for this exact hash.",
    "Host content requires Spellforge, but Allow Spellforge Missions is disabled in Gameplay settings.",
    "Approval was not persisted: {error}",
    "Previous",
    "Next",
    "Revoke All",
    "Clear Cache",
    "Reset Trust",
    "Revoke [{hash}]: {title}",
    "Revoked {count} exact-content approvals.",
    "Revocation failed: {error}",
    "Removed {count} cached full mods.",
    "Cache clear failed: {error}",
    "Trust store reset; every host mod will prompt again.",
    "Trust reset failed: {error}",
    "Revoked approval for {title}.",
    "Approval was already absent.",
    "Spellforge Content",
    "Exact approvals for this player - page {page}/{pages}",
    "No host-distributed content is approved.",
    "Started custom game lost its prepared host content.",
    "Cannot verify prepared custom-game content: {error}",
    "Started custom game content differs from the prepared package.",
    "Rejected changed multiplayer start: {error}",
    "Hosting custom content was cancelled.",
    "Cannot review custom mission metadata: {error}",
    "Cannot host custom mission: {error}",
    "Cannot advertise custom mission: {error}",
    "Creating custom game...",
    "Browser builds can join but cannot host custom content.",
    "Connect direct browser invite: {error}",
    "Direct browser invite transport closed during handshake.",
    "Timed out resolving direct browser invite.",
    "Joining direct custom content was cancelled.",
    "Direct invite did not expose a mission.",
    "Direct host selected vanilla mission `{mission}`, which is absent from this browser data.",
    "Direct browser invites are only available in browser builds.",
    "Timed out confirming no-seat host-content preflight.",
    "Host-content preflight transport closed unexpectedly.",
    "Connect for host-content review: {error}",
    "Host advertised custom content but sent an ordinary Welcome.",
    "Timed out awaiting authenticated host-content offer.",
    "Authenticated host offered content {actual} which differs from lobby advertisement {advertised}.",
    "Joining custom content was cancelled.",
    "Timed out confirming host-content preflight.",
    "[Mod] {title} - {version}",
];

const DE: [&str; TEXT_COUNT] = [
    "Spellforge-Missionen zulassen (beim nächsten Start)",
    "Exakt passende, ausdrücklich vertrauenswürdige Spellforge-Pakete beim nächsten Start ausführen.",
    "Spellforge-Inhalte verwalten...",
    "Hosten & bestätigen",
    "Vollständige Mod verteilen?",
    "Keine Lizenzangaben des Autors; dein Klick bestätigt als Host die Erlaubnis zur Weiterverteilung.",
    "Host {host} bestätigt die Erlaubnis, `{title}` aus {source} für diese Mehrspielersitzung weiterzuverteilen",
    "Mission: {value}",
    "Angegebener Autor: {value}",
    "Version: {value}",
    "Quelle: {value}",
    "Lizenz: {value}",
    "Authentifizierter Host-Schlüssel: {value}",
    "Spieler erhalten vor dem Beitritt die vollständige Lua-/Karten-/Grafik-/Audio-/Text-Mod.",
    "Nur Hosten & bestätigen wählen, wenn die Weiterverteilung erlaubt ist.",
    "Exakter Mod vertrauen",
    "Host-Inhalt vertrauen?",
    "Original (kein Lua-Paket)",
    "Lizenz/Berechtigung: {value}",
    "Verteilerschlüssel: {value}",
    "Download: {bytes} Byte",
    "SHA-256 der vollständigen Mod:",
    "SHA-256 des Lua-Pakets:",
    "Diese Mod enthält ausführbaren Missionscode. Die Zustimmung gilt nur für diese exakten Hashes.",
    "Diese vollständige Karten-/Grafik-/Audio-/Text-Mod ist nur für diesen exakten Hash zugelassen.",
    "Der Host-Inhalt benötigt Spellforge, aber Spellforge-Missionen zulassen ist in den Gameplay-Einstellungen deaktiviert.",
    "Zustimmung wurde nicht gespeichert: {error}",
    "Zurück",
    "Weiter",
    "Alle widerrufen",
    "Cache leeren",
    "Vertrauen zurücksetzen",
    "Widerrufen [{hash}]: {title}",
    "{count} Zustimmungen für exakte Inhalte widerrufen.",
    "Widerruf fehlgeschlagen: {error}",
    "{count} vollständige Mods aus dem Cache entfernt.",
    "Leeren des Caches fehlgeschlagen: {error}",
    "Vertrauensspeicher zurückgesetzt; jede Host-Mod fragt erneut nach.",
    "Zurücksetzen des Vertrauens fehlgeschlagen: {error}",
    "Zustimmung für {title} widerrufen.",
    "Die Zustimmung war bereits nicht vorhanden.",
    "Spellforge-Inhalte",
    "Exakte Zustimmungen dieses Spielers - Seite {page}/{pages}",
    "Keine vom Host verteilten Inhalte sind zugelassen.",
    "Das gestartete benutzerdefinierte Spiel hat seinen vorbereiteten Host-Inhalt verloren.",
    "Vorbereiteten Inhalt des benutzerdefinierten Spiels nicht überprüfbar: {error}",
    "Der Inhalt des gestarteten benutzerdefinierten Spiels weicht vom vorbereiteten Paket ab.",
    "Geänderten Mehrspielerstart abgelehnt: {error}",
    "Hosten benutzerdefinierter Inhalte wurde abgebrochen.",
    "Metadaten der benutzerdefinierten Mission nicht überprüfbar: {error}",
    "Benutzerdefinierte Mission kann nicht gehostet werden: {error}",
    "Benutzerdefinierte Mission kann nicht angekündigt werden: {error}",
    "Benutzerdefiniertes Spiel wird erstellt...",
    "Browser-Versionen können beitreten, aber keine benutzerdefinierten Inhalte hosten.",
    "Direkte Browser-Einladung verbinden: {error}",
    "Transport der direkten Browser-Einladung wurde beim Handshake geschlossen.",
    "Zeitüberschreitung beim Auflösen der direkten Browser-Einladung.",
    "Beitritt zu direkten benutzerdefinierten Inhalten wurde abgebrochen.",
    "Die direkte Einladung enthielt keine Mission.",
    "Der direkte Host wählte die Originalmission `{mission}`, die in diesen Browser-Daten fehlt.",
    "Direkte Browser-Einladungen sind nur in Browser-Versionen verfügbar.",
    "Zeitüberschreitung bei der Bestätigung der Host-Inhaltsprüfung ohne Sitzplatz.",
    "Transport der Host-Inhaltsprüfung wurde unerwartet geschlossen.",
    "Zur Prüfung des Host-Inhalts verbinden: {error}",
    "Der Host kündigte benutzerdefinierte Inhalte an, sendete aber ein normales Welcome.",
    "Zeitüberschreitung beim Warten auf das authentifizierte Host-Inhaltsangebot.",
    "Der authentifizierte Host bot Inhalt {actual} an, abweichend von der Lobby-Ankündigung {advertised}.",
    "Beitritt zu benutzerdefinierten Inhalten wurde abgebrochen.",
    "Zeitüberschreitung bei der Bestätigung der Host-Inhaltsprüfung.",
    "[Mod] {title} - {version}",
];

const FR: [&str; TEXT_COUNT] = [
    "Autoriser les missions Spellforge (prochain lancement)",
    "Autoriser l'exécution, au prochain lancement, des paquets Spellforge exacts et explicitement approuvés.",
    "Gérer le contenu Spellforge...",
    "Héberger et attester",
    "Distribuer le mod complet ?",
    "Aucune licence fournie par l'auteur ; votre clic enregistre l'attestation de redistribution de l'hôte.",
    "L'hôte {host} atteste être autorisé à redistribuer `{title}` depuis {source} pour cette session multijoueur",
    "Mission : {value}",
    "Auteur déclaré : {value}",
    "Version : {value}",
    "Source : {value}",
    "Licence : {value}",
    "Clé d'hôte authentifiée : {value}",
    "Les joueurs reçoivent le mod Lua/carte/graphismes/audio/textes complet avant de rejoindre.",
    "Ne choisissez Héberger et attester que si la redistribution est autorisée.",
    "Approuver le mod exact",
    "Approuver le contenu de l'hôte ?",
    "Jeu d'origine (aucun paquet Lua)",
    "Licence/autorisation : {value}",
    "Clé du distributeur : {value}",
    "Téléchargement : {bytes} octets",
    "SHA-256 du mod complet :",
    "SHA-256 du paquet Lua :",
    "Ce mod contient du code de mission exécutable. L'approbation ne vaut que pour ces empreintes exactes.",
    "Ce mod complet de carte/graphismes/audio/textes n'est approuvé que pour cette empreinte exacte.",
    "Le contenu de l'hôte nécessite Spellforge, mais Autoriser les missions Spellforge est désactivé dans les paramètres de jeu.",
    "L'approbation n'a pas été enregistrée : {error}",
    "Précédent",
    "Suivant",
    "Tout révoquer",
    "Vider le cache",
    "Réinitialiser la confiance",
    "Révoquer [{hash}] : {title}",
    "{count} approbations de contenu exact révoquées.",
    "Échec de la révocation : {error}",
    "{count} mods complets supprimés du cache.",
    "Échec du vidage du cache : {error}",
    "Registre de confiance réinitialisé ; chaque mod d'hôte demandera une nouvelle approbation.",
    "Échec de la réinitialisation de la confiance : {error}",
    "Approbation de {title} révoquée.",
    "L'approbation était déjà absente.",
    "Contenu Spellforge",
    "Approbations exactes de ce joueur - page {page}/{pages}",
    "Aucun contenu distribué par un hôte n'est approuvé.",
    "La partie personnalisée lancée a perdu son contenu d'hôte préparé.",
    "Impossible de vérifier le contenu préparé de la partie personnalisée : {error}",
    "Le contenu de la partie personnalisée lancée diffère du paquet préparé.",
    "Démarrage multijoueur modifié refusé : {error}",
    "L'hébergement du contenu personnalisé a été annulé.",
    "Impossible d'examiner les métadonnées de la mission personnalisée : {error}",
    "Impossible d'héberger la mission personnalisée : {error}",
    "Impossible d'annoncer la mission personnalisée : {error}",
    "Création de la partie personnalisée...",
    "Les versions navigateur peuvent rejoindre, mais pas héberger de contenu personnalisé.",
    "Connexion à l'invitation directe du navigateur : {error}",
    "Le transport de l'invitation directe du navigateur s'est fermé pendant la négociation.",
    "Délai dépassé lors de la résolution de l'invitation directe du navigateur.",
    "La connexion directe au contenu personnalisé a été annulée.",
    "L'invitation directe n'a indiqué aucune mission.",
    "L'hôte direct a choisi la mission d'origine `{mission}`, absente de ces données navigateur.",
    "Les invitations directes du navigateur ne sont disponibles que dans les versions navigateur.",
    "Délai dépassé lors de la vérification préalable du contenu de l'hôte sans réserver de place.",
    "Le transport de vérification préalable du contenu de l'hôte s'est fermé inopinément.",
    "Connexion pour examiner le contenu de l'hôte : {error}",
    "L'hôte a annoncé du contenu personnalisé, mais a envoyé un Welcome ordinaire.",
    "Délai dépassé dans l'attente de l'offre authentifiée de contenu de l'hôte.",
    "L'hôte authentifié a proposé le contenu {actual}, différent de l'annonce du salon {advertised}.",
    "La connexion au contenu personnalisé a été annulée.",
    "Délai dépassé lors de la vérification préalable du contenu de l'hôte.",
    "[Mod] {title} - {version}",
];

const IT: [&str; TEXT_COUNT] = [
    "Consenti missioni Spellforge (prossimo avvio)",
    "Consenti l'esecuzione, al prossimo avvio, dei pacchetti Spellforge esatti e approvati esplicitamente.",
    "Gestisci contenuti Spellforge...",
    "Ospita e attesta",
    "Distribuire il mod completo?",
    "Nessun dato di licenza dell'autore; il clic registra l'attestazione di ridistribuzione dell'host.",
    "L'host {host} attesta il permesso di ridistribuire `{title}` da {source} per questa sessione multigiocatore",
    "Missione: {value}",
    "Autore dichiarato: {value}",
    "Versione: {value}",
    "Fonte: {value}",
    "Licenza: {value}",
    "Chiave host autenticata: {value}",
    "Prima di entrare, i giocatori ricevono il mod Lua/mappa/grafica/audio/testo completo.",
    "Scegli Ospita e attesta solo se la ridistribuzione è autorizzata.",
    "Considera attendibile il mod esatto",
    "Considerare attendibile il contenuto dell'host?",
    "Originale (nessun pacchetto Lua)",
    "Licenza/permesso: {value}",
    "Chiave del distributore: {value}",
    "Download: {bytes} byte",
    "SHA-256 del mod completo:",
    "SHA-256 del pacchetto Lua:",
    "Questo mod contiene codice di missione eseguibile. L'approvazione vale solo per questi hash esatti.",
    "Questo mod completo di mappa/grafica/audio/testo è approvato solo per questo hash esatto.",
    "Il contenuto dell'host richiede Spellforge, ma Consenti missioni Spellforge è disattivato nelle impostazioni di gioco.",
    "L'approvazione non è stata salvata: {error}",
    "Precedente",
    "Successivo",
    "Revoca tutto",
    "Svuota cache",
    "Reimposta attendibilità",
    "Revoca [{hash}]: {title}",
    "Revocate {count} approvazioni di contenuto esatto.",
    "Revoca non riuscita: {error}",
    "Rimossi {count} mod completi dalla cache.",
    "Svuotamento cache non riuscito: {error}",
    "Archivio di attendibilità reimpostato; ogni mod dell'host richiederà nuovamente conferma.",
    "Reimpostazione attendibilità non riuscita: {error}",
    "Revocata l'approvazione per {title}.",
    "L'approvazione era già assente.",
    "Contenuti Spellforge",
    "Approvazioni esatte per questo giocatore - pagina {page}/{pages}",
    "Nessun contenuto distribuito dall'host è approvato.",
    "La partita personalizzata avviata ha perso il contenuto host preparato.",
    "Impossibile verificare il contenuto preparato della partita personalizzata: {error}",
    "Il contenuto della partita personalizzata avviata è diverso dal pacchetto preparato.",
    "Avvio multigiocatore modificato rifiutato: {error}",
    "L'hosting del contenuto personalizzato è stato annullato.",
    "Impossibile esaminare i metadati della missione personalizzata: {error}",
    "Impossibile ospitare la missione personalizzata: {error}",
    "Impossibile pubblicizzare la missione personalizzata: {error}",
    "Creazione della partita personalizzata...",
    "Le versioni browser possono entrare, ma non ospitare contenuti personalizzati.",
    "Connessione all'invito diretto del browser: {error}",
    "Il trasporto dell'invito diretto del browser si è chiuso durante l'handshake.",
    "Tempo scaduto durante la risoluzione dell'invito diretto del browser.",
    "L'accesso diretto al contenuto personalizzato è stato annullato.",
    "L'invito diretto non ha indicato una missione.",
    "L'host diretto ha scelto la missione originale `{mission}`, assente nei dati del browser.",
    "Gli inviti diretti del browser sono disponibili solo nelle versioni browser.",
    "Tempo scaduto durante la verifica preliminare senza occupare un posto del contenuto host.",
    "Il trasporto della verifica preliminare del contenuto host si è chiuso in modo imprevisto.",
    "Connessione per esaminare il contenuto host: {error}",
    "L'host ha annunciato contenuto personalizzato, ma ha inviato un Welcome normale.",
    "Tempo scaduto in attesa dell'offerta autenticata del contenuto host.",
    "L'host autenticato ha offerto il contenuto {actual}, diverso dall'annuncio della lobby {advertised}.",
    "L'accesso al contenuto personalizzato è stato annullato.",
    "Tempo scaduto durante la verifica preliminare del contenuto host.",
    "[Mod] {title} - {version}",
];

const PT: [&str; TEXT_COUNT] = [
    "Permitir missões Spellforge (próximo arranque)",
    "Permitir que pacotes Spellforge exatos e explicitamente aprovados sejam executados no próximo arranque.",
    "Gerir conteúdo Spellforge...",
    "Alojar e atestar",
    "Distribuir o mod completo?",
    "Sem dados de licença do autor; o clique regista o atestado de redistribuição do anfitrião.",
    "O anfitrião {host} atesta ter permissão para redistribuir `{title}` de {source} nesta sessão multijogador",
    "Missão: {value}",
    "Autor declarado: {value}",
    "Versão: {value}",
    "Origem: {value}",
    "Licença: {value}",
    "Chave autenticada do anfitrião: {value}",
    "Os jogadores recebem o mod Lua/mapa/gráficos/áudio/texto completo antes de entrar.",
    "Escolha Alojar e atestar apenas se a redistribuição estiver autorizada.",
    "Confiar no mod exato",
    "Confiar no conteúdo do anfitrião?",
    "Original (sem pacote Lua)",
    "Licença/permissão: {value}",
    "Chave do distribuidor: {value}",
    "Transferência: {bytes} bytes",
    "SHA-256 do mod completo:",
    "SHA-256 do pacote Lua:",
    "Este mod contém código de missão executável. A aprovação aplica-se apenas a estes hashes exatos.",
    "Este mod completo de mapa/gráficos/áudio/texto está aprovado apenas para este hash exato.",
    "O conteúdo do anfitrião requer Spellforge, mas Permitir missões Spellforge está desativado nas definições de jogabilidade.",
    "A aprovação não foi guardada: {error}",
    "Anterior",
    "Seguinte",
    "Revogar tudo",
    "Limpar cache",
    "Repor confiança",
    "Revogar [{hash}]: {title}",
    "Foram revogadas {count} aprovações de conteúdo exato.",
    "Falha ao revogar: {error}",
    "Foram removidos {count} mods completos da cache.",
    "Falha ao limpar a cache: {error}",
    "Armazenamento de confiança reposto; cada mod do anfitrião voltará a pedir confirmação.",
    "Falha ao repor a confiança: {error}",
    "Aprovação de {title} revogada.",
    "A aprovação já não existia.",
    "Conteúdo Spellforge",
    "Aprovações exatas deste jogador - página {page}/{pages}",
    "Nenhum conteúdo distribuído pelo anfitrião está aprovado.",
    "O jogo personalizado iniciado perdeu o conteúdo preparado do anfitrião.",
    "Não é possível verificar o conteúdo preparado do jogo personalizado: {error}",
    "O conteúdo do jogo personalizado iniciado difere do pacote preparado.",
    "Início multijogador alterado rejeitado: {error}",
    "O alojamento de conteúdo personalizado foi cancelado.",
    "Não é possível rever os metadados da missão personalizada: {error}",
    "Não é possível alojar a missão personalizada: {error}",
    "Não é possível anunciar a missão personalizada: {error}",
    "A criar jogo personalizado...",
    "As versões para navegador podem entrar, mas não alojar conteúdo personalizado.",
    "Ligar ao convite direto do navegador: {error}",
    "O transporte do convite direto do navegador fechou durante a negociação.",
    "Tempo esgotado ao resolver o convite direto do navegador.",
    "A entrada direta em conteúdo personalizado foi cancelada.",
    "O convite direto não indicou uma missão.",
    "O anfitrião direto escolheu a missão original `{mission}`, ausente destes dados do navegador.",
    "Os convites diretos do navegador só estão disponíveis nas versões para navegador.",
    "Tempo esgotado ao confirmar a pré-verificação sem lugar do conteúdo do anfitrião.",
    "O transporte da pré-verificação do conteúdo do anfitrião fechou inesperadamente.",
    "Ligar para rever o conteúdo do anfitrião: {error}",
    "O anfitrião anunciou conteúdo personalizado, mas enviou um Welcome normal.",
    "Tempo esgotado à espera da oferta autenticada de conteúdo do anfitrião.",
    "O anfitrião autenticado ofereceu o conteúdo {actual}, diferente do anúncio da sala {advertised}.",
    "A entrada em conteúdo personalizado foi cancelada.",
    "Tempo esgotado ao confirmar a pré-verificação do conteúdo do anfitrião.",
    "[Mod] {title} - {version}",
];

const PT_BR: [&str; TEXT_COUNT] = [
    "Permitir missões Spellforge (próxima inicialização)",
    "Permitir que pacotes Spellforge exatos e explicitamente aprovados sejam executados na próxima inicialização.",
    "Gerenciar conteúdo Spellforge...",
    "Hospedar e atestar",
    "Distribuir o mod completo?",
    "Sem dados de licença do autor; seu clique registra a declaração de redistribuição do host.",
    "O host {host} declara ter permissão para redistribuir `{title}` de {source} nesta sessão multijogador",
    "Missão: {value}",
    "Autor declarado: {value}",
    "Versão: {value}",
    "Origem: {value}",
    "Licença: {value}",
    "Chave autenticada do host: {value}",
    "Os jogadores recebem o mod completo de Lua/mapa/gráficos/áudio/texto antes de entrar.",
    "Escolha Hospedar e atestar somente se a redistribuição estiver autorizada.",
    "Confiar no mod exato",
    "Confiar no conteúdo do host?",
    "Original (sem pacote Lua)",
    "Licença/permissão: {value}",
    "Chave do distribuidor: {value}",
    "Download: {bytes} bytes",
    "SHA-256 do mod completo:",
    "SHA-256 do pacote Lua:",
    "Este mod contém código de missão executável. A aprovação vale somente para estes hashes exatos.",
    "Este mod completo de mapa/gráficos/áudio/texto está aprovado somente para este hash exato.",
    "O conteúdo do host requer Spellforge, mas Permitir missões Spellforge está desativado nas configurações de jogabilidade.",
    "A aprovação não foi salva: {error}",
    "Anterior",
    "Próximo",
    "Revogar tudo",
    "Limpar cache",
    "Redefinir confiança",
    "Revogar [{hash}]: {title}",
    "Foram revogadas {count} aprovações de conteúdo exato.",
    "Falha ao revogar: {error}",
    "Foram removidos {count} mods completos do cache.",
    "Falha ao limpar o cache: {error}",
    "Armazenamento de confiança redefinido; cada mod do host solicitará aprovação novamente.",
    "Falha ao redefinir a confiança: {error}",
    "Aprovação de {title} revogada.",
    "A aprovação já não existia.",
    "Conteúdo Spellforge",
    "Aprovações exatas deste jogador - página {page}/{pages}",
    "Nenhum conteúdo distribuído pelo host está aprovado.",
    "A partida personalizada iniciada perdeu o conteúdo preparado do host.",
    "Não foi possível verificar o conteúdo preparado da partida personalizada: {error}",
    "O conteúdo da partida personalizada iniciada é diferente do pacote preparado.",
    "Início multijogador alterado rejeitado: {error}",
    "A hospedagem de conteúdo personalizado foi cancelada.",
    "Não foi possível revisar os metadados da missão personalizada: {error}",
    "Não foi possível hospedar a missão personalizada: {error}",
    "Não foi possível anunciar a missão personalizada: {error}",
    "Criando partida personalizada...",
    "As versões para navegador podem entrar, mas não podem hospedar conteúdo personalizado.",
    "Conectar ao convite direto do navegador: {error}",
    "O transporte do convite direto do navegador foi fechado durante a negociação.",
    "Tempo esgotado ao resolver o convite direto do navegador.",
    "A entrada direta em conteúdo personalizado foi cancelada.",
    "O convite direto não indicou uma missão.",
    "O host direto escolheu a missão original `{mission}`, que não está presente nos dados deste navegador.",
    "Os convites diretos do navegador estão disponíveis somente nas versões para navegador.",
    "Tempo esgotado ao confirmar a pré-verificação sem vaga do conteúdo do host.",
    "O transporte da pré-verificação do conteúdo do host foi fechado inesperadamente.",
    "Conectar para revisar o conteúdo do host: {error}",
    "O host anunciou conteúdo personalizado, mas enviou um Welcome comum.",
    "Tempo esgotado ao aguardar a oferta autenticada de conteúdo do host.",
    "O host autenticado ofereceu o conteúdo {actual}, diferente do anúncio da sala {advertised}.",
    "A entrada em conteúdo personalizado foi cancelada.",
    "Tempo esgotado ao confirmar a pré-verificação do conteúdo do host.",
    "[Mod] {title} - {version}",
];

const ES: [&str; TEXT_COUNT] = [
    "Permitir misiones Spellforge (próximo inicio)",
    "Permitir que los paquetes Spellforge exactos y aprobados explícitamente se ejecuten en el próximo inicio.",
    "Gestionar contenido Spellforge...",
    "Alojar y certificar",
    "¿Distribuir el mod completo?",
    "No hay datos de licencia del autor; tu clic registra la certificación de redistribución del anfitrión.",
    "El anfitrión {host} certifica que tiene permiso para redistribuir `{title}` desde {source} en esta sesión multijugador",
    "Misión: {value}",
    "Autor declarado: {value}",
    "Versión: {value}",
    "Origen: {value}",
    "Licencia: {value}",
    "Clave autenticada del anfitrión: {value}",
    "Los jugadores reciben el mod completo de Lua/mapa/gráficos/audio/texto antes de unirse.",
    "Elige Alojar y certificar solo si la redistribución está autorizada.",
    "Confiar en el mod exacto",
    "¿Confiar en el contenido del anfitrión?",
    "Original (sin paquete Lua)",
    "Licencia/permiso: {value}",
    "Clave del distribuidor: {value}",
    "Descarga: {bytes} bytes",
    "SHA-256 del mod completo:",
    "SHA-256 del paquete Lua:",
    "Este mod contiene código de misión ejecutable. La aprobación solo se aplica a estos hashes exactos.",
    "Este mod completo de mapa/gráficos/audio/texto solo está aprobado para este hash exacto.",
    "El contenido del anfitrión requiere Spellforge, pero Permitir misiones Spellforge está desactivado en los ajustes de jugabilidad.",
    "La aprobación no se guardó: {error}",
    "Anterior",
    "Siguiente",
    "Revocar todo",
    "Vaciar caché",
    "Restablecer confianza",
    "Revocar [{hash}]: {title}",
    "Se revocaron {count} aprobaciones de contenido exacto.",
    "Error al revocar: {error}",
    "Se eliminaron {count} mods completos de la caché.",
    "Error al vaciar la caché: {error}",
    "Almacén de confianza restablecido; cada mod del anfitrión volverá a solicitar aprobación.",
    "Error al restablecer la confianza: {error}",
    "Se revocó la aprobación de {title}.",
    "La aprobación ya no existía.",
    "Contenido Spellforge",
    "Aprobaciones exactas de este jugador - página {page}/{pages}",
    "No hay contenido distribuido por anfitriones aprobado.",
    "La partida personalizada iniciada perdió el contenido preparado del anfitrión.",
    "No se puede verificar el contenido preparado de la partida personalizada: {error}",
    "El contenido de la partida personalizada iniciada difiere del paquete preparado.",
    "Se rechazó el inicio multijugador modificado: {error}",
    "Se canceló el alojamiento del contenido personalizado.",
    "No se pueden revisar los metadatos de la misión personalizada: {error}",
    "No se puede alojar la misión personalizada: {error}",
    "No se puede anunciar la misión personalizada: {error}",
    "Creando partida personalizada...",
    "Las versiones para navegador pueden unirse, pero no alojar contenido personalizado.",
    "Conectar invitación directa del navegador: {error}",
    "El transporte de la invitación directa del navegador se cerró durante la negociación.",
    "Se agotó el tiempo al resolver la invitación directa del navegador.",
    "Se canceló la unión directa al contenido personalizado.",
    "La invitación directa no indicó ninguna misión.",
    "El anfitrión directo eligió la misión original `{mission}`, ausente en estos datos del navegador.",
    "Las invitaciones directas del navegador solo están disponibles en versiones para navegador.",
    "Se agotó el tiempo al confirmar la prevalidación sin plaza del contenido del anfitrión.",
    "El transporte de prevalidación del contenido del anfitrión se cerró inesperadamente.",
    "Conectar para revisar el contenido del anfitrión: {error}",
    "El anfitrión anunció contenido personalizado, pero envió un Welcome normal.",
    "Se agotó el tiempo esperando la oferta autenticada de contenido del anfitrión.",
    "El anfitrión autenticado ofreció el contenido {actual}, distinto del anuncio de la sala {advertised}.",
    "Se canceló la unión al contenido personalizado.",
    "Se agotó el tiempo al confirmar la prevalidación del contenido del anfitrión.",
    "[Mod] {title} - {version}",
];

const RU: [&str; TEXT_COUNT] = [
    "Разрешить миссии Spellforge (при следующем запуске)",
    "При следующем запуске разрешить выполнение только точных, явно одобренных пакетов Spellforge.",
    "Управление содержимым Spellforge...",
    "Разместить и подтвердить",
    "Распространить мод целиком?",
    "Данные о лицензии автора отсутствуют; нажатие сохранит подтверждение хоста о праве распространения.",
    "Хост {host} подтверждает право распространять `{title}` из {source} в этом сетевом сеансе",
    "Миссия: {value}",
    "Заявленный автор: {value}",
    "Версия: {value}",
    "Источник: {value}",
    "Лицензия: {value}",
    "Аутентифицированный ключ хоста: {value}",
    "Перед подключением игроки получают мод целиком: Lua, карту, графику, звук и текст.",
    "Выбирайте Разместить и подтвердить только при наличии права на распространение.",
    "Доверять точному моду",
    "Доверять содержимому хоста?",
    "Оригинал (без пакета Lua)",
    "Лицензия/разрешение: {value}",
    "Ключ распространителя: {value}",
    "Загрузка: {bytes} байт",
    "SHA-256 полного мода:",
    "SHA-256 пакета Lua:",
    "Этот мод содержит исполняемый код миссии. Одобрение действует только для этих точных хешей.",
    "Этот полный мод карты/графики/звука/текста одобрен только для этого точного хеша.",
    "Содержимому хоста требуется Spellforge, но Разрешить миссии Spellforge отключено в настройках игрового процесса.",
    "Не удалось сохранить одобрение: {error}",
    "Назад",
    "Далее",
    "Отозвать все",
    "Очистить кэш",
    "Сбросить доверие",
    "Отозвать [{hash}]: {title}",
    "Отозвано одобрений точного содержимого: {count}.",
    "Не удалось отозвать: {error}",
    "Удалено полных модов из кэша: {count}.",
    "Не удалось очистить кэш: {error}",
    "Хранилище доверия сброшено; каждый мод хоста снова запросит подтверждение.",
    "Не удалось сбросить доверие: {error}",
    "Одобрение для {title} отозвано.",
    "Одобрение уже отсутствовало.",
    "Содержимое Spellforge",
    "Точные одобрения этого игрока - страница {page}/{pages}",
    "Нет одобренного содержимого, распространяемого хостами.",
    "Запущенная пользовательская игра потеряла подготовленное содержимое хоста.",
    "Не удалось проверить подготовленное содержимое пользовательской игры: {error}",
    "Содержимое запущенной пользовательской игры отличается от подготовленного пакета.",
    "Изменённый запуск сетевой игры отклонён: {error}",
    "Размещение пользовательского содержимого отменено.",
    "Не удалось проверить метаданные пользовательской миссии: {error}",
    "Не удалось разместить пользовательскую миссию: {error}",
    "Не удалось объявить пользовательскую миссию: {error}",
    "Создание пользовательской игры...",
    "Версия для браузера может подключаться, но не может размещать пользовательское содержимое.",
    "Подключение по прямому приглашению браузера: {error}",
    "Транспорт прямого приглашения браузера закрылся во время рукопожатия.",
    "Истекло время разрешения прямого приглашения браузера.",
    "Прямое подключение к пользовательскому содержимому отменено.",
    "В прямом приглашении не указана миссия.",
    "Прямой хост выбрал оригинальную миссию `{mission}`, которой нет в данных браузера.",
    "Прямые приглашения браузера доступны только в версии для браузера.",
    "Истекло время подтверждения предварительной проверки содержимого хоста без занятия места.",
    "Транспорт предварительной проверки содержимого хоста неожиданно закрылся.",
    "Подключение для проверки содержимого хоста: {error}",
    "Хост объявил пользовательское содержимое, но отправил обычное сообщение Welcome.",
    "Истекло время ожидания аутентифицированного предложения содержимого хоста.",
    "Аутентифицированный хост предложил содержимое {actual}, отличающееся от объявления в комнате {advertised}.",
    "Подключение к пользовательскому содержимому отменено.",
    "Истекло время подтверждения предварительной проверки содержимого хоста.",
    "[Мод] {title} - {version}",
];

const JA: [&str; TEXT_COUNT] = [
    "Spellforge ミッションを許可（次回起動時）",
    "完全に一致し、明示的に信頼した Spellforge パッケージを次回起動時に実行できるようにします。",
    "Spellforge コンテンツを管理...",
    "ホストして権限を表明",
    "完全な Mod を配布しますか？",
    "作者のライセンス情報がありません。クリックすると、ホストによる再配布権限の表明が記録されます。",
    "ホスト {host} は、このマルチプレイセッションで {source} の `{title}` を再配布する権限があると表明します",
    "ミッション: {value}",
    "申告された作者: {value}",
    "バージョン: {value}",
    "配布元: {value}",
    "ライセンス: {value}",
    "認証済みホスト鍵: {value}",
    "参加前に Lua・マップ・画像・音声・テキストを含む完全な Mod がプレイヤーへ送られます。",
    "再配布が許可されている場合にのみ「ホストして権限を表明」を選んでください。",
    "完全一致する Mod を信頼",
    "ホストのコンテンツを信頼しますか？",
    "オリジナル（Lua パッケージなし）",
    "ライセンス/許可: {value}",
    "配布者の鍵: {value}",
    "ダウンロード: {bytes} バイト",
    "完全な Mod の SHA-256:",
    "Lua パッケージの SHA-256:",
    "この Mod には実行可能なミッションコードが含まれます。承認はこれらの完全一致するハッシュだけに有効です。",
    "この完全なマップ・画像・音声・テキスト Mod は、この完全一致するハッシュだけに承認されます。",
    "ホストのコンテンツには Spellforge が必要ですが、ゲームプレイ設定で Spellforge ミッションの許可が無効です。",
    "承認を保存できませんでした: {error}",
    "前へ",
    "次へ",
    "すべて取り消す",
    "キャッシュを消去",
    "信頼をリセット",
    "取り消す [{hash}]: {title}",
    "完全一致コンテンツの承認を {count} 件取り消しました。",
    "取り消しに失敗しました: {error}",
    "キャッシュ済みの完全な Mod を {count} 件削除しました。",
    "キャッシュの消去に失敗しました: {error}",
    "信頼ストアをリセットしました。すべてのホスト Mod で再び確認します。",
    "信頼のリセットに失敗しました: {error}",
    "{title} の承認を取り消しました。",
    "承認はすでに存在しません。",
    "Spellforge コンテンツ",
    "このプレイヤーの完全一致承認 - {page}/{pages} ページ",
    "ホスト配布コンテンツは何も承認されていません。",
    "開始済みのカスタムゲームで、準備済みホストコンテンツが失われました。",
    "準備済みカスタムゲームコンテンツを検証できません: {error}",
    "開始済みカスタムゲームのコンテンツが準備済みパッケージと異なります。",
    "変更されたマルチプレイ開始を拒否しました: {error}",
    "カスタムコンテンツのホストをキャンセルしました。",
    "カスタムミッションのメタデータを確認できません: {error}",
    "カスタムミッションをホストできません: {error}",
    "カスタムミッションを公開できません: {error}",
    "カスタムゲームを作成中...",
    "ブラウザ版は参加できますが、カスタムコンテンツをホストできません。",
    "ブラウザの直接招待に接続: {error}",
    "ハンドシェイク中にブラウザ直接招待の通信が閉じられました。",
    "ブラウザ直接招待の解決がタイムアウトしました。",
    "直接招待によるカスタムコンテンツへの参加をキャンセルしました。",
    "直接招待にミッションが含まれていません。",
    "直接接続先のホストがオリジナルミッション `{mission}` を選びましたが、このブラウザデータにはありません。",
    "ブラウザ直接招待はブラウザ版でのみ利用できます。",
    "席を確保しないホストコンテンツ事前検証の確認がタイムアウトしました。",
    "ホストコンテンツ事前検証の通信が予期せず閉じられました。",
    "ホストコンテンツの確認用接続: {error}",
    "ホストはカスタムコンテンツを通知しましたが、通常の Welcome を送信しました。",
    "認証済みホストコンテンツの提示待ちがタイムアウトしました。",
    "認証済みホストが提示したコンテンツ {actual} は、ロビーの告知 {advertised} と異なります。",
    "カスタムコンテンツへの参加をキャンセルしました。",
    "ホストコンテンツ事前検証の確認がタイムアウトしました。",
    "[Mod] {title} - {version}",
];

const CS: [&str; TEXT_COUNT] = [
    "Povolit mise Spellforge (při příštím spuštění)",
    "Při příštím spuštění povolit jen přesné a výslovně důvěryhodné balíčky Spellforge.",
    "Spravovat obsah Spellforge...",
    "Hostovat a potvrdit",
    "Distribuovat celý mod?",
    "Chybí licenční údaje autora; kliknutím uložíte potvrzení hostitele o právu k redistribuci.",
    "Hostitel {host} potvrzuje oprávnění redistribuovat `{title}` ze zdroje {source} pro tuto hru více hráčů",
    "Mise: {value}",
    "Uvedený autor: {value}",
    "Verze: {value}",
    "Zdroj: {value}",
    "Licence: {value}",
    "Ověřený klíč hostitele: {value}",
    "Hráči před připojením obdrží celý mod Lua/mapy/grafiky/zvuku/textu.",
    "Možnost Hostovat a potvrdit vyberte pouze tehdy, je-li redistribuce povolena.",
    "Důvěřovat přesnému modu",
    "Důvěřovat obsahu hostitele?",
    "Původní hra (bez balíčku Lua)",
    "Licence/oprávnění: {value}",
    "Klíč distributora: {value}",
    "Stahování: {bytes} bajtů",
    "SHA-256 celého modu:",
    "SHA-256 balíčku Lua:",
    "Tento mod obsahuje spustitelný kód mise. Schválení platí pouze pro tyto přesné hashe.",
    "Tento celý mod mapy/grafiky/zvuku/textu je schválen pouze pro tento přesný hash.",
    "Obsah hostitele vyžaduje Spellforge, ale Povolit mise Spellforge je v nastavení hry vypnuto.",
    "Schválení nebylo uloženo: {error}",
    "Předchozí",
    "Další",
    "Odvolat vše",
    "Vymazat mezipaměť",
    "Resetovat důvěru",
    "Odvolat [{hash}]: {title}",
    "Odvoláno {count} schválení přesného obsahu.",
    "Odvolání selhalo: {error}",
    "Z mezipaměti bylo odstraněno {count} celých modů.",
    "Vymazání mezipaměti selhalo: {error}",
    "Úložiště důvěry bylo resetováno; každý mod hostitele znovu požádá o potvrzení.",
    "Resetování důvěry selhalo: {error}",
    "Schválení pro {title} bylo odvoláno.",
    "Schválení již nebylo přítomno.",
    "Obsah Spellforge",
    "Přesná schválení tohoto hráče - strana {page}/{pages}",
    "Není schválen žádný obsah distribuovaný hostitelem.",
    "Spuštěná vlastní hra ztratila připravený obsah hostitele.",
    "Nelze ověřit připravený obsah vlastní hry: {error}",
    "Obsah spuštěné vlastní hry se liší od připraveného balíčku.",
    "Změněné spuštění hry více hráčů bylo odmítnuto: {error}",
    "Hostování vlastního obsahu bylo zrušeno.",
    "Nelze zkontrolovat metadata vlastní mise: {error}",
    "Nelze hostovat vlastní misi: {error}",
    "Nelze oznámit vlastní misi: {error}",
    "Vytváří se vlastní hra...",
    "Verze pro prohlížeč se mohou připojit, ale nemohou hostovat vlastní obsah.",
    "Připojení k přímé pozvánce prohlížeče: {error}",
    "Přenos přímé pozvánky prohlížeče se během navazování spojení uzavřel.",
    "Vypršel čas při zpracování přímé pozvánky prohlížeče.",
    "Přímé připojení k vlastnímu obsahu bylo zrušeno.",
    "Přímá pozvánka neobsahovala žádnou misi.",
    "Přímý hostitel vybral původní misi `{mission}`, která v datech prohlížeče chybí.",
    "Přímé pozvánky prohlížeče jsou dostupné pouze ve verzi pro prohlížeč.",
    "Vypršel čas při potvrzení předběžné kontroly obsahu hostitele bez obsazení místa.",
    "Přenos předběžné kontroly obsahu hostitele se neočekávaně uzavřel.",
    "Připojení ke kontrole obsahu hostitele: {error}",
    "Hostitel oznámil vlastní obsah, ale poslal běžnou zprávu Welcome.",
    "Vypršel čas při čekání na ověřenou nabídku obsahu hostitele.",
    "Ověřený hostitel nabídl obsah {actual}, který se liší od oznámení v lobby {advertised}.",
    "Připojení k vlastnímu obsahu bylo zrušeno.",
    "Vypršel čas při potvrzení předběžné kontroly obsahu hostitele.",
    "[Mod] {title} - {version}",
];

const PL: [&str; TEXT_COUNT] = [
    "Zezwalaj na misje Spellforge (następne uruchomienie)",
    "Przy następnym uruchomieniu zezwalaj tylko na dokładne, jawnie zaufane pakiety Spellforge.",
    "Zarządzaj zawartością Spellforge...",
    "Hostuj i potwierdź",
    "Rozpowszechnić cały mod?",
    "Brak danych licencyjnych autora; kliknięcie zapisze potwierdzenie hosta o prawie do rozpowszechniania.",
    "Host {host} potwierdza prawo do rozpowszechniania `{title}` ze źródła {source} w tej sesji wieloosobowej",
    "Misja: {value}",
    "Podany autor: {value}",
    "Wersja: {value}",
    "Źródło: {value}",
    "Licencja: {value}",
    "Uwierzytelniony klucz hosta: {value}",
    "Przed dołączeniem gracze otrzymują cały mod Lua/mapy/grafiki/dźwięku/tekstu.",
    "Wybierz Hostuj i potwierdź tylko wtedy, gdy rozpowszechnianie jest dozwolone.",
    "Zaufaj dokładnemu modowi",
    "Zaufać zawartości hosta?",
    "Oryginał (bez pakietu Lua)",
    "Licencja/zezwolenie: {value}",
    "Klucz dystrybutora: {value}",
    "Pobieranie: {bytes} bajtów",
    "SHA-256 całego moda:",
    "SHA-256 pakietu Lua:",
    "Ten mod zawiera wykonywalny kod misji. Zgoda dotyczy tylko tych dokładnych skrótów.",
    "Ten pełny mod mapy/grafiki/dźwięku/tekstu jest zatwierdzony tylko dla tego dokładnego skrótu.",
    "Zawartość hosta wymaga Spellforge, ale Zezwalaj na misje Spellforge jest wyłączone w ustawieniach rozgrywki.",
    "Zgoda nie została zapisana: {error}",
    "Poprzednia",
    "Następna",
    "Cofnij wszystkie zgody",
    "Wyczyść pamięć podręczną",
    "Zresetuj zaufanie",
    "Cofnij zgodę [{hash}]: {title}",
    "Cofnięto {count} zgód na dokładną zawartość.",
    "Nie udało się cofnąć zgody: {error}",
    "Usunięto z pamięci podręcznej pełne mody: {count}.",
    "Nie udało się wyczyścić pamięci podręcznej: {error}",
    "Magazyn zaufania zresetowany; każdy mod hosta ponownie poprosi o zgodę.",
    "Nie udało się zresetować zaufania: {error}",
    "Cofnięto zgodę dla {title}.",
    "Zgoda już nie istniała.",
    "Zawartość Spellforge",
    "Dokładne zgody tego gracza - strona {page}/{pages}",
    "Nie zatwierdzono żadnej zawartości rozpowszechnianej przez hosta.",
    "Uruchomiona gra niestandardowa utraciła przygotowaną zawartość hosta.",
    "Nie można zweryfikować przygotowanej zawartości gry niestandardowej: {error}",
    "Zawartość uruchomionej gry niestandardowej różni się od przygotowanego pakietu.",
    "Odrzucono zmienione uruchomienie gry wieloosobowej: {error}",
    "Hostowanie zawartości niestandardowej zostało anulowane.",
    "Nie można sprawdzić metadanych misji niestandardowej: {error}",
    "Nie można hostować misji niestandardowej: {error}",
    "Nie można ogłosić misji niestandardowej: {error}",
    "Tworzenie gry niestandardowej...",
    "Wersje przeglądarkowe mogą dołączać, ale nie mogą hostować zawartości niestandardowej.",
    "Połączenie z bezpośrednim zaproszeniem przeglądarkowym: {error}",
    "Transport bezpośredniego zaproszenia przeglądarkowego zamknął się podczas uzgadniania.",
    "Upłynął czas rozwiązywania bezpośredniego zaproszenia przeglądarkowego.",
    "Anulowano bezpośrednie dołączenie do zawartości niestandardowej.",
    "Bezpośrednie zaproszenie nie wskazało misji.",
    "Bezpośredni host wybrał oryginalną misję `{mission}`, której brak w danych przeglądarki.",
    "Bezpośrednie zaproszenia przeglądarkowe są dostępne tylko w wersjach przeglądarkowych.",
    "Upłynął czas potwierdzania wstępnej kontroli zawartości hosta bez zajmowania miejsca.",
    "Transport wstępnej kontroli zawartości hosta nieoczekiwanie się zamknął.",
    "Połączenie w celu sprawdzenia zawartości hosta: {error}",
    "Host ogłosił zawartość niestandardową, ale wysłał zwykłe Welcome.",
    "Upłynął czas oczekiwania na uwierzytelnioną ofertę zawartości hosta.",
    "Uwierzytelniony host zaoferował zawartość {actual}, inną niż ogłoszenie w lobby {advertised}.",
    "Anulowano dołączenie do zawartości niestandardowej.",
    "Upłynął czas potwierdzania wstępnej kontroli zawartości hosta.",
    "[Mod] {title} - {version}",
];

const ZH_TW: [&str; TEXT_COUNT] = [
    "允許 Spellforge 任務（下次啟動）",
    "下次啟動時，允許執行內容完全相符且已明確信任的 Spellforge 套件。",
    "管理 Spellforge 內容...",
    "主持並聲明授權",
    "要散布完整模組嗎？",
    "沒有作者授權條款；按下後會記錄主機對再散布權限的聲明。",
    "主機 {host} 聲明已獲准在此多人連線中，從 {source} 再散布 `{title}`",
    "任務：{value}",
    "聲稱的作者：{value}",
    "版本：{value}",
    "來源：{value}",
    "授權條款：{value}",
    "已驗證的主機金鑰：{value}",
    "玩家加入前會收到完整的 Lua、地圖、美術、音效及文字模組。",
    "只有在獲准再散布時，才能選擇「主持並聲明授權」。",
    "信任完全相符的模組",
    "要信任主機內容嗎？",
    "原版（沒有 Lua 套件）",
    "授權條款/許可：{value}",
    "散布者金鑰：{value}",
    "下載：{bytes} 位元組",
    "完整模組 SHA-256：",
    "Lua 套件 SHA-256：",
    "此模組包含可執行的任務程式碼。核准僅適用於這些完全相符的雜湊。",
    "此完整的地圖、美術、音效及文字模組，僅針對這個完全相符的雜湊獲得核准。",
    "主機內容需要 Spellforge，但遊戲設定中的「允許 Spellforge 任務」已停用。",
    "未能儲存核准：{error}",
    "上一頁",
    "下一頁",
    "全部撤銷",
    "清除快取",
    "重設信任",
    "撤銷 [{hash}]：{title}",
    "已撤銷 {count} 項完全相符內容的核准。",
    "撤銷失敗：{error}",
    "已從快取移除 {count} 個完整模組。",
    "清除快取失敗：{error}",
    "信任資料已重設；每個主機模組都會再次詢問。",
    "重設信任失敗：{error}",
    "已撤銷 {title} 的核准。",
    "該核准原本就不存在。",
    "Spellforge 內容",
    "此玩家的完全相符核准 - 第 {page}/{pages} 頁",
    "目前沒有獲准的主機散布內容。",
    "已啟動的自訂遊戲遺失了準備好的主機內容。",
    "無法驗證已準備的自訂遊戲內容：{error}",
    "已啟動的自訂遊戲內容與準備好的套件不同。",
    "已拒絕變更過的多人遊戲啟動：{error}",
    "已取消主持自訂內容。",
    "無法檢查自訂任務中繼資料：{error}",
    "無法主持自訂任務：{error}",
    "無法公告自訂任務：{error}",
    "正在建立自訂遊戲...",
    "瀏覽器版本可以加入，但不能主持自訂內容。",
    "連線至瀏覽器直接邀請：{error}",
    "瀏覽器直接邀請的傳輸在交握期間關閉。",
    "解析瀏覽器直接邀請時逾時。",
    "已取消透過直接邀請加入自訂內容。",
    "直接邀請沒有提供任務。",
    "直接連線的主機選擇了原版任務 `{mission}`，但此瀏覽器資料中沒有該任務。",
    "瀏覽器直接邀請僅適用於瀏覽器版本。",
    "確認不占用席位的主機內容預先檢查時逾時。",
    "主機內容預先檢查的傳輸意外關閉。",
    "連線以檢查主機內容：{error}",
    "主機公告了自訂內容，卻傳送一般的 Welcome。",
    "等候已驗證的主機內容提案時逾時。",
    "已驗證的主機提供內容 {actual}，與大廳公告的 {advertised} 不同。",
    "已取消加入自訂內容。",
    "確認主機內容預先檢查時逾時。",
    "[模組] {title} - {version}",
];

const ZH_CN: [&str; TEXT_COUNT] = [
    "允许 Spellforge 任务（下次启动）",
    "下次启动时，允许执行内容完全匹配且已明确受信任的 Spellforge 包。",
    "管理 Spellforge 内容...",
    "主持并声明授权",
    "要分发完整模组吗？",
    "没有作者许可信息；点击后会记录主机对再分发权限的声明。",
    "主机 {host} 声明已获准在此多人会话中从 {source} 再分发 `{title}`",
    "任务：{value}",
    "声称的作者：{value}",
    "版本：{value}",
    "来源：{value}",
    "许可证：{value}",
    "已验证的主机密钥：{value}",
    "玩家加入前会收到完整的 Lua、地图、美术、音频及文本模组。",
    "只有在获准再分发时，才能选择“主持并声明授权”。",
    "信任完全匹配的模组",
    "要信任主机内容吗？",
    "原版（没有 Lua 包）",
    "许可证/许可：{value}",
    "分发者密钥：{value}",
    "下载：{bytes} 字节",
    "完整模组 SHA-256：",
    "Lua 包 SHA-256：",
    "此模组包含可执行的任务代码。批准仅适用于这些完全匹配的哈希。",
    "此完整的地图、美术、音频及文本模组，仅针对这个完全匹配的哈希获得批准。",
    "主机内容需要 Spellforge，但游戏设置中的“允许 Spellforge 任务”已禁用。",
    "未能保存批准：{error}",
    "上一页",
    "下一页",
    "全部撤销",
    "清除缓存",
    "重置信任",
    "撤销 [{hash}]：{title}",
    "已撤销 {count} 项完全匹配内容的批准。",
    "撤销失败：{error}",
    "已从缓存移除 {count} 个完整模组。",
    "清除缓存失败：{error}",
    "信任数据已重置；每个主机模组都会再次询问。",
    "重置信任失败：{error}",
    "已撤销 {title} 的批准。",
    "该批准原本就不存在。",
    "Spellforge 内容",
    "此玩家的完全匹配批准 - 第 {page}/{pages} 页",
    "目前没有获准的主机分发内容。",
    "已启动的自定义游戏丢失了准备好的主机内容。",
    "无法验证已准备的自定义游戏内容：{error}",
    "已启动的自定义游戏内容与准备好的包不同。",
    "已拒绝被更改的多人游戏启动：{error}",
    "已取消主持自定义内容。",
    "无法检查自定义任务元数据：{error}",
    "无法主持自定义任务：{error}",
    "无法公告自定义任务：{error}",
    "正在创建自定义游戏...",
    "浏览器版本可以加入，但不能主持自定义内容。",
    "连接到浏览器直接邀请：{error}",
    "浏览器直接邀请的传输在握手期间关闭。",
    "解析浏览器直接邀请时超时。",
    "已取消通过直接邀请加入自定义内容。",
    "直接邀请没有提供任务。",
    "直接连接的主机选择了原版任务 `{mission}`，但此浏览器数据中没有该任务。",
    "浏览器直接邀请仅适用于浏览器版本。",
    "确认不占用席位的主机内容预检时超时。",
    "主机内容预检的传输意外关闭。",
    "连接以检查主机内容：{error}",
    "主机公告了自定义内容，却发送了普通的 Welcome。",
    "等待已验证的主机内容提议时超时。",
    "已验证的主机提供内容 {actual}，与大厅公告的 {advertised} 不同。",
    "已取消加入自定义内容。",
    "确认主机内容预检时超时。",
    "[模组] {title} - {version}",
];

const KO: [&str; TEXT_COUNT] = [
    "Spellforge 임무 허용(다음 실행)",
    "다음 실행 시 정확히 일치하며 명시적으로 신뢰한 Spellforge 패키지만 실행하도록 허용합니다.",
    "Spellforge 콘텐츠 관리...",
    "호스트 및 권한 확인",
    "전체 모드를 배포하시겠습니까?",
    "제작자의 라이선스 정보가 없습니다. 클릭하면 호스트의 재배포 권한 확인이 기록됩니다.",
    "호스트 {host}은(는) 이 멀티플레이 세션에서 {source}의 `{title}`을(를) 재배포할 권한이 있음을 확인합니다",
    "임무: {value}",
    "표시된 제작자: {value}",
    "버전: {value}",
    "출처: {value}",
    "라이선스: {value}",
    "인증된 호스트 키: {value}",
    "플레이어는 참가하기 전에 Lua, 지도, 그래픽, 오디오 및 텍스트가 포함된 전체 모드를 받습니다.",
    "재배포가 허가된 경우에만 호스트 및 권한 확인을 선택하십시오.",
    "정확히 일치하는 모드 신뢰",
    "호스트 콘텐츠를 신뢰하시겠습니까?",
    "원본(Lua 패키지 없음)",
    "라이선스/허가: {value}",
    "배포자 키: {value}",
    "다운로드: {bytes}바이트",
    "전체 모드 SHA-256:",
    "Lua 패키지 SHA-256:",
    "이 모드에는 실행 가능한 임무 코드가 포함되어 있습니다. 승인은 표시된 해시 값과 정확히 일치하는 경우에만 적용됩니다.",
    "이 전체 지도, 그래픽, 오디오 및 텍스트 모드는 정확히 일치하는 이 해시에만 승인됩니다.",
    "호스트 콘텐츠에 Spellforge가 필요하지만 게임플레이 설정에서 Spellforge 임무 허용이 꺼져 있습니다.",
    "승인을 저장하지 못했습니다: {error}",
    "이전",
    "다음",
    "모두 취소",
    "캐시 지우기",
    "신뢰 초기화",
    "취소 [{hash}]: {title}",
    "정확한 콘텐츠 승인 {count}개를 취소했습니다.",
    "승인 취소 실패: {error}",
    "캐시된 전체 모드 {count}개를 제거했습니다.",
    "캐시 지우기 실패: {error}",
    "신뢰 저장소를 초기화했습니다. 모든 호스트 모드에서 다시 확인합니다.",
    "신뢰 초기화 실패: {error}",
    "{title}의 승인을 취소했습니다.",
    "승인이 이미 존재하지 않습니다.",
    "Spellforge 콘텐츠",
    "이 플레이어의 정확한 승인 - {page}/{pages}페이지",
    "승인된 호스트 배포 콘텐츠가 없습니다.",
    "시작한 사용자 지정 게임에서 준비된 호스트 콘텐츠가 사라졌습니다.",
    "준비된 사용자 지정 게임 콘텐츠를 확인할 수 없습니다: {error}",
    "시작한 사용자 지정 게임의 콘텐츠가 준비된 패키지와 다릅니다.",
    "변경된 멀티플레이 시작을 거부했습니다: {error}",
    "사용자 지정 콘텐츠 호스트를 취소했습니다.",
    "사용자 지정 임무 메타데이터를 검토할 수 없습니다: {error}",
    "사용자 지정 임무를 호스트할 수 없습니다: {error}",
    "사용자 지정 임무를 알릴 수 없습니다: {error}",
    "사용자 지정 게임 생성 중...",
    "브라우저 버전은 참가할 수 있지만 사용자 지정 콘텐츠를 호스트할 수 없습니다.",
    "브라우저 직접 초대에 연결: {error}",
    "핸드셰이크 중 브라우저 직접 초대 전송이 닫혔습니다.",
    "브라우저 직접 초대를 확인하는 중 시간이 초과되었습니다.",
    "직접 초대를 통한 사용자 지정 콘텐츠 참가를 취소했습니다.",
    "직접 초대에 임무가 포함되지 않았습니다.",
    "직접 연결한 호스트가 원본 임무 `{mission}`을(를) 선택했지만 이 브라우저 데이터에는 없습니다.",
    "브라우저 직접 초대는 브라우저 버전에서만 사용할 수 있습니다.",
    "자리를 차지하지 않는 호스트 콘텐츠 사전 검사를 확인하는 중 시간이 초과되었습니다.",
    "호스트 콘텐츠 사전 검사 전송이 예기치 않게 닫혔습니다.",
    "호스트 콘텐츠 검토를 위해 연결: {error}",
    "호스트가 사용자 지정 콘텐츠를 알렸지만 일반 Welcome을 보냈습니다.",
    "인증된 호스트 콘텐츠 제안을 기다리는 중 시간이 초과되었습니다.",
    "인증된 호스트가 제공한 콘텐츠 {actual}은(는) 로비 공지 {advertised}와(과) 다릅니다.",
    "사용자 지정 콘텐츠 참가를 취소했습니다.",
    "호스트 콘텐츠 사전 검사를 확인하는 중 시간이 초과되었습니다.",
    "[모드] {title} - {version}",
];

const TH: [&str; TEXT_COUNT] = [
    "อนุญาตภารกิจ Spellforge (การเปิดครั้งถัดไป)",
    "อนุญาตให้เรียกใช้เฉพาะแพ็กเกจ Spellforge ที่ตรงกันทุกประการและได้รับความไว้วางใจอย่างชัดเจนในการเปิดครั้งถัดไป",
    "จัดการเนื้อหา Spellforge...",
    "โฮสต์และรับรองสิทธิ์",
    "แจกจ่ายม็อดฉบับเต็มหรือไม่?",
    "ไม่มีข้อมูลสิทธิ์ใช้งานจากผู้สร้าง การคลิกจะบันทึกคำรับรองสิทธิ์ในการแจกจ่ายซ้ำของโฮสต์",
    "โฮสต์ {host} รับรองว่ามีสิทธิ์แจกจ่าย `{title}` จาก {source} ซ้ำสำหรับเซสชันผู้เล่นหลายคนนี้",
    "ภารกิจ: {value}",
    "ผู้สร้างที่ระบุ: {value}",
    "รุ่น: {value}",
    "แหล่งที่มา: {value}",
    "สิทธิ์ใช้งาน: {value}",
    "คีย์โฮสต์ที่ยืนยันแล้ว: {value}",
    "ผู้เล่นจะได้รับม็อด Lua แผนที่ ภาพ เสียง และข้อความฉบับเต็มก่อนเข้าร่วม",
    "เลือกโฮสต์และรับรองสิทธิ์เฉพาะเมื่อได้รับอนุญาตให้แจกจ่ายซ้ำเท่านั้น",
    "เชื่อถือม็อดที่ตรงกันทุกประการ",
    "เชื่อถือเนื้อหาของโฮสต์หรือไม่?",
    "เกมต้นฉบับ (ไม่มีแพ็กเกจ Lua)",
    "สิทธิ์ใช้งาน/การอนุญาต: {value}",
    "คีย์ผู้แจกจ่าย: {value}",
    "ดาวน์โหลด: {bytes} ไบต์",
    "SHA-256 ของม็อดฉบับเต็ม:",
    "SHA-256 ของแพ็กเกจ Lua:",
    "ม็อดนี้มีโค้ดภารกิจที่เรียกใช้ได้ การอนุมัติใช้ได้กับแฮชที่ตรงกันทุกประการเหล่านี้เท่านั้น",
    "ม็อดแผนที่ ภาพ เสียง และข้อความฉบับเต็มนี้ได้รับอนุมัติเฉพาะแฮชที่ตรงกันทุกประการนี้เท่านั้น",
    "เนื้อหาของโฮสต์ต้องใช้ Spellforge แต่การอนุญาตภารกิจ Spellforge ถูกปิดในการตั้งค่าการเล่น",
    "ไม่ได้บันทึกการอนุมัติ: {error}",
    "ก่อนหน้า",
    "ถัดไป",
    "เพิกถอนทั้งหมด",
    "ล้างแคช",
    "รีเซ็ตความไว้วางใจ",
    "เพิกถอน [{hash}]: {title}",
    "เพิกถอนการอนุมัติเนื้อหาที่ตรงกันทุกประการแล้ว {count} รายการ",
    "เพิกถอนไม่สำเร็จ: {error}",
    "นำม็อดฉบับเต็มออกจากแคชแล้ว {count} รายการ",
    "ล้างแคชไม่สำเร็จ: {error}",
    "รีเซ็ตที่เก็บความไว้วางใจแล้ว ม็อดจากโฮสต์ทุกม็อดจะถามอีกครั้ง",
    "รีเซ็ตความไว้วางใจไม่สำเร็จ: {error}",
    "เพิกถอนการอนุมัติสำหรับ {title} แล้ว",
    "ไม่มีการอนุมัตินี้อยู่แล้ว",
    "เนื้อหา Spellforge",
    "การอนุมัติที่ตรงกันทุกประการของผู้เล่นนี้ - หน้า {page}/{pages}",
    "ไม่มีเนื้อหาที่โฮสต์แจกจ่ายได้รับการอนุมัติ",
    "เกมกำหนดเองที่เริ่มแล้วสูญเสียเนื้อหาโฮสต์ที่เตรียมไว้",
    "ไม่สามารถตรวจสอบเนื้อหาเกมกำหนดเองที่เตรียมไว้: {error}",
    "เนื้อหาของเกมกำหนดเองที่เริ่มแล้วต่างจากแพ็กเกจที่เตรียมไว้",
    "ปฏิเสธการเริ่มเกมผู้เล่นหลายคนที่ถูกเปลี่ยนแปลง: {error}",
    "ยกเลิกการโฮสต์เนื้อหากำหนดเองแล้ว",
    "ไม่สามารถตรวจสอบข้อมูลกำกับของภารกิจกำหนดเอง: {error}",
    "ไม่สามารถโฮสต์ภารกิจกำหนดเอง: {error}",
    "ไม่สามารถประกาศภารกิจกำหนดเอง: {error}",
    "กำลังสร้างเกมกำหนดเอง...",
    "รุ่นเบราว์เซอร์เข้าร่วมได้ แต่ไม่สามารถโฮสต์เนื้อหากำหนดเอง",
    "เชื่อมต่อคำเชิญโดยตรงของเบราว์เซอร์: {error}",
    "การรับส่งคำเชิญโดยตรงของเบราว์เซอร์ปิดลงระหว่างการจับมือเชื่อมต่อ",
    "หมดเวลาขณะแก้ไขคำเชิญโดยตรงของเบราว์เซอร์",
    "ยกเลิกการเข้าร่วมเนื้อหากำหนดเองผ่านคำเชิญโดยตรงแล้ว",
    "คำเชิญโดยตรงไม่ได้ระบุภารกิจ",
    "โฮสต์โดยตรงเลือกภารกิจต้นฉบับ `{mission}` ซึ่งไม่มีอยู่ในข้อมูลเบราว์เซอร์นี้",
    "คำเชิญโดยตรงของเบราว์เซอร์ใช้ได้เฉพาะในรุ่นเบราว์เซอร์",
    "หมดเวลาขณะยืนยันการตรวจสอบเนื้อหาโฮสต์ล่วงหน้าโดยไม่จองที่นั่ง",
    "การรับส่งสำหรับการตรวจสอบเนื้อหาโฮสต์ล่วงหน้าปิดลงโดยไม่คาดคิด",
    "เชื่อมต่อเพื่อตรวจสอบเนื้อหาโฮสต์: {error}",
    "โฮสต์ประกาศเนื้อหากำหนดเอง แต่ส่ง Welcome แบบปกติ",
    "หมดเวลาขณะรอข้อเสนอเนื้อหาโฮสต์ที่ยืนยันแล้ว",
    "โฮสต์ที่ยืนยันแล้วเสนอเนื้อหา {actual} ซึ่งต่างจากประกาศในล็อบบี้ {advertised}",
    "ยกเลิกการเข้าร่วมเนื้อหากำหนดเองแล้ว",
    "หมดเวลาขณะยืนยันการตรวจสอบเนื้อหาโฮสต์ล่วงหน้า",
    "[ม็อด] {title} - {version}",
];
