[package]
name = "robin_level_data"
version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
robin_engine_types.workspace = true
robin_data_io.workspace = true
robin_util.workspace = true
robin_state_hash_derive.workspace = true
serde = { workspace = true, features = ["derive", "rc"] }
serde_json.workspace = true
bitcode.workspace = true
tracing.workspace = true
thiserror.workspace = true
num_enum = "0.7"
json-patch = "4.2"
serde_ignored = "0.1"

[dev-dependencies]
robin_test_support.workspace = true
tempfile.workspace = true

[lints]
workspace = true
