"""Freeze Tree11's privately baked bark for the coordinator's grouped review."""
import hashlib,json,sys
from pathlib import Path
ROOT=Path(__file__).resolve().parents[3];sys.path.insert(0,str(ROOT/'level-editor/refinement/blender'))
from build_review_gallery import build
B=ROOT/'level-editor/work/croisement03-refinement/restart2'
def sha(p):return hashlib.sha256(Path(p).read_bytes()).hexdigest()
def write(p,d):p.write_text(json.dumps(d,indent=2)+'\n')
def main():
 base=B/'approved-hub-textures-v1/croisement03-tree-11/wood-input-v1';src=base/'source-restored-fill-v1';out=B/'texture-review-tree11-hub-wood-v1';assert not out.exists();model=src/'worker.blend';native=json.loads((src/'native-audit.json').read_text());transfer=json.loads((src/'transfer.json').read_text());assert sha(model)==native['model_sha256']==transfer['model_sha256'];assert native['accepted_bark_changes']==native['provisional_foliage_changes']==native['known_misses']==native['ray_exhaustions']==0
 generation=json.loads((base/'packet-v1/generation-review.json').read_text());assert generation['protected_changes']==0
 for p,h in generation['files'].items():assert sha(p)==h
 assert len(transfer['objects'])==3 and transfer['original_images_exact'] and transfer['crown_exact']
 evidence=[model,src/'transfer.json',src/'native-audit.json',src/'native-comparison.png',src/'actual/textured.png',base/'packet-v1/generation-review.json',base/'normalization.json',B/'approved-hub-v17-v23-plus-two-v1/user-approval.json']
 write(src/'self-review.json',dict(status='PASS author saved eight-view material and native review; independent root and user texture decision pending',model_sha256=sha(model),native_view_index=0,actual_saved_views_reviewed=list(range(8)),native_source=dict(bark_samples=210,visible_bark=202,foliage_samples=2805,changed_or_missing=0),visual_findings=['Fine mottled gray-brown bark covers previously gray stems and branches in all eight saved views.','No broad neutral patches, stretched longitudinal stripes, detached texture blocks or altered silhouettes observed.','Fork and branch connections remain the approved geometry; all native crown texture and alpha remain unchanged.','Generated bark is lighter on the lit base and front stems, and darker on rear stems, consistent with the approved solid lighting sheet.'],limits=['Native comparison uses gray to identify unknown source, not actual filled material.','Contact image is the prior approved geometry context, not a new filled contact render. Geometry and original UVs were proven exact.','Shared Arbre06 runtime ownership and whole-map terrain completion remain separate.'],evidence={str(p):sha(p) for p in evidence}))
 out.mkdir();notes=['APPEARANCE ONLY: inferred bark RGB on exact approved Tree11 geometry; original UVs, source images, crown geometry and alpha retained.','210 observed bark samples (202 visible, eight hidden by native leaves) and 2,805 foliage samples pass source first-hit checks with zero changes or misses.','Generation used the two permitted Leicester bark examples; all protected sheet pixels retained exactly.','Author reviewed all eight saved material views beside the approved before sheet. Original camera is top-left. Independent coordinator and user texture decisions remain pending.','Context image is the prior approved geometry/contact evidence; it still shows old gray bark. This texture-only candidate changes no contact geometry.','The native diagnostic marks unknown regions gray; actual filled materials are shown in the main sheet. Runtime ownership and terrain publication remain separate.']
 write(out/'visual-review.json',dict(status='Author appearance PASS; independent root and user review pending',model_sha256=sha(model),native_view_index=0,notes=notes,evidence={str(src/'self-review.json'):sha(src/'self-review.json')}))
 item=dict(id='croisement03-tree-11-wood-texture',name='North forked tree11 — inferred bark appearance',scope='texture',status='ready-for-user',technical_eligible=True,model=str(model),solid=str(B/'tree11-crown-prototype-v4/physical-opacity-audit/sheet.png'),textured=str(src/'actual/textured.png'),stored_material_textured=str(src/'actual/textured.png'),context=str(B/'tree11-crown-joint-v2/sheet.png'),source_comparison=str(src/'native-comparison.png'),source_comparison_label='Exact known-source first hits / unknown-source gray diagnostic / original art; actual filled model shown above',validation=str(src/'native-audit.json'),ownership=str(src/'transfer.json'),review=str(out/'visual-review.json'),notes=notes)
 manifest=out/'review-candidates.json';write(manifest,dict(map='Croisement03 bark appearance',scope='Texture only on approved Tree11 geometry; independent root review before grouped handoff',items=[item]));build(manifest,out/'gallery',pending_only=True)
 paths=evidence+[src/'self-review.json',manifest,out/'visual-review.json']+[Path(item[k]) for k in ('solid','context')]+list((out/'gallery').rglob('*'));write(out/'freeze.json',dict(status='Frozen author-reviewed texture; root and user review pending',model_sha256=sha(model),files={str(p):sha(p) for p in paths if p.is_file()}));print(manifest)
if __name__=='__main__':main()
