"""Freeze reviewed static Tree06 geometry, excluding runtime and terrain claims."""
import hashlib,json,sys
from pathlib import Path
ROOT=Path(__file__).resolve().parents[3];sys.path.insert(0,str(ROOT/'level-editor/refinement/blender'))
from build_review_gallery import build
B=ROOT/'level-editor/work/croisement03-refinement/restart2'
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def write(p,d):p.write_text(json.dumps(d,indent=2)+'\n')
def main():
 src=B/'tree06-crown-prototype-v4';model=src/'worker.blend';out=B/'geometry-round11-tree06-v4-bound';assert sha(model)=='3fcb08513d379132175b186beca403b6c735b498faf9919a11f217a1dca81b9a';root=json.loads((src/'root-review.json').read_text());assert root['status']=='PASS scoped static geometry root review; user approval pending' and root['model_sha256']==sha(model);native=json.loads((src/'native-audit.json').read_text());assert native['accepted_bark_changes']==native['provisional_foliage_changes']==native['known_misses']==0;assert json.loads((src/'transparency-convergence/receipt.json').read_text())['status']=='PASS';assert sha(src/'root-review-request.json')==root['request_sha256'];out.mkdir(exist_ok=False)
 notes=['STATIC GEOMETRY ONLY: Tree06 own single stem with complete inferred off-map crown. Unknown bark remains gray for later approved fill.', 'All543 accepted bark samples retained:531 visible and12 behind frame0 foliage. All1119 native leaf samples match, zero changes or misses.', 'Neighbor Tree05 reserved175 bark rays retain171 existing first hits and four preexisting coarse holes;19 unsupported inferred leaf faces were removed to avoid new blockage.', 'Gray geometry views preserve physical leaf alpha. The lower native fragment remains asymmetric; inferred supported clusters complete the crown.', 'Only Leicester southeast cottage tree and Leicester moat bank tree are external references; observed RGB is own native art.', 'Joint context includes root-reviewed Tree07, coarse unfinished Tree05 and diagnostic floor. Elevated coarse part, actual rocks and broad painted terrain remain excluded.', 'Arbre07 fragment is provisional construction context. Runtime wind, global order, exclusive membership and whole-map completion are excluded.']
 paths=[model,src/'actual/textured.png',src/'physical-opacity-audit/sheet.png',src/'physical-opacity-audit/receipt.json',src/'native-comparison.png',src/'native-audit.json',src/'self-review.json',src/'root-review.json',src/'transparency-convergence/receipt.json',B/'tree06-crown-joint-v4/sheet.png',B/'tree06-crown-joint-v4/receipt.json'];paths += [Path(p) for p in json.loads((src/'root-review-request.json').read_text())['evidence']];write(out/'visual-review.json',dict(status='SCOPED STATIC GEOMETRY author and root PASS; user pending',model_sha256=sha(model),evidence={str(p):sha(p) for p in paths},native_view_index=0,notes=notes));item=dict(id='croisement03-tree-06',name='North single-stem tree06 — static geometry',status='ready-for-user',technical_eligible=True,model=str(model),solid=str(src/'physical-opacity-audit/sheet.png'),textured=str(src/'actual/textured.png'),context=str(B/'tree06-crown-joint-v4/sheet.png'),source_comparison=str(src/'native-comparison.png'),source_comparison_label='Native expected / saved first-hit / source differences:543bark+1119leaf unchanged',validation=str(src/'native-audit.json'),review=str(out/'visual-review.json'),notes=notes);manifest=out/'review-candidates.json';write(manifest,dict(map='Croisement03 Tree06 static geometry',scope='Static geometry only; inferred bark fill, wind, broader native ownership and terrain excluded',items=[item]));build(manifest,out/'gallery',pending_only=True);paths += [manifest,out/'visual-review.json']+list((out/'gallery').rglob('*'));write(out/'freeze.json',dict(status='Frozen scoped static geometry; user pending',model_sha256=sha(model),files={str(p):sha(p) for p in paths if p.is_file()}));print(manifest)
if __name__=='__main__':main()
