"""Freeze independently reviewed static source foliage additions for grouped approval."""
import json,hashlib,sys
from pathlib import Path
ROOT=Path(__file__).resolve().parents[3];sys.path.insert(0,str(ROOT/'level-editor/refinement/blender'))
from build_review_gallery import build
B=ROOT/'level-editor/work/croisement03-refinement/restart2'
def h(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def write(p,d):p.write_text(json.dumps(d,indent=2)+'\n')
def main():
 source=B/'static-crown-pair-review-v3';request=json.loads((source/'root-review-request.json').read_text());root=json.loads((source/'root-review.json').read_text());assert root['status'].startswith('PASS');assert root['request_sha256']==h(source/'root-review-request.json');assert all(h(Path(p))==sha for p,sha in request['evidence'].items());out=B/'geometry-round7-static-crowns-v3';out.mkdir(exist_ok=False);items=[]
 for row in request['items']:
  n=row['tree'];p=B/f'tree{n}-static-leaf-crown-v3';model=p/'worker.blend';assert h(model)==row['model_sha256'];notes=[f'STATIC GEOMETRY CHANGE ONLY: add{row["source_guard"]["new_static_foliage_pixels"]} previously missing observed static foliage pixels to Tree{n}.', 'All previously approved wood/crown meshes, images, UVs and original known appearance retained. Added foliage RGB is this map own native artwork.', 'Small native source cells receive irregular depth and modest tilt; bounded pixel-scale side thinness and asymmetry remain visible. No repeated smooth ribs or long stretched leaf strips.', 'All accepted bark, original native leaves and added static samples have zero first-hit changes or misses. Native camera is top-left; gray geometry keeps original leaf alpha.', 'Only the two permitted Leicester trees were external morphology references. Known source pixel ownership did not expand during the depth correction.', 'New foliage is STATIC; it must not receive shared Arbre06 frame substitutions. Wind, dynamic membership/global ordering and full scene completion are excluded.', 'Joint context includes unchanged approved Tree13 and ferns35/76 on a diagnostic floor. Ground receiver input and subsequent generated appearance require separate approval.']
  review=out/f'tree{n}-visual-review.json';write(review,dict(status='Author and root scoped static geometry PASS; user pending',model_sha256=h(model),root_review_file=str(source/'root-review.json'),root_review_sha256=h(source/'root-review.json'),notes=notes,evidence=request['evidence']));items.append(dict(id=f'croisement03-tree-{n}',name=f'Tree{n} — added static foliage geometry',status='ready-for-user',technical_eligible=True,model=str(model),solid=str(p/'physical-opacity-audit/sheet.png'),textured=str(p/'actual/textured.png'),context=str(B/'tree12-14-static-leaf-joint-v3/sheet.png'),source_comparison=str(p/'native-comparison.png'),source_comparison_label='Native expected / saved first-hit / source comparison; all known samples unchanged',validation=str(p/'native-audit.json'),review=str(review),notes=notes))
 manifest=out/'review-candidates.json';write(manifest,dict(map='Croisement03 static crown additions',scope='Two changed static geometry cards only',items=items));build(manifest,out/'gallery',pending_only=True);files=dict(request['evidence']);files[str(source/'root-review.json')]=h(source/'root-review.json');files[str(source/'root-review-request.json')]=h(source/'root-review-request.json');files.update({str(p):h(p) for p in out.rglob('*') if p.is_file()});write(out/'freeze.json',dict(status='Frozen scoped static geometry; grouped user approval pending',files=files));print(manifest)
if __name__=='__main__':main()
