"""Freeze reviewed static Tree09 geometry, excluding runtime and terrain claims."""
import hashlib,json,sys
from pathlib import Path
ROOT=Path(__file__).resolve().parents[3];sys.path.insert(0,str(ROOT/'level-editor/refinement/blender'))
from build_review_gallery import build
B=ROOT/'level-editor/work/croisement03-refinement/restart2'
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def write(p,d):p.write_text(json.dumps(d,indent=2)+'\n')
def main():
 src=B/'tree09-crown-prototype-v2';model=src/'worker.blend';out=B/'geometry-round8-tree09-v2';assert sha(model)=='a1f42a5db58998c5303d6e963d951a7097092de6e3fb25266d34e8a51fd1bb31';root=json.loads((src/'root-review.json').read_text());assert root['status']=='PASS scoped source-domain and static geometry root review; user geometry approval pending' and root['model_sha256']==sha(model);native=json.loads((src/'native-audit.json').read_text());assert native['accepted_bark_changes']==native['provisional_foliage_changes']==native['known_misses']==0;assert json.loads((src/'transparency-convergence/receipt.json').read_text())['status']=='PASS';out.mkdir(exist_ok=False)
 notes=['STATIC GEOMETRY ONLY: single-stem tree09 with complete inferred off-map crown and irregular supported lower leaf clusters. Unknown bark remains gray for later approved texture fill.',
 'All146 accepted bark samples retained;143 visible and3 obscured by frame0 foliage. All856 provisional native frame0 leaf samples match exactly, zero changed or missed known pixels.',
 'Gray geometry views preserve physical leaf alpha. Narrow hanging native fragment and broader inferred off-map crown remain asymmetric; completed boundaries use irregular supported foliage. An unsupported low inferred hook was removed; all other geometry and images were retained.',
 'Only the Leicester southeast cottage tree and Leicester moat bank tree are external morphology references. Native foliage RGB is this map’s own source.',
 'Joint context includes root-reviewed Tree10, coarse unfinished Tree08 and diagnostic floor. Actual broad terrain contains unresolved painted foliage and is excluded.',
 'Shared Arbre06 spatial fragment remains provisional. No wind playback, complete global ordering, exclusive dynamic membership or whole-map completion is approved by this card.']
 paths=[model,src/'actual/textured.png',src/'physical-opacity-audit/sheet.png',src/'physical-opacity-audit/receipt.json',src/'native-comparison.png',src/'native-audit.json',src/'self-review.json',src/'root-review.json',src/'transparency-convergence/receipt.json',B/'tree09-crown-joint-v2/sheet.png',B/'tree09-crown-joint-v2/receipt.json'];write(out/'visual-review.json',dict(status='SCOPED STATIC GEOMETRY author and root PASS; user pending',model_sha256=sha(model),evidence={str(p):sha(p) for p in paths},native_view_index=0,notes=notes));item=dict(id='croisement03-tree-10',name='North single-stem tree09 — static geometry',status='ready-for-user',technical_eligible=True,model=str(model),solid=str(src/'physical-opacity-audit/sheet.png'),textured=str(src/'actual/textured.png'),context=str(B/'tree09-crown-joint-v2/sheet.png'),source_comparison=str(src/'native-comparison.png'),source_comparison_label='Native expected / saved first-hit / source differences:146bark+856leaf unchanged',validation=str(src/'native-audit.json'),review=str(out/'visual-review.json'),notes=notes);manifest=out/'review-candidates.json';write(manifest,dict(map='Croisement03 Tree09 static geometry',scope='Static geometry only; inferred bark fill, wind, broader native ownership and terrain excluded',items=[item]));build(manifest,out/'gallery',pending_only=True);paths += [manifest,out/'visual-review.json']+list((out/'gallery').rglob('*'));write(out/'freeze.json',dict(status='Frozen scoped static geometry; user pending',model_sha256=sha(model),files={str(p):sha(p) for p in paths if p.is_file()}));print(manifest)
if __name__=='__main__':main()
