"""Freeze reviewed static Tree08 geometry, excluding runtime and terrain claims."""
import hashlib,json,sys
from pathlib import Path
ROOT=Path(__file__).resolve().parents[3];sys.path.insert(0,str(ROOT/'level-editor/refinement/blender'))
from build_review_gallery import build
B=ROOT/'level-editor/work/croisement03-refinement/restart2'
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def write(p,d):p.write_text(json.dumps(d,indent=2)+'\n')
def main():
 src=B/'tree08-crown-prototype-v1';model=src/'worker.blend';out=B/'geometry-round9-tree08-v1';assert sha(model)=='1d778f8c83d61c0d8b11f856db508c1651fe0389876f7b8884aa750be0bfc02c';root=json.loads((src/'root-review.json').read_text());assert root['status']=='PASS scoped source-domain and static geometry root review; user approval pending' and root['model_sha256']==sha(model);native=json.loads((src/'native-audit.json').read_text());assert native['accepted_bark_changes']==native['provisional_foliage_changes']==native['known_misses']==0;assert json.loads((src/'transparency-convergence/receipt.json').read_text())['status']=='PASS';out.mkdir(exist_ok=False)
 notes=['STATIC GEOMETRY ONLY: three-stem tree08 with complete inferred off-map crown and irregular supported lower leaf clusters. Unknown bark remains gray for later approved texture fill.',
 'All370 accepted bark samples retained;352 visible and18 obscured by frame0 foliage. All1127 provisional native frame0 leaf samples match exactly, zero changed or missed known pixels.',
 'Gray geometry views preserve physical leaf alpha. Narrow hanging native fragment and broader inferred off-map crown remain asymmetric; completed boundaries use irregular supported foliage. Hidden stem connectivity and off-map branches are inferred.',
 'Only the Leicester southeast cottage tree and Leicester moat bank tree are external morphology references. Native foliage RGB is this map’s own source.',
 'Joint context includes root-reviewed Tree09, coarse unfinished Tree07 and diagnostic floor. Actual broad terrain contains unresolved painted foliage and is excluded.',
 'Shared Arbre06 spatial fragment remains provisional. No wind playback, complete global ordering, exclusive dynamic membership or whole-map completion is approved by this card.']
 paths=[model,src/'actual/textured.png',src/'physical-opacity-audit/sheet.png',src/'physical-opacity-audit/receipt.json',src/'native-comparison.png',src/'native-audit.json',src/'self-review.json',src/'root-review.json',src/'transparency-convergence/receipt.json',B/'tree08-crown-joint-v2/sheet.png',B/'tree08-crown-joint-v2/receipt.json'];write(out/'visual-review.json',dict(status='SCOPED STATIC GEOMETRY author and root PASS; user pending',model_sha256=sha(model),evidence={str(p):sha(p) for p in paths},native_view_index=0,notes=notes));item=dict(id='croisement03-tree-08',name='North three-stem tree08 — static geometry',status='ready-for-user',technical_eligible=True,model=str(model),solid=str(src/'physical-opacity-audit/sheet.png'),textured=str(src/'actual/textured.png'),context=str(B/'tree08-crown-joint-v2/sheet.png'),source_comparison=str(src/'native-comparison.png'),source_comparison_label='Native expected / saved first-hit / source differences:370bark+1127leaf unchanged',validation=str(src/'native-audit.json'),review=str(out/'visual-review.json'),notes=notes);manifest=out/'review-candidates.json';write(manifest,dict(map='Croisement03 Tree08 static geometry',scope='Static geometry only; inferred bark fill, wind, broader native ownership and terrain excluded',items=[item]));build(manifest,out/'gallery',pending_only=True);paths += [manifest,out/'visual-review.json']+list((out/'gallery').rglob('*'));write(out/'freeze.json',dict(status='Frozen scoped static geometry; user pending',model_sha256=sha(model),files={str(p):sha(p) for p in paths if p.is_file()}));print(manifest)
if __name__=='__main__':main()
