"""Prepare one scoped saved-material candidate for the coordinator's grouped review."""
import hashlib,json,sys
from pathlib import Path
R=Path(__file__).resolve().parents[3];sys.path.insert(0,str(R/'level-editor/refinement/blender'))
from build_review_gallery import build
B=R/'level-editor/work/croisement03-refinement/restart2'
def sha(p):return hashlib.sha256(Path(p).read_bytes()).hexdigest()
def write(p,d):p.write_text(json.dumps(d,indent=2)+'\n')
def main():
 base=B/'approved-hub-textures-v1/croisement03-tree-10/wood-input-v1';src=base/'source-restored-fill-v1';out=B/'texture-review-tree10-hub-wood-v1';assert not out.exists();model=src/'worker.blend';native=json.loads((src/'native-audit.json').read_text());transfer=json.loads((src/'transfer.json').read_text());review=json.loads((src/'self-review.json').read_text());assert sha(model)==native['model_sha256']==transfer['model_sha256']==review['model_sha256'];assert native['accepted_bark_changes']==native['provisional_foliage_changes']==native['known_misses']==native['ray_exhaustions']==0
 for p,h in review['evidence'].items():assert sha(p)==h
 out.mkdir();notes=['APPEARANCE ONLY: inferred bark RGB on exact hub-approved Tree10 geometry. No canopy or animation changes.','131 observed bark samples (129 visible; two behind native leaves) and 1,895 leaf samples remain unchanged. Original packed RGBA and UVs retained.','The generated request included only Leicester southeast cottage tree and Leicester moat bank tree bark examples. Protected sheet pixels are exact.','Author inspected all eight saved textured views, known-source comparison, and native/oblique contact with approved Trees09/11. Independent coordinator review is pending.','Gray neighboring wood and diagnostic ground are context only. The source comparison uses gray for non-source samples; the stored-material sheet shows the actual filled appearance.','Shared Arbre06 runtime ownership and publication remain separate.']
 write(out/'visual-review.json',dict(status='Author scoped appearance PASS; independent coordinator review pending; user pending',model_sha256=sha(model),native_view_index=0,evidence={str(p):sha(p) for p in [src/'self-review.json',src/'transfer.json',src/'native-audit.json',base/'packet-v1/generation-review.json',B/'approved-hub-v17-v23-plus-two-v1/user-approval.json']},notes=notes))
 item=dict(id='croisement03-tree-10-wood-texture',name='North tree10 — inferred bark appearance',scope='texture',status='ready-for-user',technical_eligible=True,model=str(model),solid=str(B/'tree10-crown-prototype-v3/actual/solid.png'),textured=str(src/'actual/textured.png'),stored_material_textured=str(src/'actual/textured.png'),context=str(base/'filled-contact-v1/sheet.png'),source_comparison=str(src/'native-comparison.png'),source_comparison_label='Known native source samples / saved-model first hits / original context; unknown surfaces gray only in this diagnostic',validation=str(src/'native-audit.json'),ownership=str(src/'transfer.json'),review=str(out/'visual-review.json'),notes=notes)
 manifest=out/'review-candidates.json';write(manifest,dict(map='Croisement03 bark appearance',scope='Texture only on hub-approved Tree10 geometry; root review before grouped handoff',items=[item]));build(manifest,out/'gallery',pending_only=True)
 paths=[model,manifest,out/'visual-review.json',src/'self-review.json',src/'transfer.json',src/'native-audit.json',src/'native-comparison.png',src/'actual/textured.png',base/'filled-contact-v1/sheet.png',base/'filled-contact-v1/receipt.json']+list((out/'gallery').rglob('*'));write(out/'freeze.json',dict(status='Frozen author-reviewed candidate; independent root and user appearance review pending',model_sha256=sha(model),files={str(p):sha(p) for p in paths if p.is_file()}));print(manifest)
if __name__=='__main__':main()
