"""Freeze the exact reviewed receiver input scope for grouped approval."""
import json,hashlib
from pathlib import Path
ROOT=Path(__file__).resolve().parents[3];B=ROOT/'level-editor/work/croisement03-refinement/restart2';D=B/'trio-tree-integration-v1/terrain-input-proposal-v5';OUT=B/'texture-input-round1-trio-ground-v5'
def h(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def write(p,v):p.write_text(json.dumps(v,indent=2)+'\n')
def main():
 OUT.mkdir(exist_ok=False);proof=json.loads((D/'root-review-request.json').read_text());scope=json.loads((D/'scope.json').read_text());root=json.loads((D/'root-review.json').read_text());assert root['status']=='PASS scoped receiver classification for grouped input review';assert root['request_sha256']==h(D/'root-review-request.json');files=dict(proof['evidence']);files.update(scope['source_guards'])
 for ref in scope['supplementary_references']:files[ref['file']]=ref['sha256']
 for p in (D/'root-review-request.json',D/'root-review.json'):files[str(p)]=h(p)
 assert all(h(Path(p))==sha for p,sha in files.items());model=ROOT/'level-editor/library/3d-assets/croisement03/croisement03-terrain/model.glb';files[str(model)]=h(model)
 images=[dict(label=label,file=str(p),sha256=h(p)) for label,p in [('Proposed receiver mask; native map orientation',D/'input-review.png'),('Native camera left, reverse right; current top and proposed neutral bottom',D.parent/'terrain-contact-receiver-v5/source-opposite-ground-comparison.png'),('Retained native dark gaps and reserved context',D.parent/'receiver-residual-diagnosis-v1/residual-native-gaps.png')]]
 images += [dict(label='Same-map observed floor reference: '+Path(ref['file']).stem,file=ref['file'],sha256=ref['sha256']) for ref in scope['supplementary_references']]
 notes=['TEXTURE INPUT ONLY:17,447 exact receiver pixels below Tree12/13/14. No generated appearance, model geometry or publication approved here.','Remove source-supported trio foliage/trunks, temporal source union and exact prior-generated floor footprints beneath eight retiring native parts.','Physical tree known RGBA remains exact; ground pixels outside mask remain exact.1,133 reserved neighbor/fern/root overlaps are excluded.','Remaining dark negative spaces read as shaded background; preserve them with disclosed tiny-edge ambiguity.','Only the two shown observed same-map floor crops are supplementary references; both exclude old generated floor.','Changed static Tree12/14 geometry requires separate approval. Generation waits both this input approval and compatible geometry approval.','After generation, native/reverse saved scene review must rule out remaining duplicate trio painting. Neighboring terrain, wind and whole-map completion remain excluded.']
 identity=dict(asset_id='croisement03-trio-ground-receiver',model_sha256=h(model),evidence=files);revision=hashlib.sha256(json.dumps(identity,sort_keys=True,separators=(',',':')).encode()).hexdigest();item=dict(asset_id=identity['asset_id'],name='Trees12/13/14 — ground receiver fill input',model_sha256=h(model),review_revision=revision,decision='pending',scope='texture-input',evidence=files,displayed_images=images,notes=notes)
 write(OUT/'bound-members.json',dict(items=[item],cards=[dict(card_id='croisement03-trio-ground-receiver-input-v5',title=item['name'],asset_ids=[item['asset_id']])]))
 write(OUT/'ready-candidate.json',dict(version=1,id='croisement03-trio-ground-receiver-input-v5',name=item['name'],asset_ids=[item['asset_id']],scope='texture-input',status='Root PASS; awaiting grouped input approval',candidate_model=str(model),candidate_model_sha256=h(model),review_revision=revision,root_review=root,presentation=dict(main_actual=images[0]['file'],context=images[1]['file'],supplementary_references=images[3:]),disclosures=notes,files={p:dict(path=p,sha256=v) for p,v in files.items()}))
 write(OUT/'freeze.json',dict(status='Frozen grouped input card; no synthesis approval',review_revision=revision,files={**files,str(OUT/'bound-members.json'):h(OUT/'bound-members.json'),str(OUT/'ready-candidate.json'):h(OUT/'ready-candidate.json')}));print(OUT/'bound-members.json')
if __name__=='__main__':main()
