"""Freeze reviewed static Tree05 geometry, excluding runtime and terrain claims."""
import hashlib,json,sys
from pathlib import Path
ROOT=Path(__file__).resolve().parents[3];sys.path.insert(0,str(ROOT/'level-editor/refinement/blender'))
from build_review_gallery import build
B=ROOT/'level-editor/work/croisement03-refinement/restart2'
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def write(p,d):p.write_text(json.dumps(d,indent=2)+'\n')
def main():
 src=B/'tree05-crown-prototype-v5';model=src/'worker.blend';out=B/'geometry-round12-tree05-v5-bound';assert sha(model)=='aa35ee3e30ee69c84d5960a50c9e8dda24e29c94ebf8d2e656e6fb8f9f8f4d39';root=json.loads((src/'root-review.json').read_text());assert root['status']=='PASS scoped static geometry root review; user approval pending' and root['model_sha256']==sha(model);native=json.loads((src/'native-audit.json').read_text());assert native['accepted_bark_changes']==native['provisional_foliage_changes']==native['known_misses']==0;assert json.loads((src/'transparency-convergence/receipt.json').read_text())['status']=='PASS';assert sha(src/'root-review-request.json')==root['request_sha256'];out.mkdir(exist_ok=False)
 notes=['STATIC GEOMETRY ONLY: four observed Tree05 woody tracks and inferred complete off-map crown; unknown bark remains gray pending approved fill.', 'All1138 accepted bark samples retained:1106 visible and32 behind frame0 foliage. All2392 native leaf samples exact, zero known changes or misses.', 'All543 accepted neighboring Tree06 bark rays retain first-hit ownership against its exact root-reviewed geometry.', 'Left main and dark right stems correspond spatially to011 and014; other observed tracks are authored scenery. Coarse012 is not interpreted as a fifth trunk. No gameplay additions are implied.', 'Native hanging foliage remains asymmetric; inferred supported clusters provide reverse volume. Eight source-ray cell offsets and one support bend resolve source ordering with its attachment unchanged.', 'Only Leicester southeast cottage tree and Leicester moat bank tree are external references; observed RGB comes from own map art.', 'Exact Tree06 and diagnostic ground provide local joint context. Final native rock/ivy receiver, painted terrain, wind membership/global ordering and whole map completion remain excluded.']
 paths=[model,src/'actual/textured.png',src/'physical-opacity-audit/sheet.png',src/'physical-opacity-audit/receipt.json',src/'native-comparison.png',src/'native-audit.json',src/'self-review.json',src/'root-review.json',src/'transparency-convergence/receipt.json',B/'tree05-crown-joint-v5/sheet.png',B/'tree05-crown-joint-v5/receipt.json'];paths += [Path(p) for p in json.loads((src/'root-review-request.json').read_text())['evidence']];write(out/'visual-review.json',dict(status='SCOPED STATIC GEOMETRY author and root PASS; user pending',model_sha256=sha(model),evidence={str(p):sha(p) for p in paths},native_view_index=0,notes=notes));item=dict(id='croisement03-tree-05',name='North four-stem tree05 — static geometry',status='ready-for-user',technical_eligible=True,model=str(model),solid=str(src/'physical-opacity-audit/sheet.png'),textured=str(src/'actual/textured.png'),context=str(B/'tree05-crown-joint-v5/sheet.png'),source_comparison=str(src/'native-comparison.png'),source_comparison_label='Native expected / saved first-hit / source differences:1138bark+2392leaf unchanged',validation=str(src/'native-audit.json'),review=str(out/'visual-review.json'),notes=notes);manifest=out/'review-candidates.json';write(manifest,dict(map='Croisement03 Tree05 static geometry',scope='Static geometry only; inferred bark fill, wind, broader native ownership and terrain excluded',items=[item]));build(manifest,out/'gallery',pending_only=True);paths += [manifest,out/'visual-review.json']+list((out/'gallery').rglob('*'));write(out/'freeze.json',dict(status='Frozen scoped static geometry; user pending',model_sha256=sha(model),files={str(p):sha(p) for p in paths if p.is_file()}));print(manifest)
if __name__=='__main__':main()
