"""Freeze the exact planar ground atlas appearance after independent review."""
from pathlib import Path
import hashlib,json,sys
ROOT=Path(__file__).resolve().parents[3];sys.path.insert(0,str(ROOT/'level-editor/refinement/blender'))
from build_review_gallery import build
B=ROOT/'level-editor/work/croisement03-refinement/restart2'
def sha(p):return hashlib.sha256(Path(p).read_bytes()).hexdigest()
def write(p,d):p.write_text(json.dumps(d,indent=2)+'\n')
def main():
 base=B/'approved-hub-textures-v1/trio-ground/correction-v3-region-guide';e=base/'experiment';g=e/'generation-short-no-mask-with-lighting-openrouter-with-auxiliary';v=base/'appearance-review-v3';out=B/'texture-review-trio-ground-v3';assert not out.exists();report=json.loads((v/'review.json').read_text());assert report['protected_changes']==0 and report['editable_pixels']==17447
 for p,h in report['files'].items():assert sha(p)==h
 views=json.loads((e/'views.json').read_text());model=Path(views['audited_glb']);assert sha(model)==views['audited_glb_sha256'];assert sha(views['atlas_source'])==views['atlas_sha256'];assert sha(views['ownership_report'])==views['ownership_sha256']
 for p,h in views['external_geometry_buffers'].items():assert sha(p)==h
 report.update(status='PASS independently reviewed planar atlas appearance; root and user decision pending',visual_findings=['At native scale and enlarged, the two lower-left editable strips now contain granular irregular brown/olive earth and leaf litter. The old smooth cylindrical-looking strips are no longer present.','The upper editable canopy cutouts have varied forest-floor grain continuous with surrounding painted litter and shadows.','The thin bright bark edge adjoining the lower-right editable strip and broad olive patch farther right are protected original artwork, not generated defects. They remain exact.','No magenta or cyan guide regions are reproduced; all output pixels inside the editable domain are the returned raw response.'],scope='Final generated planar atlas appearance only, exact 17,447 approved pixels. Application to a private terrain worker, publication and full-map runtime remain separate.',reviewed_images=['generated-preserved full atlas','filled-detail.png','filled-lower-strips.png','guide-lower-strips.png'])
 write(v/'review.json',report);out.mkdir();notes=['APPEARANCE ONLY: final forest-floor fill inside the exact 17,447 approved terrain-atlas pixels. No geometry, UV, masks or ownership changed.','All other 1,334,233 atlas pixels and every alpha value remain exact. Generation is verified against the archived raw response and all four reference images.','Lower stripped-trunk holes now carry granular brown/olive litter, not smooth upright bands. The cyan/magenta ordinary reference only guided locations; local compositing enforced pixel protection.','Protected original bright bark sliver and broad far-right olive context remain visible intentionally; they fall outside this approved editable domain.','This is the existing planar-atlas exception: one native atlas, not an eight-view object. The linked terrain model is the unchanged approved receiver, not a claim that this new atlas is already baked or published.','Independent author review passed. Coordinator/user appearance approval, private application and runtime integration remain pending.']
 item=dict(id='croisement03-trio-ground-fill-v3',name='Northeast trio ground — completed forest-floor atlas',scope='texture',status='ready-for-user',technical_eligible=True,model=str(model),solid=str(e/'region-guide.png'),solid_label='Approved editable domain only: magenta upper holes, cyan lower strips',textured=str(g/'generated-preserved.png'),textured_label='Final source-preserved planar atlas appearance; not yet integrated',context=str(v/'filled-detail.png'),source_comparison=str(v/'filled-lower-strips.png'),source_comparison_label='8× nearest enlargement of the previously troublesome lower editable strips; surrounding source pixels protected',validation=str(v/'review.json'),ownership=views['ownership_report'],review=str(v/'review.json'),notes=notes)
 manifest=out/'review-candidates.json';write(manifest,dict(map='Croisement03 planar ground appearance',scope='Final atlas appearance only; existing approved planar receiver geometry unchanged; application/integration pending',texture_review=True,items=[item]));build(manifest,out/'gallery',pending_only=True)
 paths=[manifest,v/'review.json',model,Path(views['atlas_source']),Path(views['ownership_report']),e/'views.json',e/'approval.json',base/'request-plan.json']+[Path(p) for p in report['files']]+list(v.glob('*.png'))+list((out/'gallery').rglob('*'))+[Path(p) for p in views['external_geometry_buffers']]
 write(out/'freeze.json',dict(status='Frozen planar atlas appearance; coordinator and user decisions pending',scope='texture-atlas only; receiver geometry already approved',receiver_model_sha256=sha(model),atlas_sha256=sha(g/'generated-preserved.png'),files={str(p):sha(p) for p in paths if p.is_file()}));print(manifest)
if __name__=='__main__':main()
