"""Freeze reviewed static Tree04 geometry, excluding runtime and terrain claims."""
import hashlib,json,sys
from pathlib import Path
ROOT=Path(__file__).resolve().parents[3];sys.path.insert(0,str(ROOT/'level-editor/refinement/blender'))
from build_review_gallery import build
B=ROOT/'level-editor/work/croisement03-refinement/restart2'
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def write(p,d):p.write_text(json.dumps(d,indent=2)+'\n')
def main():
 src=B/'tree04-crown-prototype-v1';model=src/'worker.blend';out=B/'geometry-round13-tree04-v1-bound';assert sha(model)=='d20c52cb8ba0c0cbf33949bca15da63de1b12e83ab9276bf481c7ffd0f925db3';root=json.loads((src/'root-review.json').read_text());assert root['status']=='PASS scoped static geometry for grouped user review; user approval pending' and root['model_sha256']==sha(model);native=json.loads((src/'native-audit.json').read_text());assert native['accepted_bark_changes']==native['provisional_foliage_changes']==native['known_misses']==0;assert json.loads((src/'transparency-convergence/receipt.json').read_text())['status']=='PASS';assert sha(src/'root-review-request.json')==root['request_sha256'];out.mkdir(exist_ok=False)
 notes=['STATIC GEOMETRY ONLY: Tree04 curved left stem and two straighter woody tracks with inferred complete gold crown; unknown bark remains gray.', 'All708 independently classified bark samples retained:699 visible and9 behind frame0 foliage. All3304 gold Arbre07 leaf samples exact, zero changes or misses.', 'All1138 neighboring Tree05 bark first-hit ownership rays are preserved against its exact reviewed geometry.', 'Three tracks correspond spatially to009,008,010. The thin dark425 track and unclassified upper forks remain excluded.', 'Red Arbre08 foreground source is separately retained and not assigned to Tree04; decoded frame0 gold/red alpha domains are disjoint in this crop. Complete global ordering and runtime wind remain separate.', 'Only Leicester southeast cottage tree and Leicester moat bank tree are external references; nativeRGB is own map source.', 'Joint context contains exact Tree05 and diagnostic floor. Native ivy/rock receiver, painted terrain cleanup and final map ground contact remain unfinished.']
 paths=[model,src/'actual/textured.png',src/'physical-opacity-audit/sheet.png',src/'physical-opacity-audit/receipt.json',src/'native-comparison.png',src/'native-audit.json',src/'self-review.json',src/'root-review.json',src/'transparency-convergence/receipt.json',B/'tree04-crown-joint-v1/sheet.png',B/'tree04-crown-joint-v1/receipt.json'];paths += [Path(p) for p in json.loads((src/'root-review-request.json').read_text())['evidence']];write(out/'visual-review.json',dict(status='SCOPED STATIC GEOMETRY author and root PASS; user pending',model_sha256=sha(model),evidence={str(p):sha(p) for p in paths},native_view_index=0,notes=notes));item=dict(id='croisement03-tree-04',name='North three-stem tree04 — static geometry',status='ready-for-user',technical_eligible=True,model=str(model),solid=str(src/'physical-opacity-audit/sheet.png'),textured=str(src/'actual/textured.png'),context=str(B/'tree04-crown-joint-v1/sheet.png'),source_comparison=str(src/'native-comparison.png'),source_comparison_label='Native expected / saved first-hit / source differences:708bark+3304leaf unchanged',validation=str(src/'native-audit.json'),review=str(out/'visual-review.json'),notes=notes);manifest=out/'review-candidates.json';write(manifest,dict(map='Croisement03 Tree04 static geometry',scope='Static geometry only; inferred bark fill, wind, broader native ownership and terrain excluded',items=[item]));build(manifest,out/'gallery',pending_only=True);paths += [manifest,out/'visual-review.json']+list((out/'gallery').rglob('*'));write(out/'freeze.json',dict(status='Frozen scoped static geometry; user pending',model_sha256=sha(model),files={str(p):sha(p) for p in paths if p.is_file()}));print(manifest)
if __name__=='__main__':main()
