"""Freeze Tree02 geometry and the specifically bound Tree03 native leaf revision."""
import hashlib,json,sys
from pathlib import Path
ROOT=Path(__file__).resolve().parents[3];sys.path.insert(0,str(ROOT/'level-editor/refinement/blender'))
from build_review_gallery import build
B=ROOT/'level-editor/work/croisement03-refinement/restart2'
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def write(p,d):p.write_text(json.dumps(d,indent=2)+'\n')
def main():
 src=B/'tree02-isolated-prototype-v7';model=src/'worker.blend';joint=B/'tree02-shared-ridge-joint-v5';derivative=B/'tree03-ridge-leaf-derivative-v2/worker.blend';out=B/'geometry-round15-tree02-shared-ridge-v1'
 assert sha(model)=='63d1308cc5ed95b188c182501a80694f7dae56e79a1e7c88bab3ec7691b1e9a8';assert sha(derivative)=='d785afe9f8f47b4f8c7582925876823ccab100ee36b162cafa7627bc71bc754d'
 root=json.loads((joint/'root-shared-interface-review-v1.json').read_text());assert root['status'].startswith('PASS');assert root['request_sha256']==sha(joint/'root-review-request.json');request=json.loads((joint/'root-review-request.json').read_text());paths=[B/p for p in request['evidence']];assert all(sha(B/p)==h for p,h in request['evidence'].items())
 guard=json.loads((derivative.parent/'receipt.json').read_text());assert guard['image_rgba_unchanged'];assert all(not v['changes'] for v in guard['checks'].values());assert all(not v['changes'] for v in guard['ridge_checks'].values());assert json.loads((derivative.parent/'saved-model-guard.json').read_text())['status'].startswith('PASS');out.mkdir(exist_ok=False)
 notes=['STATIC TREE GEOMETRY: Tree02 trunk, source-supported bent limb and complete inferred crown; additionally the exact Tree03 native leaf-cell2787 depth correction bound to this card. No appearance, wind or completed terrain approval.', 'Tree02 original377 accepted bark and1812 own leaf samples stay exact. The shared candidate preserves2172 Tree02-domain,9358 Tree03-domain and708 Tree04-domain object/face/RGBA first hits.', 'The Tree03 revision moves one independent four-vertex native leaf cell13 world units toward the native camera along its own projection rays. UV, all referenced RGBA, projected coverage and every other surface remain unchanged; saved/reopened guard passes. Frozen prior Tree03 card is not overwritten.', 'The observed footy166 is explained by the foreground bank: authored top85 and source-supported crest hide the lower trunk beginningy167. Both trees remain seated on the original lower ground. The full shared receiver spans both trees; no cutoff avoids Tree03 ownership.', 'The bank is DIAGNOSTIC CONTEXT, not a completed ridge asset: finite crop edges, neutral unseen back and unfinished painted ground remain explicit. Its10-column1–2pixel crest adjustment preserves already accepted visible bark instead of treating mask96 as exclusive material ownership.', 'All unknown gray bark still requires separately approved texture fill. Only Leicester southeast cottage tree and Leicester moat bank tree were external morphology references; all foliage RGB is own native art.', 'Original-camera view is first throughout. Native frame0 spatial comparison does not prove global order, exclusive animated membership, physical wind or whole-map completion.']
 paths += [joint/'root-shared-interface-review-v1.json',joint/'root-review-request.json',src/'review-unclipped-v1/alpha-gray8.png',src/'review-unclipped-v1/actual8.png'];models={'croisement03-tree-02':{'path':str(model),'sha256':sha(model)},'croisement03-tree-03-scoped-leaf2787-derivative':{'path':str(derivative),'sha256':sha(derivative)}}
 write(out/'visual-review.json',dict(status='SCOPED STATIC GEOMETRY author and root PASS; user pending',models=models,evidence={str(p):sha(p) for p in paths},native_view_index=0,notes=notes))
 item=dict(id='croisement03-tree-02-shared-ridge-interface',name='Tree02 — geometry and Tree03 leaf-depth revision',status='ready-for-user',technical_eligible=True,model=str(model),bound_models=models,solid=str(src/'review-unclipped-v1/alpha-gray8.png'),textured=str(src/'review-unclipped-v1/actual8.png'),context=str(joint/'sheet.png'),source_comparison=str(B/'tree02-shared-ridge-contact-v1/contact-comparison.png'),source_comparison_label='Native art / native physical contact / reverse contact; ridge is diagnostic context',validation=str(derivative.parent/'receipt.json'),review=str(out/'visual-review.json'),notes=notes)
 manifest=out/'review-candidates.json';write(manifest,dict(map='Croisement03 shared tree interface',scope='Tree02 static geometry plus exact Tree03 leaf2787 derivative; bank is diagnostic context only',items=[item]));build(manifest,out/'gallery',pending_only=True);paths += [manifest,out/'visual-review.json']+list((out/'gallery').rglob('*'));write(out/'freeze.json',dict(status='Frozen scoped static geometry; user pending',models=models,files={str(p):sha(p) for p in paths if p.is_file()}));print(manifest)
if __name__=='__main__':main()
