"""Freeze reviewed static Tree03 geometry, excluding runtime and terrain claims."""
import hashlib,json,sys
from pathlib import Path
ROOT=Path(__file__).resolve().parents[3];sys.path.insert(0,str(ROOT/'level-editor/refinement/blender'))
from build_review_gallery import build
B=ROOT/'level-editor/work/croisement03-refinement/restart2'
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def write(p,d):p.write_text(json.dumps(d,indent=2)+'\n')
def main():
 src=B/'tree03-crown-prototype-v2';model=src/'worker.blend';out=B/'geometry-round14-tree03-v2-bound';assert sha(model)=='0d71de988e22119da0a19ac0fdc7f0143a8172657e712fd83889ab8cdeaaaf40';root=json.loads((src/'root-review.json').read_text());assert root['status']=='PASS scoped static geometry for grouped user review; user approval pending' and root['model_sha256']==sha(model);native=json.loads((src/'native-audit.json').read_text());assert native['accepted_bark_changes']==native['provisional_foliage_changes']==native['known_misses']==0;assert json.loads((src/'transparency-convergence/receipt.json').read_text())['status']=='PASS';assert sha(src/'root-review-request.json')==root['request_sha256'];out.mkdir(exist_ok=False)
 notes=['STATIC GEOMETRY ONLY: mature Tree03 trunk and bespoke tapered upright/right/short-left branches support a complete inferred red crown. Unknown wood remains gray.', 'All1090 accepted bark samples retained:971 visible and119 behind frame0 foliage. All8387 native red leaf samples exact, zero changes or misses.', 'Neighbor Tree04 retains705 first hits; exactly3 are correctly occluded by matching native red source samples.31 inferred cards were removed to eliminate accidental occlusion.', 'Lower closure extends beneath the observed ledge using existing placement. The diagnostic floor does not establish final ledge/rock contact or painted-terrain cleanup.', 'Only Leicester southeast cottage tree and Leicester moat bank tree are external references; observed foliage is own native Arbre08 art.', 'The far-left Tree02 branch remains separate. Full shared Arbre08 membership, complete global ordering, wind playback and whole-map completion are excluded.']
 paths=[model,src/'actual/textured.png',src/'physical-opacity-audit/sheet.png',src/'physical-opacity-audit/receipt.json',src/'native-comparison.png',src/'native-audit.json',src/'self-review.json',src/'root-review.json',src/'transparency-convergence/receipt.json',B/'tree03-crown-joint-v2/sheet.png',B/'tree03-crown-joint-v2/receipt.json'];paths += [Path(p) for p in json.loads((src/'root-review-request.json').read_text())['evidence']];write(out/'visual-review.json',dict(status='SCOPED STATIC GEOMETRY author and root PASS; user pending',model_sha256=sha(model),evidence={str(p):sha(p) for p in paths},native_view_index=0,notes=notes));item=dict(id='croisement03-tree-03',name='North mature branched tree03 — static geometry',status='ready-for-user',technical_eligible=True,model=str(model),solid=str(src/'physical-opacity-audit/sheet.png'),textured=str(src/'actual/textured.png'),context=str(B/'tree03-crown-joint-v2/sheet.png'),source_comparison=str(src/'native-comparison.png'),source_comparison_label='Native expected / saved first-hit / source differences:1090bark+8387leaf unchanged',validation=str(src/'native-audit.json'),review=str(out/'visual-review.json'),notes=notes);manifest=out/'review-candidates.json';write(manifest,dict(map='Croisement03 Tree03 static geometry',scope='Static geometry only; inferred bark fill, wind, broader native ownership and terrain excluded',items=[item]));build(manifest,out/'gallery',pending_only=True);paths += [manifest,out/'visual-review.json']+list((out/'gallery').rglob('*'));write(out/'freeze.json',dict(status='Frozen scoped static geometry; user pending',model_sha256=sha(model),files={str(p):sha(p) for p in paths if p.is_file()}));print(manifest)
if __name__=='__main__':main()
